### ISSUE TITLE
Certain OS versions failing to pull down?

### ISSUE THREAD

**Issue by telepathine-ltd** [grahampugh/erase-install#101]
Hi, this is a great idea for a tool, thanks! We'd love to leverage it in our environment. However, I've been testing on a completely clean build of Catalina, and this is the response when I've tried to specify os=11.3, 11.3.1 and 11.4- 

<img width="891" alt="Unknown" src="https://user-images.githubusercontent.com/2760869/122258306-e65de580-ce9e-11eb-8667-266da40a416c.png">

It does appear to grab the installer when I run the base command. Am I just missing a piece? Is something wrong?

**Comment by grahampugh** [comment]
I guess you figured out that you should use either `--os=11` or `--version=11.4`.

**Comment by telepathine-ltd** [comment]
Sure did, thanks! It’s a wonder what some non distracted reading will do. Thanks for taking the time to respond, and great work!

Dan
