### ISSUE TITLE
ERROR: Can't find the installer! 

### ISSUE THREAD

**Issue by user1233445** [grahampugh/erase-install#111]
Hi Guys,

I'm trying to use the erase-install script for upgrading Catalina Macs to BigSur with the option to download and install the version as a package. My command looks like this:

`sudo /Library/Management/erase-install/erase-install.sh --os=11 --pkg --reinstall --check-power --depnotify `

The script downloads the package into the folder /Library/Management/erase-install/ but don't install it with the error message  [erase-install] ERROR: Can't find the installer!.

```
Package downloaded to: /Library/Management/erase-install/InstallAssistant-11.5.1-20G80.pkg
   [run_installinstallmacos] InstallAssistant package downloaded.
   [erase-install] Closing DEPNotify download message (language=de)

   [erase-install] ERROR: Can't find the installer! 
```

Maybe I didn't understand the instructions correctly, but normally the package should be installed at the same time, right?
Thank you in advance!

**Comment by Porkpie23** [comment]
Try running it with Force curl

sudo /Library/Management/erase-install/erase-install.sh --force-curl --os=11 --pkg --reinstall --check-power --depnotify

**Comment by user1233445** [comment]
Thank you for your help but I tried it and it don't work. Same error as before message "ERROR: Can't find the installer!". Do you have another idea to fix that?

**Comment by grahampugh** [comment]
Can you try using the package?

**Comment by user1233445** [comment]
Thank you for your answer. I checked the package and I can install it manually without any problems. I used the following command to establish the installation:

`sudo /Library/Management/erase-install/erase-install.sh --force-curl --os=11 --pkg --reinstall --check-power --depnotify`

Below you will find the corresponding logs

> Print: Entry, "AppleLanguages:0", Does Not Exist
> 
>    [erase-install] v0.21.0 script execution started: Mi 29 Sep 2021 15:10:25 CEST
>    [erase-install] Caffeinating this script (pid=895)
>    [free_space_check] OK - 405154736 KB free disk space detected
>    [check_power_status] OK - AC power detected
>    [erase-install] Looking for existing installer
>    [find_existing_installer] No valid installer found.
>    [erase-install] Starting download process
>    [erase-install] Opening jamfHelper download message (language=en)
>    [get_installinstallmacos] Downloading installinstallmacos.py...
>    [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
>    [run_installinstallmacos] Checking that selected OS 11 is available
> 
>    [run_installinstallmacos] This command is now being run:
> 
>    installinstallmacos.py --workdir=/Library/Management/erase-install --ignore-cache --pkg --os=11 --validate 
> 2021-09-29 15:10:26.810 jamfHelper[931:11355] isPrefsCreateCacheFromEnabledAndDefaultInputSources - can't find anything from GetInputSourceEnabledPrefs, use defaultASCIIKeyLayoutDict = <CFBasicHash 0x7fb4ea9197c0 [0x7fffa77c18f0]>{type = mutable dict, count = 3,
> entries =>
> 	0 : <CFString 0x7fffa782c7e8 [0x7fffa77c18f0]>{contents = "InputSourceKind"} = <CFString 0x7fffa7871d28 [0x7fffa77c18f0]>{contents = "Keyboard Layout"}
> 	1 : <CFString 0x7fffa785de68 [0x7fffa77c18f0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xac55b20c2f3f397b [0x7fffa77c18f0]>{value = +3, type = kCFNumberSInt64Type}
> 	9 : <CFString 0x7fffa78274e8 [0x7fffa77c18f0]>{contents = "KeyboardLayout Name"} = German
> }
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 0 11.5G    0  899k    0     0  3223k      0  1:02:45 --:--:--  1:02:45 3212k
> ............
> ............ 
> 100 11.5G  100 11.5G    0     0  13.8M      0  0:14:15  0:14:15 --:--:-- 12.9M
> 
> installinstallmacos.py - get macOS installers from the Apple software catalog
> 
> This Mac:
> Model Identifier : iMac19,1
> 
> Board ID         : Mac-*********************
> OS Version     : 10.14.6
> Build ID           : ****************
> 
>  #  ProductID       Version    Build    Post Date   Title                          
>  1  071-97382       11.6       20G165   2021-09-17  macOS Big Sur                  
>  2  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
> 
> Build 20G165 selected. Downloading #1...
> 
> Package downloaded to: /Library/Management/erase-install/InstallAssistant-11.6-20G165.pkg
>    [run_installinstallmacos] InstallAssistant package downloaded.
>    [erase-install] Closing jamfHelper download message (language=en)
>    [erase-install] 'jamfHelper' ended
> 
>    [erase-install] ERROR: Can't find the installer! 


Thank you in advance.

**Comment by grahampugh** [comment]
Thanks I can reproduce this. Looking into it.

**Comment by grahampugh** [comment]
This should be resolved in 0.22.0+

**Comment by user1233445** [comment]
Thank you. How can I test the 0.22.0 release, cause there isn't a new package uploaded? Or should I use the 0.23 packages?

**Comment by grahampugh** [comment]
@user1233445 apologies, the package is there now. But you can also try the 0.23.0 (even better).

**Comment by user1233445** [comment]
I tried the new package and I got the same error message as before. I used the following command to establish the installation:

`sudo /Library/Management/erase-install/erase-install.sh --force-curl --os=11 --pkg --erase --check-power --depnotify`

I got the following log:

>   [erase-install] v0.22.0 script execution started: Mon Oct  4 14:45:10 CEST 2021
>    [erase-install] Caffeinating this script (pid=4423)
>    [free_space_check] OK - 417509688 KB free disk space detected
>    [check_power_status] OK - AC power detected
>    [erase-install] Looking for existing installer
>    [find_existing_installer] No valid installer found.
>    [erase-install] Starting download process
>    [erase-install] Opening DEPNotify download message (language=en)
>    [get_installinstallmacos] Downloading installinstallmacos.py...
>    [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
>    [run_installinstallmacos] Checking that selected OS 11 is available
> 
>    [run_installinstallmacos] This command is now being run:
> 
>    installinstallmacos.py --workdir=/Library/Management/erase-install --ignore-cache --pkg --os=11 --validate 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 11.5G  100 11.5G    0     0  26.6M      0  0:07:24  0:07:24 --:--:-- 27.1M
> 
> installinstallmacos.py - get macOS installers from the Apple software catalog
> 
> This Mac:
> Model Identifier : MacBookAir6,2
> 
> Board ID         : Mac-xxxxxxxx
> OS Version       : 11.5.2
> Build ID         : 20G95
> 
>  #  ProductID       Version    Build    Post Date   Title                          
>  1  071-71342       11.5       20G71    2021-07-21  macOS Big Sur                  
>  2  071-97382       11.6       20G165   2021-09-17  macOS Big Sur                  
>  3  071-72781       11.5.1     20G80    2021-07-26  macOS Big Sur                  
>  4  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
>  5  071-00696       11.4       20F71    2021-06-02  macOS Big Sur                  
> 
> Build 20G165 selected. Downloading #2...
> 
> Package downloaded to: /Library/Management/erase-install/InstallAssistant-11.6-20G165.pkg
>    [run_installinstallmacos] InstallAssistant package downloaded.
>    [erase-install] Closing DEPNotify download message (language=en)
> 
>    [erase-install] ERROR: Can't find the installer! 

I repeated the command to check if it needed to be run twice (on a second device it worked the second time I ran it). But there I got the following result:

>    [erase-install] v0.22.0 script execution started: Mon Oct  4 15:00:11 CEST 2021
>    [erase-install] Caffeinating this script (pid=4507)
>    [free_space_check] OK - 405363500 KB free disk space detected
>    [check_power_status] OK - AC power detected
>    [erase-install] Looking for existing installer
>    [find_existing_installer] InstallAssistant package found at /Library/Management/erase-install/InstallAssistant-11.6-20G165.pkg.
>    [check_installassistant_pkg_is_valid] Checking validity of /Library/Management/erase-install/InstallAssistant-11.6-20G165.pkg.
>    [check_installassistant_pkg_is_valid] Installer:  < System: 20G95 : invalid build.
>    [erase-install] ERROR: Invalid installer is present. Run with --overwrite option to ensure that a valid installer is obtained.

Thank you in advance for your help.

**Comment by grahampugh** [comment]
Weird, it's working for me. I'll take another look later.

PS, do not use `--force-curl` when using the package installation. It is not useful.

**Comment by grahampugh** [comment]
In the meantime, there is no need for you to use the --pkg option. That's just an experimental option, but it doesn't really have any advantage.
