### ISSUE TITLE
Running the latest script  - issue line 32

### ISSUE THREAD

**Issue by Porkpie23** [grahampugh/erase-install#112]
I'm trying to run the latest script but getting an error on line 32

Result of command:
/Library/Management/erase-install/erase-install.sh: line 32: syntax error near unexpected token `>'
/Library/Management/erase-install/erase-install.sh: line 32: `exec > >(tee ${LOG_FILE}) 2>&1'

Can anyone help?

**Comment by Porkpie23** [comment]
Despite using the latest installer and the described method of deployment through JAMF, I'm still seeing the same error in the logs.... Anyone able to help?

**Comment by grahampugh** [comment]
Line 32 is a blank line.

Line 31 is:

```
exec > >(tee ${LOG_FILE}) 2>&1
```

I'm not sure if what you pasted above is mangled by formatting, but there appear to be extra characters in the line.
How _exactly_ are you adding the script to Jamf?

**Comment by Porkpie23** [comment]
I downloaded the package which was uploaded to JAMF and deployed it with a policy along with the command /Library/Management/erase-install/erase-install.sh --force-curl --reinstall --check-power --version=10.15.7, nothing was changed as the previous version of the package was working

**Comment by grahampugh** [comment]
I'll give the uploaded package a try tomorrow in case it's corrupt. 

By the way, there is no need for --force-curl if you're using the package. installinstallmacos.py is included in the package as well as erase-install.sh, and I update the package whenever there is a new version of either. So you are unnecessarily downloading installinstallmacos again by using --force-curl.

**Comment by grahampugh** [comment]
I tried the 0.21.0 installer package that I had uploaded, and it's working just fine for me. Not sure how you're getting that error, but it doesn't seem to be affecting anyone else.
