### ISSUE TITLE
syntax error: invalid arithmetic operator (error token is ".4")

### ISSUE THREAD

**Issue by ahousseini** [grahampugh/erase-install#12]
There is an error on line 87 at the if statement.

Line [85](https://github.com/grahampugh/erase-install/blob/master/erase-install.sh#L85) gives me `14`:
```
installer_version=$( /usr/bin/defaults read "$installer_app/Contents/Info.plist" DTPlatformVersion | sed 's|10\.||')
```

Line [86](https://github.com/grahampugh/erase-install/blob/master/erase-install.sh#L86) gives me `14.4`:
```
installed_version=$( /usr/bin/sw_vers | grep ProductVersion | awk '{ print $NF }' | sed 's|10\.||')
```

**Comment by grahampugh** [comment]
Hi, this is already addressed in a branch I'm working on at present. It should get into the master in a couple of days: https://github.com/grahampugh/erase-install/blob/installpackages/erase-install.sh

**Comment by grahampugh** [comment]
This should now be fixed in the master branch
