### ISSUE TITLE
Add --confirm flag to be used without --erase

### ISSUE THREAD

**Issue by mattdjerome** [grahampugh/erase-install#123]
We use erase/install to do our in place upgrades. It would be great to prompt the user to save their work and reboot with a timer.

**Comment by grahampugh** [comment]
Please could you test this out in the 0.22.0 pre-release?

**Comment by mattdjerome** [comment]
Sure! Thanks for the speed!

**Comment by mattdjerome** [comment]
Works great. This is VERY much appreciated!
