### ISSUE TITLE
—version=11.6 pulls Monterey

### ISSUE THREAD

**Issue by 12oseA** [grahampugh/erase-install#147]
Firstly, thanks for this script! It's been a major game changer for us. Lately I've noticed that Mac's running catalina will pull Monterey instead. It wasn't an issue with Big Sur (11.3) until today. This is being used as to erase with the jamf parameters set to 

--version=11.6

Also tested with 

--version=11.6.1 

and I'm getting the same results where it attempts Monterey instead.I've also noticed similar issues with both erase and reinstall options.

**Comment by grahampugh** [comment]
Please can you post the full output of the command? You souls see it in /var/log/erase-install.sh if you do a run with --test-run added so that it doesn't actually perform the erase/reinstall.

**Comment by n0brainer** [comment]
Seeing similar behavior with --sameos via jamf/depnotify.  I tried on an 11.6.0 machine and it's trying to load the macOS 12.

`/Library/Management/erase-install/erase-install.sh --sameos --depnotify --erase --confirm --check-power --power-wait-limit 180 --test-run`

**Comment by grahampugh** [comment]
@n0brainer Please can you post the full output of the command? You should see it in `/Library/Management/erase-install/erase-install.log` if you do a run with `--test-run` added so that it doesn't actually perform the erase/reinstall.
