### ISSUE TITLE
Error grabbing installer

### ISSUE THREAD

**Issue by JamesRodgers17** [grahampugh/erase-install#151]
**Describe the bug**
Looks like the script fails to grab installer 

**To Reproduce**
Policy run via Jamf Install command would be:  erase-install.sh --force-curl --upgrade --version-11.6 --overwrite --move
 
**Expected behavior**
Script should run and pull down and download the Installer (version 11.6) and then move the Install macOS Big Sur.app into the /Applications folder

**Code/log output**
Script result: 
   [erase-install] v24.1 script execution started: Wed Nov 10 11:23:40 CST 2021
   [erase-install] Caffeinating this script (pid=9708)
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [get_installinstallmacos] Downloading installinstallmacos.py...
/Library/Management/erase-install/installinstallmacos.py: OK
   [get_installinstallmacos] downloaded new installinstallmacos.py successfully.
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] MacAdmins Python is installed
   [run_installinstallmacos] Checking that selected version 11.6 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --version 11.6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0 2915k    0     0  9687k      0  0:20:52 --:--:--  0:20:52 9655k
  0 11.5G    0 27.3M    0     0  21.0M      0  0:09:23  0:00:01  0:09:22 21.0M  

** I did not include full Dload part of logs due to length, I am just copying and pasting logs from Jamf console ** 

2021-11-10 11:34:16.067 installer[9853:268431] Package /Library/Management/erase-install/content/downloads/57/38/071-97382-A_OEKYSXCO6D/97vrhncortwd3i38zfogcscagmpwksdzce/InstallAssistant.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.qJCIci
installer: The install failed. (The Installer could not install the software because there was no software found to install. The Installer could not install the software.)
Command '['/usr/sbin/installer', '-pkg', '/Library/Management/erase-install/content/downloads/57/38/071-97382-A_OEKYSXCO6D/97vrhncortwd3i38zfogcscagmpwksdzce/071-97382.English.dist', '-target', '/private/tmp/dmg.qJCIci']' returned non-zero exit status 1.
Product installation failed.

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro15,1

Bridge ID        : J680AP
Board ID         : Mac-937A206F2EE63C01
OS Version       : 10.15.7
Build ID         : 19H524

 #  ProductID       Version    Build    Post Date   Title                          
 1  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
 2  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 3  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 4  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
 5  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
 6  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 7  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 8  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 9  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
10  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
11  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
12  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
13  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
14  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
15  071-97382       11.6       20G165   2021-09-17  macOS Big Sur                  
16  002-23774       12.0.1     21A559   2021-10-25  macOS Monterey                 

Build 20G165 selected. Downloading #15...

Making empty sparseimage...
   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.

**Screenshots**
None 

**Environment (please complete the following information):**
 - OS version [10.15.7]
 - erase-install version="24.1".

**Additional context**
After the script failed the first time, it was run again and it gives me the following out put in the Logs:
Script result: 
   [erase-install] v24.1 script execution started: Wed Nov 10 12:08:50 CST 2021
   [erase-install] Caffeinating this script (pid=10546)
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_11.6-20G165.sparseimage.
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	EFI                            	
/dev/disk3s2        	Apple_HFS                      	/Volumes/Install_macOS_11.6-20G165
   [check_installer_is_valid] Checking validity of .
   [check_installer_is_valid] Using DTSDKBuild value from Info.plist
   [check_installer_is_valid] Installer Info.plist could not be found!
   [check_installer_is_valid] Build of existing installer could not be found!

**Comment by grahampugh** [comment]
I suspect this is one of two things:
- The download may have been interrupted/corrupted. Do you get exactly the same error every time (running with `--overwrite`)?
- Do you have any security software on your computer that might be preventing the installation?

**Comment by JamesRodgers17** [comment]
I have not tried it without the --overwrite, but it does seem to be the same error every-time when using the overwrite command. We do have Carbon Black but it should not be flagging the download anymore. Our security team has whitelisted the download. IS there a way around the following log error? Like a way to clear/delete that "Install_macOS_11.6-20G165.sparseimage"?  

Script result: 
   [erase-install] v24.1 script execution started: Wed Nov 10 21:03:19 CST 2021
   [erase-install] Caffeinating this script (pid=68935)
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_11.6-20G165.sparseimage.
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	EFI                            	
/dev/disk3s2        	Apple_HFS                      	/Volumes/Install_macOS_11.6-20G165
   [check_installer_is_valid] Checking validity of .
   [check_installer_is_valid] Using DTSDKBuild value from Info.plist
   [check_installer_is_valid] Installer Info.plist could not be found!
   [check_installer_is_valid] Build of existing installer could not be found!

**Comment by grahampugh** [comment]
`--overwrite` should `clear/delete that "Install_macOS_11.6-20G165.sparseimage"`.

**Comment by MehdiYawari** [comment]
Hallo grahampugh
I would really appreciate your help with the problem that we have, while downloading MacOS Big Sur. 
In Log file I dont see anything that could help me to unterstand why we have this Problem. 
We have the erase-install package on our jamf server and use this command "/Library/Management/erase-install/erase-install.sh --os=11 --move --erase --update --current-user --check-power --confirm --depnotify" to erase and install macos Bigsur. It works perfectly on many of our devices but sometime we get this error "Error obtaining valid installer. Cannot continue." Can you tell me why we get this error?

Many many thanks

here is the log: 
   [erase-install] v24.0 script execution started: Mon Nov 29 11:52:40 CET 2021
   [erase-install] Caffeinating this script (pid=44277)
   [free_space_check] OK - 403290656 KB free disk space detected
   [check_power_status] OK - AC power detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Starting download process
   [erase-install] Opening DEPNotify download message (language=en)
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Checking that selected OS 11 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --os 11 --validate
Error reading /Library/Management/erase-install/content/downloads/01/28/061-86291-A_JPEIWIOZES/enpozvvbmj3mj2dhulhevlt8b429qd5kw0/InstallAssistantAuto.smd: unclosed token: line 304, column 62

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro13,2

Bridge ID        : X619AP
Board ID         : Mac-66E35819EE2D0D05
OS Version       : 10.15.7
Build ID         : 19H1419

Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 1328, in <module>
    main()
  File "/Library/Management/erase-install/installinstallmacos.py", line 926, in main
    product_info = os_installer_product_info(
  File "/Library/Management/erase-install/installinstallmacos.py", line 671, in os_installer_product_info
    if not product_info[product_key]["title"]:
KeyError: 'title'
   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.
   [erase-install] 'DEPNotify' ended

**Comment by Alitejawi** [comment]
I am seeing the same for a couple of my machines: 

`   [erase-install] Caffeinating this script (pid=10154)
   [check_free_space] OK - 279 GB free/purgeable disk space detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_11.5.2-20G95.sparseimage.
/dev/disk2          	GUID_partition_scheme
/dev/disk2s1        	EFI
/dev/disk2s2        	Apple_HFS                      	/Volumes/Install_macOS_11.5.2-20G95
   [check_installer_is_valid] Checking validity of .
   [check_installer_is_valid] Using DTSDKBuild value from Info.plist
   [check_installer_is_valid] Installer Info.plist could not be found!
   [check_installer_is_valid] Build of existing installer could not be found!
   [erase-install] 'caffeinate' ended
/Library/Management/erase-install/erase-install.sh: line 945: 10165 Terminated: 15          /usr/bin/caffeinate -dimsu -w $pid`

**Comment by grahampugh** [comment]
@MehdiYawari and @Alitejawi please open your own bug report - don't assume that your problem is the same as somebody else's. 

@MehdiYawari in your case I suspect a download error. You just have to try again.

@Alitejawi I cannot get any useful information from just a snippet of the output. Please open your own issue and fill in all the requested information.
