### ISSUE TITLE
"__MACOSX" folder created/left in /Applications/Utilities

### ISSUE THREAD

**Issue by crgundersen** [grahampugh/erase-install#153]
Using 24.1 release, a folder "__MACOSX" is created/left behind in /Applications/Utilities. On Slack, Graham mentioned this was due to DEPNotify. It would be great if this folder was removed during workflow. Thanks.

**Comment by grahampugh** [comment]
@crgundersen I think this folder came from a specific release of erase-install (24.0, I think). I do not think it is not in the current release. Can you confirm? I don't think it's worth engineering a section of code to delete the folder under these circumstances.

**Comment by crgundersen** [comment]
@grahampugh I was using the erase-install-depnotify-24.1.pkg (pre-release). I replaced it this am w/ formal release, and I’m seeing the same result where “__MACOSX” folder w/ Oct 27, 2021 2:17 PM modification date is created.

**Comment by grahampugh** [comment]
Very strange. OK let's see what happens in 25.0. I don't see the folder in the source from which the Makefile is making the package, so it would be very odd to appear from nowhere!

**Comment by grahampugh** [comment]
Can you check the 25.0 RC? Note there's nothing in here to delete the folder, but hopefully it isn't putting it back.

**Comment by crgundersen** [comment]
@grahampugh Using erase-install-depnotify-25.0.pkg, “__MACOSX” folder is still created in /Applications/Utilities, but with Date Modified of today at 10:40 AM.

**Comment by grahampugh** [comment]
I've updated a corrected `erase-install-depnotify-25.0.pkg` which does not have the `__MACOSX` folder (according to Suspicious Package scrutiny). I had put the cleanup command in the wrong place in the Makefile - now fixed.

**Comment by crgundersen** [comment]
Confirmed. No `__MACOSX` folder is created w/ corrected `erase-install-depnotify-25.0.pkg` pre-release. Thanks much @grahampugh
