### ISSUE TITLE
erase-install 24.1 - package installation after Reinstallation doesn't work

### ISSUE THREAD

**Issue by user1233445** [grahampugh/erase-install#157]
It seems that signed packages in the folder /Library/Management/erase-install/extras are not installed in version 24.1 after the reinstallation. In the logs it finds the package to be installed but doesn't install it.

**Comment by grahampugh** [comment]
Please provide logs.

**Comment by user1233445** [comment]
below you will find the logs:

`
   [erase-install] v24.1 script execution started: Mon Nov 15 11:54:58 CET 2021
   [erase-install] Caffeinating this script (pid=1845)
   [free_space_check] OK - 225756320 KB free disk space detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Opening DEPNotify download message (language=de)
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Checking that selected OS 11 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --os 11 --validate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0  466k    0     0  1795k      0  1:52:38 --:--:--  1:52:38 1788k
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   188  100   188    0     0   5222      0 --:--:-- --:--:-- --:--:--  5222
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.WjGRmw
installer: The install was successful.

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookAir6,2

Board ID         : Mac-XXX
OS Version       : 11.6
Build ID         : 20G165

 #  ProductID       Version    Build    Post Date   Title                          
 1  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
 2  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 3  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 4  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
 5  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
 6  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 7  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 8  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 9  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
10  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
11  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
12  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
13  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
14  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
15  071-97382       11.6       20G165   2021-09-17  macOS Big Sur                  
16  002-23589       11.6.1     20G224   2021-10-25  macOS Big Sur                  
17  002-23774       12.0.1     21A559   2021-10-25  macOS Monterey                 

Build 20G224 selected. Downloading #16...

Making empty sparseimage...
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
Product downloaded and installed to /Library/Management/erase-install/Install_macOS_11.6.1-20G224.sparseimage
   [run_installinstallmacos] Mounting sparse disk image to identify installer app.
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	EFI                            	
/dev/disk2s2        	Apple_HFS                      	/Volumes/Install_macOS_11.6.1-20G224
   [erase-install] Installer is at: /Volumes/Install_macOS_11.6.1-20G224/Applications/Install macOS Big Sur.app
   [erase-install] Closing DEPNotify download message (language=de)
/Library/Management/erase-install/erase-install.sh: line 716: kill: (1886) - No such process

   [erase-install] WARNING! Running /Volumes/Install_macOS_11.6.1-20G224/Applications/Install macOS Big Sur.app with eraseinstall option

   [find_extra_installers] Additional package to install: /Library/Management/erase-install/extras/ThinProv-DeleteComputerEntry-1.3.pkg
   [erase-install] Opening DEPNotify full screen message (language=de)
By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.
Preparing to run macOS Installer...

Preparing: 0.0%            
Preparing: 0.1%               
Preparing: 99.4%            
Preparing: 100.1%            
Preparing: 100.9%            
Preparing: 101.8%            
`

**Comment by grahampugh** [comment]
Can you run the command with `--test-run` please? I'd like to see the constructed `startosinstall` command from the output.

**Comment by user1233445** [comment]
Below you will find the logs with the -test-run command:

```
   [erase-install] v24.1 script execution started: Fri Nov 19 09:43:42 CET 2021
   [erase-install] Caffeinating this script (pid=1794)

*** TEST-RUN ONLY! ***
* This script will perform all tasks up to the point of erase or reinstall,
* but will not actually erase or reinstall.
* Remove the --test-run argument to perform the erase or reinstall.
**********************

   [free_space_check] OK - 3872583016 KB free disk space detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Opening DEPNotify download message (language=en)
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Checking that selected OS 11 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --os 11 --validate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 99 11.5G   99 11.5G    0     0  26.5M      0  0:07:26  0:07:26 --:--:-- 27.3M
100 11.5G  100 11.5G    0     0  26.5M      0  0:07:26  0:07:26 --:--:-- 27.3M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1611k  100 1611k    0     0  5149k      0 --:--:-- --:--:-- --:--:-- 5149k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1952k  100 1952k    0     0  3784k      0 --:--:-- --:--:-- --:--:-- 3776k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5778  100  5778    0     0  41568      0 --:--:-- --:--:-- --:--:-- 41568
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2571k  100 2571k    0     0  8061k      0 --:--:-- --:--:-- --:--:-- 8061k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   188  100   188    0     0   1634      0 --:--:-- --:--:-- --:--:--  1634
100   188  100   188    0     0   1634      0 --:--:-- --:--:-- --:--:--  1620
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.D3dQkx
installer: The install was successful.

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro16,1

Bridge ID        : XXXXXXX
Board ID         : Mac-XXXXXXXX
OS Version       : 11.6.1
Build ID         : 20G224

 #  ProductID       Version    Build    Post Date   Title                          
 1  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
 2  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 3  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 4  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
 5  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
 6  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 7  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 8  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 9  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
10  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
11  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
12  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
13  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
14  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
15  071-97382       11.6       20G165   2021-09-17  macOS Big Sur                  
16  002-23589       11.6.1     20G224   2021-10-25  macOS Big Sur                  
17  002-23774       12.0.1     21A559   2021-10-25  macOS Monterey                 

Build 20G224 selected. Downloading #16...

Making empty sparseimage...
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
Product downloaded and installed to /Library/Management/erase-install/Install_macOS_11.6.1-20G224.sparseimage
   [run_installinstallmacos] Mounting sparse disk image to identify installer app.
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	EFI                            	
/dev/disk2s2        	Apple_HFS                      	/Volumes/Install_macOS_11.6.1-20G224
   [erase-install] Installer is at: /Volumes/Install_macOS_11.6.1-20G224/Applications/Install macOS Big Sur.app
   [erase-install] Closing DEPNotify download message (language=en)
/Library/Management/erase-install/erase-install.sh: line 716: kill: (1835) - No such process

   [erase-install] WARNING! Running /Volumes/Install_macOS_11.6.1-20G224/Applications/Install macOS Big Sur.app with eraseinstall option

   [find_extra_installers] Additional package to install: /Library/Management/erase-install/extras/ThinProv-DeleteComputerEntry-1.3.pkg
   [erase-install] Opening DEPNotify full screen message (language=en)
   [erase-install] Run without '--test-run' to run this command:
/Volumes/Install_macOS_11.6.1-20G224/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall --eraseinstall --allowremoval --forcequitapps --pidtosignal 2977 --pidtosignal 1806 --agreetolicense --nointeraction --installpackage /Library/Management/erase-install/extras/ThinProv-DeleteComputerEntry-1.3.pkg
/Library/Management/erase-install/erase-install.sh: line 705:  2978 Killed: 9               dep_notify_progress startosinstall > /dev/null 2>&1
   [erase-install] 'caffeinate' ended

```

**Comment by grahampugh** [comment]
The outputted command seems correct. Can you try running the command independently and see if it works?.

Probably easier if you use `erase-install.sh --move` to extract the installer app into /Applications. Then you can run:

```
/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall --eraseinstall --allowremoval --forcequitapps --agreetolicense --nointeraction --installpackage /Library/Management/erase-install/extras/ThinProv-DeleteComputerEntry-1.3.pkg
```

If that fails, I'm curious if you have tried with any other package. Maybe your package is not suitable.

**Comment by user1233445** [comment]
Hi, 

I tried it with the command you wrote, but it didn't work. If I install the package with the installer application, it works flawlessly. Do you have an idea where's the problem is?

I remember that the package must be a distribution and not a component package. Is that correct?

**Comment by grahampugh** [comment]
Sorry I don't know the answer to that. I've never personally used that option as we don't need to distribute any packages that early in our enrollment. 

Good to know it's not a problem with the script though.
