### ISSUE TITLE
Allow the end-user more than one attempt to successfully enter their account password.

### ISSUE THREAD

**Issue by ryangball** [grahampugh/erase-install#159]
**Is your feature request related to a problem? Please describe.**
On Apple Silicon Macs when the logged-in user is prompted to enter their password in order to complete the upgrade, they only have one opportunity to do so correctly.

**Describe the solution you'd like**
Allow the end-user more than one opportunity (maybe 5 max) to successfully enter their own password before exiting with an error.

**Describe alternatives you've considered**
Add a loop testing that `/usr/bin/dscl /Search -authonly "$user" "$password"` is successful, and if not letting the end-user know that their password was not correct and giving them the opportunity to try again. If they enter their password incorrectly 5 times, display the same error they already receive and then exit abnormally. I don't think there is enough of a need to customize the number of times they can try (adding more complexity and command line arguments), but I feel like a max should be hard-coded in.

**Comment by grahampugh** [comment]
Please check out the 25.0 RC. I added the opportunity to get it wrong 5 times. Note that an empty password submission currently counts the same as pressing Cancel, so you then don't get more attempts. I may try to figure out how better to catch the Cancel button, but my initial attempt didn't work so I had to plump for checking for an empty string instead.

**Comment by grahampugh** [comment]
Should be fixed now in v25.0. Let me know if not.
