### ISSUE TITLE
Mobile account - this account cannot be used to to perform the reinstall

### ISSUE THREAD

**Issue by talving** [grahampugh/erase-install#162]
When a Mobile Account without Admin permissions tries to run this they get "this account cannot be used to to perform the reinstall" possible to run this as a non local admin? 

Alternative is basically deploying a temp admin account on the device and allow user to use that one time for upgrading.

**Comment by grahampugh** [comment]
Are you talking about `--reinstall` or `--erase`? The `--erase` option already promotes the user to admin. The `--reinstall` option should not need admin rights so long as the user is a Volume Owner.

**Comment by talving** [comment]
Using:
`/Library/Management/erase-install/erase-install.sh --os=12 --update --reinstall --confirm --depnotify`

**Comment by grahampugh** [comment]
Is this on Intel or Apple Silicon, and are your mobile users Volume Owners?

**Comment by talving** [comment]
Apple Silicon.
Nope users are not Volume Owners. This is due to very strict rules from clients.

Possible to have the script run with admin rights without user input?

**Comment by grahampugh** [comment]
You can't run `startosinstall` on Apple Silicon Macs without being a Volume Owner.

**Comment by talving** [comment]
Possible to run this as a admin without giving the user admin login? Like having a flag --adminlogin with username/password deployed remote?

**Comment by grahampugh** [comment]
I'm reluctant to supply an option for passing a password in remotely. It seems very insecure to allow a `--password` option. Far less secure than just allowing your users to be Volume Owners, for example.

**Comment by talving** [comment]
The problem is that we work closely with big client that follow the so called TPN. This makes it so users are only allowed to have mobile accounts and therefor not be volume owners. 
I'm trying to figure out the best way to deploy updates remote without giving the user any Admin access. 

Only way around this on a M1 Mac seems to be using a admin password to install the new update.

**Comment by grahampugh** [comment]
I'm pretty sure mobile accounts can be Volume Owners. And any account that you use has to be a Volume Owner, whether it is admin or not.
