### ISSUE TITLE
Script is attempting to install from existing installers in /Applications/ that are different from the version specified as a parameter. 

### ISSUE THREAD

**Issue by erishiamu** [grahampugh/erase-install#163]
**Describe the bug**
we are executing an upgrade on Mojave clients to Catalina specifying --os=10.15 in the payload, clients with existing macos installers for different versions in /Applications/ are attempting to install those versions instead. This works for Big Sur but simply errors out for Monterey installers. 

**To Reproduce**
We deployed the current release pkg and are using this command in a files and processes > execute command policy paylod:
/Library/Management/erase-install/erase-install.sh --reinstall --update --os=10.15

**Expected behavior**
We expected the script to install the newest 10.15 build for the hardware if it is already download and download it if not, instead it is attempting to install non 10.15 versions using random installers in /Applications/

**Code/log output**
erase-install] v0.23.0 script execution started: Tue Nov 16 16:45:18 MST 2021
   [erase-install] Caffeinating this script (pid=19823)
   [free_space_check] OK - 57024540 KB free disk space detected
   [erase-install] Looking for existing installer
   [find_existing_installer] Installer found at /Applications/Install macOS Monterey.app.
   [check_installer_is_valid] Checking validity of /Applications/Install macOS Monterey.app.
   [check_installer_is_valid] Using Build value from com_apple_MobileAsset_MacSoftwareUpdate.xml
Volume Shared Support on disk2s2 force-unmounted
   [check_installer_is_valid] Installer: 21A559 >= System: 18G9323 : valid build.
   [erase-install] Checking for newer installer
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install
   [check_newer_available] Checking available: 18F2059 vs. installer: 21A559
   [check_newer_available] Checking available: 18G103 vs. installer: 21A559
   [check_newer_available] Checking available: 17G66 vs. installer: 21A559
   [check_newer_available] Checking available: 18E2034 vs. installer: 21A559
   [check_newer_available] Checking available: 17F66a vs. installer: 21A559
   [check_newer_available] Checking available: 19D2064 vs. installer: 21A559
   [check_newer_available] Checking available: 19E2269 vs. installer: 21A559
   [check_newer_available] Checking available: 19G2006 vs. installer: 21A559
   [check_newer_available] Checking available: 19G2021 vs. installer: 21A559
   [check_newer_available] Checking available: 19H2 vs. installer: 21A559
   [check_newer_available] Checking available: 19H4 vs. installer: 21A559
   [check_newer_available] Checking available: 19H15 vs. installer: 21A559
   [check_newer_available] Checking available: 20G95 vs. installer: 21A559
   [check_newer_available] Checking available: 21A559 vs. installer: 21A559
   [check_newer_available] No newer builds found

   [erase-install] WARNING! Running /Applications/Install macOS Monterey.app with reinstall option

   [erase-install] Opening jamfHelper full screen message (language=en)
Error: You may not install to this volume because it has a disk password.
By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.
   [erase-install] 'Self Service' ended
   [erase-install] 'jamfHelper' ended
/Library/Management/erase-install/erase-install.sh: line 637: 19952 Terminated: 15          "$jamfHelper" -windowType $window_type -title "${!dialog_reinstall_title}" -heading "${!dialog_reinstall_heading}" -description "${!dialog_reinstall_desc}" -icon "$dialog_reinstall_icon"
   [erase-install] 'caffeinate' ended

**Screenshots**

**Environment (please complete the following information):**
 - OS version: current 10.14.X, 10.14.6 and 10.14.5 clients have both behaved in this way. 
 - erase-install version : 24.1
  
**Additional context**

**Comment by grahampugh** [comment]
That is the expected behaviour of the script. See the wiki:

> If an installer is already cached on the system, either in the working directory or in /Applications, the script will detect this and do nothing more.

If you want to ensure that the installer in `/Applications` is valid, use the `--update` option. If you want to delete it and download a fresh one, use the `--overwrite` option. If you want some new parameter to ensure that any existing installer is exactly what you specify, then file a Feature Request (not a bug report) or supply a PR.
