### ISSUE TITLE
--overwrite issue

### ISSUE THREAD

**Issue by mvught** [grahampugh/erase-install#175]
**Describe the bug**
We use the script in JAMF with the following arguments:
--erase--confirm--sameos--check-power--overwrite--current-user--depnotify but the --overwrite ignore the following folder:
/Library/Management/erase-install/Install_macOS_12.1-21C52.sparseimage

So if the script fails and the end user runs it again we get an error in JAMF policy failed.

**To Reproduce**
Run the script and create a Restricting to prevent to update/upgrade. 
Run the script again and the problem is there in de logging.
 
**Expected behavior**
To fix this i made a script before to get rid off the spareimage
#Cleanup
rm -rf /Library/Management/erase-install/

**Code/log output**
[erase-install] Looking for existing installer app or pkg       [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_12.1-21C52.sparseimage.

**Screenshots**
None

**Environment (please complete the following information):**
BS and Monterey
v0.25.0

**Comment by grahampugh** [comment]
Can you post me the full output log please?

**Comment by mvught** [comment]
He Graham,

I have flushed the logs ..... man o man, so I'm trying to reproduce the problem here. It will take some time to track it down ;0
