### ISSUE TITLE
JAMF EA "System Wiped"

### ISSUE THREAD

**Issue by mvught** [grahampugh/erase-install#176]
**Is your feature request related to a problem? Please describe.**
Feature to read out the system is wiped and we can read it out.

**Describe the solution you'd like**
touch file anywhere to read it's done: /Library/Application Support/JAMF/bin/com.eraseandinstall.done
($JAMF recon is required to read out the touch before reboot)

**Describe alternatives you've considered**
If have done it now but before erase v0.25.0 is running, so if its fails than the touch is set. (that's not very reliable)

**Additional context**
JAMF EA:
#!/usr/bin/env bash
RESULT="Not Wiped"
if [ -f "/Library/Application Support/JAMF/bin/com.eraseandinstall.done" ] ; then
  RESULT="System Wiped"
fi
/bin/echo "<result>$RESULT</result>"

**Comment by grahampugh** [comment]
Hi,

I think the latest that you could lay down a file is immediately prior to the startosinstall command running. This is already possible using the following argument:

```
    --preinstall-command 'some arbitrary command'
                        Supply a shell command to run immediately prior to startosinstall
                        running. An example might be 'jamf recon -department Spare'.
                        Ensure that the command is in quotes.
 ```
You'd also have to run the `recon` at that point - there's no opportunity to do this once `startosinstall` begins.

Perhaps an alternative that you could use is the output from DEPNotify log file (`/var/tmp/depnotify.log `) (if you are using the `--depnotify` option), which would report that 100% of preparation had happened (on Monterey+). But there would be no opportunity for a `recon`, so I'm not sure if that's useful.

**Comment by ryangball** [comment]
Seems like a good use case for the --extras argument and a custom package to lay down the breadcrumb.

https://github.com/grahampugh/erase-install/wiki/7.-Erasing-and-reinstalling-macOS#additional-packages-to-install-after-macos-is-installed

**Comment by mvught** [comment]
Hello Graham,

Thats the thing I have done at the moment:
"Run Script erase-reinstall-helper-before"

In this script I run:
# Erase macbook touch
echo "Erase macbook touch"
touch "/Library/Application Support/JAMF/bin/com.eraseandinstall.done"
"$JAMF_BINARY" recon

After that i run your script 
<img width="772" alt="Screenshot 2022-01-11 at 22 14 53" src="https://user-images.githubusercontent.com/14079626/149022897-7dd5135d-37ce-4eef-bbc1-b6132db46c79.png">

**Comment by grahampugh** [comment]
As I said earlier, you can already do that with the --preinstall-command option.

**Comment by romiksbmnn** [comment]
> As I said earlier, you can already do that with the --preinstall-command option.
> 
> I think Ryan's suggestion is better though, as it would then only lay the breadcrumb if the reinstall was successful.

Please tell how to use two commands with --preinstall-command option (the same issue like inmvught : need to create file and then do jamf recon

**Comment by grahampugh** [comment]
@romiksbmnn You could try `--preinstall-command "some command; some other command"` (that's the standard way to run two commands in one line using shell).

I haven't tried it, so report back if it works (or doesn't).

**Comment by romiksbmnn** [comment]
It will be correct ?  --preinstall-command "touch "/Library/Application Support/JAMF/bin/com.eraseandinstall.done"; jamf recon"

**Comment by romiksbmnn** [comment]
> @romiksbmnn You could try `--preinstall-command "some command; some other command"` (that's the standard way to run two commands in one line using shell).
> 
> I haven't tried it, so report back if it works (or doesn't).

It will be correct ? --preinstall-command "touch "/Library/Application Support/JAMF/bin/com.eraseandinstall.done"; jamf recon"

**Comment by grahampugh** [comment]
Nope, you have quotes within quotes. Use single quotes for the inner ones, or drop them and use a backslash in the path's spaces.

**Comment by romiksbmnn** [comment]
> Nope, you have quotes within quotes. Use single quotes for the inner ones, or drop them and use a backslash in the path's spaces. 

No it doesn't work, i want to modify your script for my own. I need to put command touch and jamf recon after button "comfirm". Maybe you can help where i must put it in the script?

**Comment by romiksbmnn** [comment]
> Hello Graham,
> 
> 
> 
> Thats the thing I have done at the moment:
> 
> "Run Script erase-reinstall-helper-before"
> 
> 
> 
> In this script I run:
> 
> ```
> 
> Erase macbook touch
> 
> echo "Erase macbook touch"
> 
> touch "/Library/Application Support/JAMF/bin/com.eraseandinstall.done"
> 
> "$JAMF_BINARY" recon
> 
> ```
> 
> 
> 
> After that i run your script 
> 
> <img width="772" alt="Screenshot 2022-01-11 at 22 14 53" src="https://user-images.githubusercontent.com/14079626/149022897-7dd5135d-37ce-4eef-bbc1-b6132db46c79.png">
> 
> 
> 
> But it would be nice to have it somewhere in the script
> 
> 
> 
> 

Did you solve your problem?

**Comment by ryangball** [comment]
You can't just do this?

--preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done; jamf recon'

**Comment by romiksbmnn** [comment]
> You can't just do this?
> 
> --preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done; jamf recon'

Yes i tried to  do this but after that nothing happens, file hasn't been created and jamf recon didn't work, I will try to do this again and reply. Thanks

**Comment by romiksbmnn** [comment]
> You can't just do this?
> 
> --preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done; jamf recon'

Hi. It doesn't work for me

**Comment by romiksbmnn** [comment]
> Nope, you have quotes within quotes. Use single quotes for the inner ones, or drop them and use a backslash in the path's spaces.

How can I integrate it into the script? Thanks

**Comment by romiksbmnn** [comment]
> --preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done; jamf recon'

command creates file /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done;  (com.eraseandinstall.done;) but it's not correct it creates file with semicolon (;) and didn't execute the second command

**Comment by romiksbmnn** [comment]
> @romiksbmnn You could try `--preinstall-command "some command; some other command"` (that's the standard way to run two commands in one line using shell).
> 
> I haven't tried it, so report back if it works (or doesn't).

I see in 26 version Multiple --postinstall-command arguments can now be supplied.  please can you help with it? I need to run 2 commands before startoinstall --preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done; jamf recon'

**Comment by romiksbmnn** [comment]
> Nope, you have quotes within quotes. Use single quotes for the inner ones, or drop them and use a backslash in the path's spaces. 

Dear Grahampugh please could you explain multiple preinstall commands how to?

**Comment by grahampugh** [comment]
Please ensure you have downloaded the latest version of v26.0, which I just uploaded now. 

You can now do either of the following:

```
--preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done; jamf recon'
```

```
--preinstall-command 'touch /Library/Application\ Support/JAMF/bin/com.eraseandinstall.done' --preinstall-command 'jamf recon'
