### ISSUE TITLE
Trying to do an erase and reload in Big Sur

### ISSUE THREAD

**Issue by TheRossRoss** [grahampugh/erase-install#181]
Describe the bug
We use the script in JAMF with the following arguments:
/Library/Management/erase-install/erase-install.sh --build=20G314 --erase --depnotify --confirm --current-user --overwrite or 
/Library/Management/erase-install/erase-install.sh --os=11 --erase --depnotify --confirm --current-user --overwrite

When running the script we get **[run_installinstallmacos] Error obtaining valid installer. Cannot continue.** even though earlier in the script it finds either the OS or the Build version.

To Reproduce
run the command either directly on the machine in terminal like we normally do or add a self service button (end user remote wipe for when we can't be in front of the machine)

Expected behavior
Computer erases and reloads the OS or Build we've specified.

Code/log output
   [erase-install] Caffeinating this script (pid=16108)
   [check_free_space] OK - 460 GB free/purgeable disk space detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Opening DEPNotify download message (language=en)
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Non-standard catalog URL selected
   [run_installinstallmacos] Checking that selected build 20G314 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --catalogurl https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog --build 20G314 --validate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   188  100   188    0     0   2160      0 --:--:-- --:--:-- --:--:--  2160
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 19 1611k   19  319k    0     0  1042k      0  0:00:01 --:--:--  0:00:01 1039k
100 1611k  100 1611k    0     0  3638k      0 --:--:-- --:--:-- --:--:-- 3629k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1952k  100 1952k    0     0  5179k      0 --:--:-- --:--:-- --:--:-- 5179k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5778  100  5778    0     0  24075      0 --:--:-- --:--:-- --:--:-- 24075
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2571k  100 2571k    0     0  3919k      0 --:--:-- --:--:-- --:--:-- 3913k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0  239k    0     0   631k      0  5:20:41 --:--:--  5:20:41  629k
  0 11.5G    0 16.5M    0     0  12.8M      0  0:15:24  0:00:01  0:15:23 12.8M
  0 11.5G    0 36.0M    0     0  15.6M      0  0:12:37  0:00:02  0:12:35 15.6M
  0 11.5G    0 49.7M    0     0  15.0M      0  0:13:05  0:00:03  0:13:02 15.0M
  0 11.5G    0 61.7M    0     0  14.3M      0  0:13:44  0:00:04  0:13:40 14.3M
  0 11.5G    0 74.3M    0     0  14.0M      0  0:14:04  0:00:05  0:13:59 15.0M
  0 11.5G    0 86.4M    0     0  13.7M      0  0:14:23  0:00:06  0:14:17 13.9M
  0 11.5G    0 97.3M    0     0  13.3M      0  0:14:48  0:00:07  0:14:41 12.2M
  0 11.5G    0  108M    0     0  13.0M      0  0:15:10  0:00:08  0:15:02 11.6M
  0 11.5G    0  117M    0     0  12.6M      0  0:15:37  0:00:09  0:15:28 11.1M
  1 11.5G    1  127M    0     0  12.3M      0  0:16:00  0:00:10  0:15:50 10.5M
  1 11.5G    1  137M    0     0  12.2M      0  0:16:10  0:00:11  0:15:59 10.3M
  1 11.5G    1  149M    0     0  12.1M      0  0:16:15  0:00:12  0:16:03 10.4M
  1 11.5G    1  158M    0     0  11.9M      0  0:16:35  0:00:13  0:16:22 10.0M
  1 11.5G    1  168M    0     0  11.8M      0  0:16:44  0:00:14  0:16:30 10.2M
  1 11.5G    1  179M    0     0  11.7M      0  0:16:49  0:00:15  0:16:34 10.5M
  1 11.5G    1  191M    0     0  11.7M      0  0:16:47  0:00:16  0:16:31 10.7M
  1 11.5G    1  202M    0     0  11.7M      0  0:16:51  0:00:17  0:16:34 10.6M
  1 11.5G    1  213M    0     0  11.6M      0  0:16:55  0:00:18  0:16:37 11.0M
  1 11.5G    1  225M    0     0  11.6M      0  0:16:55  0:00:19  0:16:36 11.3M
  2 11.5G    2  237M    0     0  11.6M      0  0:16:53  0:00:20  0:16:33 11.5M
  2 11.5G    2  249M    0     0  11.7M      0  0:16:53  0:00:21  0:16:32 11.4M
  2 11.5G    2  261M    0     0  11.7M      0  0:16:50  0:00:22  0:16:28 11.7M
  2 11.5G    2  273M    0     0  11.7M      0  0:16:49  0:00:23  0:16:26 12.0M
  2 11.5G    2  286M    0     0  11.7M      0  0:16:46  0:00:24  0:16:22 12.1M
  2 11.5G    2  298M    0     0  11.8M      0  0:16:43  0:00:25  0:16:18 12.3M
  2 11.5G    2  312M    0     0  11.8M      0  0:16:38  0:00:26  0:16:12 12.6M
  2 11.5G    2  325M    0     0  11.9M      0  0:16:33  0:00:27  0:16:06 12.8M
  2 11.5G    2  339M    0     0  11.9M      0  0:16:28  0:00:28  0:16:00 13.1M
  2 11.5G    2  352M    0     0  12.0M      0  0:16:25  0:00:29  0:15:56 13.2M
  3 11.5G    3  365M    0     0  12.0M      0  0:16:22  0:00:30  0:15:52 13.3M
  3 11.5G    3  377M    0     0  12.0M      0  0:16:22  0:00:31  0:15:51 13.1M
  3 11.5G    3  386M    0     0  11.9M      0  0:16:29  0:00:32  0:15:57 12.2M
  3 11.5G    3  391M    0     0  11.7M      0  0:16:52  0:00:33  0:16:19 10.1M
  3 11.5G    3  393M    0     0  11.4M      0  0:17:15  0:00:34  0:16:41 8293k
  3 11.5G    3  395M    0     0  11.1M      0  0:17:45  0:00:35  0:17:10 5836k
  3 11.5G    3  397M    0     0  10.9M      0  0:18:02  0:00:36  0:17:26 4010k
  3 11.5G    3  402M    0     0  10.8M      0  0:18:17  0:00:37  0:17:40 3257k
  3 11.5G    3  412M    0     0  10.7M      0  0:18:20  0:00:38  0:17:42 4484k
  3 11.5G    3  420M    0     0  10.7M      0  0:18:26  0:00:39  0:17:47 5709k
  3 11.5G    3  429M    0     0  10.6M      0  0:18:31  0:00:40  0:17:51 7399k
  3 11.5G    3  437M    0     0  10.5M      0  0:18:40  0:00:41  0:17:59 8091k
  3 11.5G    3  445M    0     0  10.5M      0  0:18:46  0:00:42  0:18:04 8693k
  3 11.5G    3  452M    0     0  10.4M      0  0:18:53  0:00:43  0:18:10 8267k
  3 11.5G    3  460M    0     0  10.3M      0  0:19:00  0:00:44  0:18:16 8145k
  3 11.5G    3  468M    0     0  10.3M      0  0:19:06  0:00:45  0:18:21 7869k
  4 11.5G    4  475M    0     0  10.2M      0  0:19:14  0:00:46  0:18:28 7858k
  4 11.5G    4  483M    0     0  10.2M      0  0:19:20  0:00:47  0:18:33 7790k
  4 11.5G    4  491M    0     0  10.1M      0  0:19:24  0:00:48  0:18:36 7950k
  4 11.5G    4  499M    0     0  10.1M      0  0:19:30  0:00:49  0:18:41 7929k
  4 11.5G    4  507M    0     0  10.1M      0  0:19:33  0:00:50  0:18:43 8136k
  4 11.5G    4  515M    0     0  10.0M      0  0:19:38  0:00:51  0:18:47 8300k
  4 11.5G    4  524M    0     0  10.0M      0  0:19:41  0:00:52  0:18:49 8517k
  4 11.5G    4  533M    0     0  10.0M      0  0:19:44  0:00:53  0:18:51 8542k
  4 11.5G    4  542M    0     0   9.9M      0  0:19:46  0:00:54  0:18:52 8845k
  4 11.5G    4  553M    0     0  10.0M      0  0:19:45  0:00:55  0:18:50 9233k
  4 11.5G    4  563M    0     0  10.0M      0  0:19:44  0:00:56  0:18:48 9716k
  4 11.5G    4  574M    0     0  10.0M      0  0:19:42  0:00:57  0:18:45  9.9M
  4 11.5G    4  583M    0     0  10.0M      0  0:19:43  0:00:58  0:18:45 10.0M
  5 11.5G    5  593M    0     0  10.0M      0  0:19:44  0:00:59  0:18:45 10.1M
  5 11.5G    5  602M    0     0   9.9M      0  0:19:47  0:01:00  0:18:47  9.8M
  5 11.5G    5  610M    0     0   9.9M      0  0:19:51  0:01:01  0:18:50 9599k
  5 11.5G    5  618M    0     0   9.9M      0  0:19:54  0:01:02  0:18:52 8927k
  5 11.5G    5  626M    0     0   9.9M      0  0:19:57  0:01:03  0:18:54 8774k
  5 11.5G    5  634M    0     0   9.8M      0  0:20:02  0:01:04  0:18:58 8289k
  5 11.5G    5  642M    0     0   9.8M      0  0:20:05  0:01:05  0:19:00 8222k
  5 11.5G    5  649M    0     0   9.7M      0  0:20:10  0:01:06  0:19:04 8072k
  5 11.5G    5  657M    0     0   9.7M      0  0:20:12  0:01:07  0:19:05 8138k
  5 11.5G    5  667M    0     0   9.7M      0  0:20:12  0:01:08  0:19:04 8398k
  5 11.5G    5  677M    0     0   9.7M      0  0:20:12  0:01:09  0:19:03 8982k
  5 11.5G    5  688M    0     0   9.7M      0  0:20:11  0:01:10  0:19:01 9392k
  5 11.5G    5  699M    0     0   9.8M      0  0:20:08  0:01:11  0:18:57 10.0M
  5 11.5G    5  710M    0     0   9.8M      0  0:20:07  0:01:12  0:18:55 10.4M
  6 11.5G    6  720M    0     0   9.8M      0  0:20:07  0:01:13  0:18:54 10.4M
  6 11.5G    6  730M    0     0   9.8M      0  0:20:05  0:01:14  0:18:51 10.6M
  6 11.5G    6  742M    0     0   9.8M      0  0:20:02  0:01:15  0:18:47 10.9M
  6 11.5G    6  754M    0     0   9.8M      0  0:19:58  0:01:16  0:18:42 10.9M
  6 11.5G    6  766M    0     0   9.9M      0  0:19:56  0:01:17  0:18:39 11.1M
  6 11.5G    6  773M    0     0   9.8M      0  0:19:59  0:01:18  0:18:41 10.8M
  6 11.5G    6  783M    0     0   9.8M      0  0:20:00  0:01:19  0:18:41 10.4M
  6 11.5G    6  793M    0     0   9.8M      0  0:19:59  0:01:20  0:18:39 10.1M
  6 11.5G    6  805M    0     0   9.9M      0  0:19:57  0:01:21  0:18:36 10.1M
  6 11.5G    6  816M    0     0   9.9M      0  0:19:55  0:01:22  0:18:33 10.0M
  6 11.5G    6  826M    0     0   9.9M      0  0:19:54  0:01:23  0:18:31 10.5M
  7 11.5G    7  838M    0     0   9.9M      0  0:19:51  0:01:24  0:18:27 11.0M
  7 11.5G    7  848M    0     0   9.9M      0  0:19:52  0:01:25  0:18:27 10.9M
  7 11.5G    7  859M    0     0   9.9M      0  0:19:49  0:01:26  0:18:23 10.9M
  7 11.5G    7  870M    0     0   9.9M      0  0:19:49  0:01:27  0:18:22 10.7M
  7 11.5G    7  880M    0     0   9.9M      0  0:19:48  0:01:28  0:18:20 10.8M
  7 11.5G    7  891M    0     0   9.9M      0  0:19:47  0:01:29  0:18:18 10.6M
  7 11.5G    7  902M    0     0   9.9M      0  0:19:46  0:01:30  0:18:16 10.8M
  7 11.5G    7  913M    0     0  10.0M      0  0:19:44  0:01:31  0:18:13 10.7M
  7 11.5G    7  923M    0     0  10.0M      0  0:19:45  0:01:32  0:18:13 10.6M
  7 11.5G    7  929M    0     0   9.9M      0  0:19:49  0:01:33  0:18:16 9975k
  7 11.5G    7  931M    0     0   9.8M      0  0:20:00  0:01:34  0:18:26 8123k
  7 11.5G    7  933M    0     0   9.7M      0  0:20:11  0:01:35  0:18:36 6228k
  7 11.5G    7  935M    0     0  9948k      0  0:20:20  0:01:36  0:18:44 4444k
  7 11.5G    7  938M    0     0  9875k      0  0:20:29  0:01:37  0:18:52 3049k
  7 11.5G    7  946M    0     0  9860k      0  0:20:31  0:01:38  0:18:53 3447k
  8 11.5G    8  955M    0     0  9855k      0  0:20:31  0:01:39  0:18:52 4970k
  8 11.5G    8  964M    0     0  9842k      0  0:20:33  0:01:40  0:18:53 6363k
  8 11.5G    8  973M    0     0  9838k      0  0:20:34  0:01:41  0:18:53 7717k
  8 11.5G    8  981M    0     0  9823k      0  0:20:36  0:01:42  0:18:54 8795k
  8 11.5G    8  989M    0     0  9813k      0  0:20:37  0:01:43  0:18:54 8896k
  8 11.5G    8 1000M    0     0  9818k      0  0:20:36  0:01:44  0:18:52 9079k
  8 11.5G    8 1008M    0     0  9808k      0  0:20:37  0:01:45  0:18:52 9115k
  8 11.5G    8 1017M    0     0  9801k      0  0:20:38  0:01:46  0:18:52 9036k
  8 11.5G    8 1027M    0     0  9806k      0  0:20:38  0:01:47  0:18:51 9460k
  8 11.5G    8 1037M    0     0  9812k      0  0:20:37  0:01:48  0:18:49 9793k
  8 11.5G    8 1048M    0     0  9823k      0  0:20:36  0:01:49  0:18:47 9926k
  8 11.5G    8 1059M    0     0  9837k      0  0:20:34  0:01:50  0:18:44 10.2M
  9 11.5G    9 1071M    0     0  9853k      0  0:20:32  0:01:51  0:18:41 10.7M
  9 11.5G    9 1083M    0     0  9876k      0  0:20:29  0:01:52  0:18:37 11.1M
  9 11.5G    9 1095M    0     0  9899k      0  0:20:26  0:01:53  0:18:33 11.5M
  9 11.5G    9 1106M    0     0  9911k      0  0:20:25  0:01:54  0:18:31 11.5M
  9 11.5G    9 1117M    0     0  9924k      0  0:20:23  0:01:55  0:18:28 11.5M
  9 11.5G    9 1125M    0     0  9911k      0  0:20:25  0:01:56  0:18:29 10.9M
  9 11.5G    9 1133M    0     0  9899k      0  0:20:26  0:01:57  0:18:29 10.1M
  9 11.5G    9 1142M    0     0  9894k      0  0:20:27  0:01:58  0:18:29 9761k
  9 11.5G    9 1152M    0     0  9888k      0  0:20:27  0:01:59  0:18:28 9365k
  9 11.5G    9 1161M    0     0  9883k      0  0:20:28  0:02:00  0:18:28 8947k
  9 11.5G    9 1169M    0     0  9869k      0  0:20:30  0:02:01  0:18:29 8898k
  9 11.5G    9 1178M    0     0  9870k      0  0:20:30  0:02:02  0:18:28 9183k
 10 11.5G   10 1188M    0     0  9870k      0  0:20:30  0:02:03  0:18:27 9311k
 10 11.5G   10 1199M    0     0  9877k      0  0:20:29  0:02:04  0:18:25 9626k
 10 11.5G   10 1209M    0     0  9885k      0  0:20:28  0:02:05  0:18:23 9922k
 10 11.5G   10 1220M    0     0  9894k      0  0:20:27  0:02:06  0:18:21 10.2M
 10 11.5G   10 1230M    0     0  9899k      0  0:20:26  0:02:07  0:18:19 10.3M
 10 11.5G   10 1241M    0     0  9905k      0  0:20:25  0:02:08  0:18:17 10.5M
 10 11.5G   10 1253M    0     0  9924k      0  0:20:23  0:02:09  0:18:14 10.8M
 10 11.5G   10 1264M    0     0  9940k      0  0:20:21  0:02:10  0:18:11 11.0M
 10 11.5G   10 1273M    0     0  9933k      0  0:20:22  0:02:11  0:18:11 10.6M
 10 11.5G   10 1281M    0     0  9915k      0  0:20:24  0:02:12  0:18:12 10.0M
 10 11.5G   10 1290M    0     0  9911k      0  0:20:25  0:02:13  0:18:12  9.8M
 10 11.5G   10 1301M    0     0  9922k      0  0:20:23  0:02:14  0:18:09 9882k
 11 11.5G   11 1312M    0     0  9931k      0  0:20:22  0:02:15  0:18:07 9693k
 11 11.5G   11 1323M    0     0  9941k      0  0:20:21  0:02:16  0:18:05  9.9M
 11 11.5G   11 1334M    0     0  9952k      0  0:20:19  0:02:17  0:18:02 10.6M
 11 11.5G   11 1343M    0     0  9949k      0  0:20:20  0:02:18  0:18:02 10.6M
 11 11.5G   11 1354M    0     0  9956k      0  0:20:19  0:02:19  0:18:00 10.6M
 11 11.5G   11 1364M    0     0  9957k      0  0:20:19  0:02:20  0:17:59 10.4M
 11 11.5G   11 1372M    0     0  9950k      0  0:20:20  0:02:21  0:17:59  9.9M
 11 11.5G   11 1382M    0     0  9949k      0  0:20:20  0:02:22  0:17:58 9870k
 11 11.5G   11 1392M    0     0  9950k      0  0:20:20  0:02:23  0:17:57 9976k
 11 11.5G   11 1403M    0     0  9960k      0  0:20:19  0:02:24  0:17:55  9.8M
 11 11.5G   11 1414M    0     0  9970k      0  0:20:17  0:02:25  0:17:52 10.0M
 12 11.5G   12 1424M    0     0  9973k      0  0:20:17  0:02:26  0:17:51 10.3M
 12 11.5G   12 1435M    0     0  9978k      0  0:20:16  0:02:27  0:17:49 10.5M
 12 11.5G   12 1445M    0     0  9979k      0  0:20:16  0:02:28  0:17:48 10.5M
 12 11.5G   12 1453M    0     0  9971k      0  0:20:17  0:02:29  0:17:48 10.0M
 12 11.5G   12 1462M    0     0  9962k      0  0:20:18  0:02:30  0:17:48 9735k
 12 11.5G   12 1470M    0     0  9955k      0  0:20:19  0:02:31  0:17:48 9446k
 12 11.5G   12 1481M    0     0  9958k      0  0:20:19  0:02:32  0:17:47 9351k
 12 11.5G   12 1491M    0     0  9962k      0  0:20:18  0:02:33  0:17:45 9456k
 12 11.5G   12 1494M    0     0  9915k      0  0:20:24  0:02:34  0:17:50 8247k
 12 11.5G   12 1496M    0     0  9864k      0  0:20:30  0:02:35  0:17:55 6962k
 12 11.5G   12 1499M    0     0  9818k      0  0:20:36  0:02:36  0:18:00 5744k
 12 11.5G   12 1501M    0     0  9775k      0  0:20:42  0:02:37  0:18:05 4213k
 12 11.5G   12 1509M    0     0  9764k      0  0:20:43  0:02:38  0:18:05 3716k
 12 11.5G   12 1518M    0     0  9763k      0  0:20:43  0:02:39  0:18:04 5072k
 12 11.5G   12 1528M    0     0  9766k      0  0:20:43  0:02:40  0:18:03 6682k
 12 11.5G   12 1538M    0     0  9768k      0  0:20:42  0:02:41  0:18:01 8174k
 13 11.5G   13 1548M    0     0  9769k      0  0:20:42  0:02:42  0:18:00 9596k
 13 11.5G   13 1557M    0     0  9767k      0  0:20:43  0:02:43  0:18:00 9843k
 13 11.5G   13 1566M    0     0  9766k      0  0:20:43  0:02:44  0:17:59 9848k
 13 11.5G   13 1574M    0     0  9752k      0  0:20:44  0:02:45  0:17:59 9297k
 13 11.5G   13 1584M    0     0  9754k      0  0:20:44  0:02:46  0:17:58 9311k
 13 11.5G   13 1593M    0     0  9754k      0  0:20:44  0:02:47  0:17:57 9267k
 13 11.5G   13 1605M    0     0  9765k      0  0:20:43  0:02:48  0:17:55 9719k
 13 11.5G   13 1614M    0     0  9763k      0  0:20:43  0:02:49  0:17:54 9663k
 13 11.5G   13 1623M    0     0  9760k      0  0:20:43  0:02:50  0:17:53  9.7M
 13 11.5G   13 1631M    0     0  9753k      0  0:20:44  0:02:51  0:17:53 9698k
 13 11.5G   13 1641M    0     0  9754k      0  0:20:44  0:02:52  0:17:52 9745k
 13 11.5G   13 1651M    0     0  9758k      0  0:20:44  0:02:53  0:17:51 9516k
 14 11.5G   14 1662M    0     0  9765k      0  0:20:43  0:02:54  0:17:49 9824k
 14 11.5G   14 1672M    0     0  9767k      0  0:20:43  0:02:55  0:17:48 9998k
 14 11.5G   14 1682M    0     0  9773k      0  0:20:42  0:02:56  0:17:46 10.2M
 14 11.5G   14 1694M    0     0  9784k      0  0:20:40  0:02:57  0:17:43 10.5M
 14 11.5G   14 1705M    0     0  9797k      0  0:20:39  0:02:58  0:17:41 10.9M
 14 11.5G   14 1718M    0     0  9812k      0  0:20:37  0:02:59  0:17:38 11.2M
 14 11.5G   14 1729M    0     0  9825k      0  0:20:35  0:03:00  0:17:35 11.5M
 14 11.5G   14 1740M    0     0  9831k      0  0:20:35  0:03:01  0:17:34 11.5M
 14 11.5G   14 1753M    0     0  9848k      0  0:20:32  0:03:02  0:17:30 11.8M
 14 11.5G   14 1766M    0     0  9869k      0  0:20:30  0:03:03  0:17:27 12.1M
 14 11.5G   14 1778M    0     0  9879k      0  0:20:29  0:03:04  0:17:25 11.9M
 15 11.5G   15 1789M    0     0  9889k      0  0:20:27  0:03:05  0:17:22 11.9M
 15 11.5G   15 1802M    0     0  9907k      0  0:20:25  0:03:06  0:17:19 12.3M
 15 11.5G   15 1814M    0     0  9919k      0  0:20:24  0:03:07  0:17:17 12.2M
 15 11.5G   15 1827M    0     0  9937k      0  0:20:21  0:03:08  0:17:13 12.1M
 15 11.5G   15 1839M    0     0  9950k      0  0:20:20  0:03:09  0:17:11 12.2M
 15 11.5G   15 1851M    0     0  9960k      0  0:20:18  0:03:10  0:17:08 12.3M
 15 11.5G   15 1862M    0     0  9969k      0  0:20:17  0:03:11  0:17:06 11.9M
 15 11.5G   15 1876M    0     0  9989k      0  0:20:15  0:03:12  0:17:03 12.2M
 15 11.5G   15 1885M    0     0  9990k      0  0:20:15  0:03:13  0:17:02 11.7M
 15 11.5G   15 1895M    0     0  9992k      0  0:20:15  0:03:14  0:17:01 11.3M
 16 11.5G   16 1906M    0     0  9996k      0  0:20:14  0:03:15  0:16:59 11.0M
 16 11.5G   16 1917M    0     0   9.7M      0  0:20:13  0:03:16  0:16:57 11.1M
 16 11.5G   16 1927M    0     0   9.7M      0  0:20:13  0:03:17  0:16:56 10.3M
 16 11.5G   16 1939M    0     0   9.7M      0  0:20:12  0:03:18  0:16:54 10.6M
 16 11.5G   16 1950M    0     0   9.7M      0  0:20:11  0:03:19  0:16:52 10.8M
 16 11.5G   16 1960M    0     0   9.7M      0  0:20:11  0:03:20  0:16:51 10.7M
 16 11.5G   16 1970M    0     0   9.7M      0  0:20:11  0:03:21  0:16:50 10.4M
 16 11.5G   16 1979M    0     0   9.7M      0  0:20:11  0:03:22  0:16:49 10.3M
 16 11.5G   16 1988M    0     0   9.7M      0  0:20:12  0:03:23  0:16:49  9.7M
 16 11.5G   16 1997M    0     0   9.7M      0  0:20:12  0:03:24  0:16:48 9730k
 16 11.5G   16 2006M    0     0   9.7M      0  0:20:13  0:03:25  0:16:48 9508k
 16 11.5G   16 2014M    0     0   9.7M      0  0:20:14  0:03:26  0:16:48 9136k
 17 11.5G   17 2024M    0     0   9.7M      0  0:20:13  0:03:27  0:16:46 9363k
 17 11.5G   17 2034M    0     0   9.7M      0  0:20:13  0:03:28  0:16:45 9514k
 17 11.5G   17 2044M    0     0   9.7M      0  0:20:13  0:03:29  0:16:44 9643k
 17 11.5G   17 2055M    0     0   9.7M      0  0:20:12  0:03:30  0:16:42  9.8M
 17 11.5G   17 2065M    0     0   9.7M      0  0:20:12  0:03:31  0:16:41 10.1M
 17 11.5G   17 2077M    0     0   9.7M      0  0:20:11  0:03:32  0:16:39 10.4M
 17 11.5G   17 2085M    0     0   9.7M      0  0:20:12  0:03:33  0:16:39 10.1M
 17 11.5G   17 2091M    0     0  9992k      0  0:20:15  0:03:34  0:16:41 9516k
 17 11.5G   17 2094M    0     0  9956k      0  0:20:19  0:03:35  0:16:44 7740k
 17 11.5G   17 2097M    0     0  9929k      0  0:20:22  0:03:36  0:16:46 6499k
 17 11.5G   17 2100M    0     0  9895k      0  0:20:27  0:03:37  0:16:50 4667k
 17 11.5G   17 2106M    0     0  9880k      0  0:20:28  0:03:38  0:16:50 4278k
 17 11.5G   17 2117M    0     0  9887k      0  0:20:27  0:03:39  0:16:48 5394k
 17 11.5G   17 2128M    0     0  9894k      0  0:20:27  0:03:40  0:16:47 7118k
 18 11.5G   18 2137M    0     0  9892k      0  0:20:27  0:03:41  0:16:46 8288k
 18 11.5G   18 2148M    0     0  9895k      0  0:20:27  0:03:42  0:16:45 9911k
 18 11.5G   18 2159M    0     0  9900k      0  0:20:26  0:03:43  0:16:43 10.5M
 18 11.5G   18 2166M    0     0  9892k      0  0:20:27  0:03:44  0:16:43  9.8M
 18 11.5G   18 2175M    0     0  9888k      0  0:20:27  0:03:45  0:16:42 9642k
 18 11.5G   18 2182M    0     0  9877k      0  0:20:29  0:03:46  0:16:43 9200k
 18 11.5G   18 2191M    0     0  9872k      0  0:20:29  0:03:47  0:16:42 8839k
 18 11.5G   18 2200M    0     0  9868k      0  0:20:30  0:03:48  0:16:42 8445k
 18 11.5G   18 2210M    0     0  9870k      0  0:20:30  0:03:49  0:16:41 8879k
 18 11.5G   18 2218M    0     0  9866k      0  0:20:30  0:03:50  0:16:40 8857k
 18 11.5G   18 2226M    0     0  9857k      0  0:20:31  0:03:51  0:16:40 8980k
 18 11.5G   18 2236M    0     0  9859k      0  0:20:31  0:03:52  0:16:39 9248k
 18 11.5G   18 2245M    0     0  9854k      0  0:20:32  0:03:53  0:16:39 9205k
 19 11.5G   19 2254M    0     0  9851k      0  0:20:32  0:03:54  0:16:38 8993k
 19 11.5G   19 2264M    0     0  9853k      0  0:20:32  0:03:55  0:16:37 9249k
 19 11.5G   19 2273M    0     0  9853k      0  0:20:32  0:03:56  0:16:36 9668k
 19 11.5G   19 2282M    0     0  9848k      0  0:20:32  0:03:57  0:16:35 9367k
 19 11.5G   19 2289M    0     0  9838k      0  0:20:34  0:03:58  0:16:36 9076k
 19 11.5G   19 2297M    0     0  9831k      0  0:20:34  0:03:59  0:16:35 8903k
 19 11.5G   19 2299M    0     0  9831k      0  0:20:35  0:03:59  0:16:36 8624k
curl: (18) transfer closed with 10021905812 bytes remaining to read
Could not replicate https://swcdn.apple.com/content/downloads/04/42/002-42341-A_4PL6G0S8GN/cs65avpi1aelh133lc36fy0ste3lihe71n/InstallAssistant.pkg: Command '['/usr/bin/curl', '-fL', '--create-dirs', '-o', '/Library/Management/erase-install/content/downloads/04/42/002-42341-A_4PL6G0S8GN/cs65avpi1aelh133lc36fy0ste3lihe71n/InstallAssistant.pkg', '-w', '%{http_code}', '--compressed', 'https://swcdn.apple.com/content/downloads/04/42/002-42341-A_4PL6G0S8GN/cs65avpi1aelh133lc36fy0ste3lihe71n/InstallAssistant.pkg']' returned non-zero exit status 18.

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro16,1

Bridge ID        : J152fAP
Board ID         : Mac-E1008331FDC96864
OS Version       : 11.6.2
Build ID         : 20G314

 #  ProductID       Version    Build    Post Date   Title                          
 1  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
 2  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 3  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 4  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
 5  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
 6  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 7  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 8  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 9  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
10  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
11  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
12  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
13  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
14  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
15  071-97382       11.6       20G165   2021-09-17  macOS Big Sur                  
16  002-23774       12.0.1     21A559   2021-12-01  macOS Monterey                 
17  002-23589       11.6.1     20G224   2021-12-01  macOS Big Sur                  
18  002-42435       12.1       21C52    2021-12-13  macOS Monterey                 
19  002-42341       11.6.2     20G314   2021-12-13  macOS Big Sur                  

Build 20G314 available. Downloading #19...

   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.

   [erase-install] 'caffeinate' ended
/Library/Management/erase-install/erase-install.sh: line 954: 16119 Terminated: 15          /usr/bin/caffeinate -dimsu -w $pid
/Library/Management/erase-install/erase-install.sh: line 733: 16144 Killed: 9               dep_notify_progress installinstallmacos > /dev/null 2>&1

Screenshots
None

Environment (please complete the following information):
BS 11.6.2 (running on machine)
v0.25.1

**Comment by grahampugh** [comment]
I'm afraid you have a network issue. The curl download failed at 19%. Not much I can help with there.

**Comment by TheRossRoss** [comment]
Super odd!  Also thanks for catching that and teaching me how to read the logs better.  Going to try on another network here at the house to see if that improves things.  Then traceback on the original network to see where the issue lies with that.  WIll update in Slack what the issue might be if you'd like?
