### ISSUE TITLE
Language selector - option/flag to select only 1 language 

### ISSUE THREAD

**Issue by Benek107** [grahampugh/erase-install#192]
**Is your feature request related to a problem? Please describe.**
I would like to have an option to run this script only using 1 Language. Whole company is using only English, so even if somebody has German OS they still should see English version of this process. This would help making Company specific modifications to some Dialogue localization.

**Describe the solution you'd like**
It would be nice to have flag --language=EN

**Describe alternatives you've considered**
I would remove IF or change all user_language= to EN

if [[ $language = de* ]]; then
    user_language="de"
elif [[ $language = nl* ]]; then
    user_language="nl"
elif [[ $language = fr* ]]; then
    user_language="fr"
else
    user_language="en"
fi

**Additional context**

**Comment by grahampugh** [comment]
If you are already modifying the text to be more company-specific, why not also modify the bit of code that determines which language to use?

**Comment by Benek107** [comment]
I can do such modification. That is why I put this as enhancement so maybe in future releases you might consider adding such flag/option. This is more for users that they can change localization text but afraid of messing with scrip.

**Comment by grahampugh** [comment]
There is no functionality for changing the text without editing the script (and it would be far too many parameters to achieve that). So this feature request would not achieve your goal of not having to edit the script.

**Comment by grahampugh** [comment]
I'm going to close this case, because I think there are already a lot of flags which is getting confusing to users, and I don't really see the use case for a language override. If you don't want your users to see the outputs in the language their OS is set to, perhaps you should be overriding their OS setting.
