### ISSUE TITLE
Problem running script as preinstall-command

### ISSUE THREAD

**Issue by kryptonit1** [grahampugh/erase-install#202]
**Describe the bug**
I'm trying to run a script as a --preinstall-command, but that does not seem to work very well. When I enter `--preinstall-command "/Applications/Test Application 2.app/Contents/Helpers/Remover.app/Contents/Scripts/uninstall.sh"` it seems to cut everything in the command after the first space in the path.

I've also tried:
`--preinstall-command "/Applications/Test\ Application\ 2.app/Contents/Helpers/Remover.app/Contents/Scripts/uninstall.sh"`

But it doesn't help either. The command gets cut off after `Test\`

**To Reproduce**
Executed from Jamf Policy with uploaded pkg using the following command:
/Library/Management/erase-install/erase-install.sh --os=11 --erase --confirm --depnotify --check-power --power-wait-limit 180 --preinstall-command "/Applications/Test Application 2.app/Contents/Helpers/Remover.app/Contents/Scripts/uninstall.sh"
 
**Expected behavior**
I expected the uninstall.sh script to be executed before startosinstall.

**Environment (please complete the following information):**
 - macOS 11.6.4
 - erase-install version 25

**Comment by kryptonit1** [comment]
Output from erase-install.log:

[erase-install] Now running arbitrary command: /Applications/Test Application 2.app/Contents/Helpers/Remover.app/Contents/Scripts/uninstall.sh
/Library/Management/erase-install/erase-install.sh: line 1938: /Applications/Test: No such file or directory

**Comment by kryptonit1** [comment]
Quotes around `$preinstall_command` on line 1938 of erase-install.sh seems to do the trick.

**Comment by ryangball** [comment]
You should add a slash after Test like: Test\ Application

**Comment by grahampugh** [comment]
I believe I have now fixed this. 

FYI, quotes around the command did not work. I had to use `bash -c $command` to cope with quotes. Let me know if it works for you or not. There could easily be edge cases here due to escaping quotes etc. My tests used the following successfully:

```
--preinstall-command "ls /Applications/Some\ App.app/Contents/Resources"
--preinstall-command "ls '/Applications/Some App.app/Contents/Resources'"
--preinstall-command 'ls "/Applications/Some App.app/Contents/Resources"'
--preinstall-command "ls \"/Applications/Some App.app/Contents/Resources\""
```

**Comment by kryptonit1** [comment]
> I believe I have now fixed this.
> 
> FYI, quotes around the command did not work. I had to use `bash -c $command` to cope with quotes. Let me know if it works for you or not. There could easily be edge cases here due to escaping quotes etc. My tests used the following successfully:
> 
> ```
> --preinstall-command "ls /Applications/Some\ App.app/Contents/Resources"
> --preinstall-command "ls '/Applications/Some App.app/Contents/Resources'"
> --preinstall-command 'ls "/Applications/Some App.app/Contents/Resources"'
> --preinstall-command "ls \"/Applications/Some App.app/Contents/Resources\""
> ```

Yes, seems to be working now when using `--preinstall-command "ls /Applications/Some\ App.app/Contents/Resources"` and erase-install-depnotify-26.0.pkg. Thanks a lot!
