### ISSUE TITLE
Upgrade will use an existing macOS installer, even if the major version is specified in command line

### ISSUE THREAD

**Issue by Tribruin** [grahampugh/erase-install#205]
**Describe the bug**
If a major version is specified in the command line using the (e.g. --os=12), but the script finds an installer already in the Application folder (Install macOS Big Sur.app), the script will default to the found installer instead of trying to pull the correct version from Apple. 

**To Reproduce**
Install a version of macOS that is different from both an installer on the computer and available from Apple. (e.g. 10.15.7). Download a version of the Big Sur installer and place in the application folder. Call erase-install from the command line using the --os=12 argument, but do not use the --overwrite option.

Erase-Install will skip the download of Monterey a proceed with the Big Sur install instead.  
 
**Expected behavior**
The script should verify the major version of the found installer matches the version specified in the command line. 

**Code/log output**
--os=12 --current-user --check-power --depnotify --reinstall --cleanup-after-use

**Environment (please complete the following information):**
 - OS version: 10.15.7
 - erase-install version [e.g. 24.0] -25.0

**Additional context**
I have added the --overwrite argument to the command line. But wanted to bring awareness to the issue.

**Comment by grahampugh** [comment]
This behaviour is expected and described in the wiki. 

I would accept a feature request if you would like this behaviour to change.

**Comment by Tribruin** [comment]
Thanks. I think that would be a good check. I didn't notice this in the Wiki. I have gone ahead and added --overwrite to my arguments.

**Comment by BlueCornPie** [comment]
I encountered an issue with this today. I had a Mac running Big Sur 11.6.5. I had two different installers in the Applications folder (one for Big Sur 11.6.5 from making a USB installer for some other Macs and another for Monterey 12.3 which I expected to be used for the upgrade as that's what I had indicated in the Execute Command field in Jamf (--version 12.3)). Big Sur got reinstalled instead. 

It's sort of on the cusp of a bug and an enhancement, but it would be nice if the selected version would be used in this case.

**Comment by grahampugh** [comment]
Funnily enough this came up with somebody else yesterday. But I would say that it's not a common scenario on an end user's Mac. It generally only comes up on machines admins are testing on, where they have been playing around with multiple installers for different reasons, as in your case.

Handling multiple installers lying around across the different possible locations is not trivial. On a managed Mac, you should be able to tell from your inventory if there are multiple installers on the device.

Note that erase-install.sh only looks in two places for installers: `/Applications` or an overridden installer location, and the set working directory (default `/Library/Management/erase-install`). You can easily store others elsewhere on the system for other purposes.

**Comment by grahampugh** [comment]
However, I am working on restricting the "validity" of an installer to the one specified in `--version`, `--os`, `--build` or `--sameos`.

**Comment by grahampugh** [comment]
This is addressed in 26.1.
