### ISSUE TITLE
Option to remove Cancel button from Password prompt on Apple Silicon

### ISSUE THREAD

**Issue by Tribruin** [grahampugh/erase-install#208]
**Is your feature request related to a problem? Please describe.**
We are pushing out Monterey to our users, first as an option in Self Service. Then as a forced install. The user is given 24 hours before they upgrade will run. For most users this works fine. However, I found that some M1 users found they can click Cancel at the password prompt, which will cancel the upgrade.  

**Describe the solution you'd like**
The optional ability to remove the Cancel button from the password prompt on M1 computers. The user should be required to enter the password. Also, do not fail out after 5 bad passwords. 

**Describe alternatives you've considered**
I will look at re-enabling my Launch Agent if the erase-install upgrade fails. But the user will still have the option to cancel. 

**Additional context**

**Comment by grahampugh** [comment]
I believe this is addressed in 26.1.
