### ISSUE TITLE
Check installer is valid errors (Info.plist could not be found!)

### ISSUE THREAD

**Issue by GabeShack** [grahampugh/erase-install#214]
**Describe the bug**
Erase Install fails with error

**To Reproduce**
we are using Jamf to trigger a policy that installs the the erase-install-26.pkg then runs the following "/Library/Management/erase-install/erase-install.sh --erase --version=12.2.1 --current-user --check-power --update"

 
**Expected behavior**
On most devices, we see the script run properly, download 12.2.1 and erase and install the system.

**Code/log output**
On a few devices we are seeing the following run log errors:
Verifying package integrity...
	Installing erase-install-26.0.pkg...
	Successfully installed erase-install-26.0.pkg.
	Running command /Library/Management/erase-install/erase-install.sh --erase --version=12.2.1 --current-user --check-power --update...
	Result of command:
	[erase-install] v26.0 script execution started: Wed Mar  2 11:32:48 EST 2022
	   [erase-install] Caffeinating this script (pid=1475)
	   [check_free_space] OK - 50 GB free/purgeable disk space detected
	   [check_power_status] OK - AC power detected
	   [erase-install] Looking for existing installer app or pkg
	   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_12.2.1-21D62.sparseimage.
	/dev/disk2          	GUID_partition_scheme          	
	/dev/disk2s1        	EFI                            	
	/dev/disk2s2        	Apple_HFS                      	/Volumes/Install_macOS_12.2.1-21D62
	   [check_installer_is_valid] Checking validity of .
	   [check_installer_is_valid] Using DTSDKBuild value from Info.plist
	   [check_installer_is_valid] Installer Info.plist could not be found!
	   [check_installer_is_valid] Build of existing installer could not be found!
	
	   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
	/Library/Management/erase-install/erase-install.sh: line 1042:  1490 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$
	Unmounting file server...

**Environment (please complete the following information):**
 - OS version 10.15.7
 - erase-install version 26 

**Additional context**
We also tried pre-downloading the 12.2.1 installer from the Mr. Macintosh links before running the script but still got the above message.

**Comment by GabeShack** [comment]
In looking this over perhaps it is an incomplete installer file in /Libarary/Management/erase-install/Install_macOS_12.2.1-21D62.sparseimage

I can try this again and remove the --update to see if that changes this behavior?

**Comment by grahampugh** [comment]
I would suspect a download problem causing a corrupt installer. But since you say you tried with an existing installer, there must be something on your system preventing either mounting the sparseimage or reading the file properly - an AV product perhaps?

Try adding the --move option which will move the app to /Applications so that it isn't mounted during the validation phase.

**Comment by GabeShack** [comment]
adding the --overwrite seems to have resolved this issue.  If it comes up again I will try the --move option.
Thanks!
