### ISSUE TITLE
Big Sur not downloading with --version or --os

### ISSUE THREAD

**Issue by chemxboy** [grahampugh/erase-install#215]
When using erase-install.sh --update --version 11.6.4 or --os 11:

```
Version 11.6.4 is not available. Run again without --version argument to select a valid build to download.

   [run_installinstallmacos] No disk image found. I guess nothing got downloaded.

```

When using  python /Library/Management/erase-install/installinstallmacos.py and manually choosing then entry for 11.6.4, it downloads successfully.

17  002-65695       11.6.4     20G417   2022-02-17  macOS Big Sur

**Comment by grahampugh** [comment]
Is 11.6.4 valid for that device? Try erase-install.sh --list - it will show you which installers are compatible.

**Comment by chemxboy** [comment]
--list shows Unsupported macOS version.  Looks like I misunderstood the erase and install capabilities. I was trying to install 11.6.4 on a Mac that had already upgraded to 12.

**Comment by grahampugh** [comment]
That's not possible by any method other than internet recovery (Intel) or DFU (Apple Silicon).
