### ISSUE TITLE
Seeing an issue with 12.3 installer

### ISSUE THREAD

**Issue by GabeShack** [grahampugh/erase-install#220]
**Describe the bug**
Erase Install failing when using the 12.3 version

**To Reproduce**
Run command:  /Library/Management/erase-install/erase-install.sh --erase --version=12.3 --current-user --check-power --overwrite  (ive also tried replacing the overwrite command with --move)
 
**Expected behavior**
This previously worked using the 12.2.1 in the version field

**Code/log output**
[erase-install] v26.0 script execution started: Wed Mar 16 11:05:34 EDT 2022
	   [erase-install] Caffeinating this script (pid=91404)
	   [check_free_space] OK - 141 GB free/purgeable disk space detected
	   [check_power_status] OK - AC power detected
	   [erase-install] Looking for existing installer app or pkg
	   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_12.3-21E230.sparseimage.
	/dev/disk2          	GUID_partition_scheme          	
	/dev/disk2s1        	EFI                            	
	/dev/disk2s2        	Apple_HFS                      	/Volumes/Install_macOS_12.3-21E230
	   [check_installer_is_valid] Checking validity of .
	   [check_installer_is_valid] Using DTSDKBuild value from Info.plist
	   [check_installer_is_valid] Installer Info.plist could not be found!
	   [check_installer_is_valid] Build of existing installer could not be found!
	
	   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
	/Library/Management/erase-install/erase-install.sh: line 1042: 91419 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$

**Screenshots**

**Environment (please complete the following information):**
 This is happening on 11.6 and 12.2.1 machines so far that I've tested
 - erase-install version [26.0] 

**Additional context**
We are using this on M1 MacBook Air 2020s and 2015 Macbook Air models and 2020 MacBook Air intel models

**Comment by grahampugh** [comment]
--overwrite will overwrite any installer.

**Comment by GabeShack** [comment]
Well I ran that same command over and over and overwrite didn’t work as expected. Once I removed the bad sparse image form the erase-install folder, it then worked as expected.
