### ISSUE TITLE
Support package signature

### ISSUE THREAD

**Issue by kenchan0130** [grahampugh/erase-install#221]
**Is your feature request related to a problem? Please describe.**
Using the package installer causes the installer to be blocked by Gatekeeer.

**Describe the solution you'd like**
I would like to see the package signed.

**Describe alternatives you've considered**
For GUI, hold down the ctrl key and tab-click on the installer.

**Additional context**
Being signed makes it more secure.

It is also possible to use https://github.com/Installomator/Installomator to integrate smoothly.

**Comment by grahampugh** [comment]
If you download with curl, this won't happen. 

Feel free to sign it yourself. I won't be providing this as it would tie the project to my employee.

**Comment by kenchan0130** [comment]
We can certainly sign it ourself. However, it does not prove that the package uploaded here is legitimate.
We are able to open it with curl with no problem as it does not give the extended attribute. However, it does not satisfy the desire to verify that the package is correct.

**Comment by grahampugh** [comment]
Sorry but I am not going to sign the packages for the reason I have already given. You can inspect the code and build a package yourself using the Makefile if you wish. 

This is an open source project that has gone far beyond my org's own use case. It is simply not possible for me to satisfy everyone else's requirements or wishes. You are of course able to fork and amend the project however you see fit.
