### ISSUE TITLE
JAMF Policy - Completed

### ISSUE THREAD

**Issue by MlooneyHV** [grahampugh/erase-install#223]
**Describe the bug**
When pushing this out with JAMF via a recurring check-in, the policy never actually shows as completed. It stays marked as "Pending". This then makes the policy try to install macOS Monterey again once the machine check's in. I believe this also happens if the policy is ran manually through self service.

**Expected behavior**
I expected the policy to register in JAMF as completed

**Environment (please complete the following information):**
 - OS version Big Sur to Monterey
 - erase-install version 26.0

**Comment by grahampugh** [comment]
Correct. See the FAQ. https://github.com/grahampugh/erase-install/wiki/FAQs#in-jamf-pro-the-policy-logs-show-as-pending-after-the-upgrade-has-finished---why

Don't set the policy to run via recurring check-in. Find a more appropriate check-in.
