### ISSUE TITLE
Error with installing Monterey 12.2.1 from 12.1

### ISSUE THREAD

**Issue by mrally7** [grahampugh/erase-install#224]
**Describe the bug**
There are multiple machines that we need to upgrade from 12.1 to 12.2.1.  Package runs but then during preparing stage fails with "Unable to verify MacOS".  The script identifies the correct installer however, it errors when attempting to obtain the OS.  This is preventing machines from upgrading to 12.2.1.  The users on not on using VPN clients at the time of the install.

Below is the Error from jamf logs:

**Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 452, in replicate_url
    _ = subprocess.check_output(curl_cmd)
  File "/Library/Management/erase-install/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Management/erase-install/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/curl', '-fL', '--create-dirs', '-o', '/Library/Management/erase-install/content/downloads/11/62/002-66265-A_HKQGKQG1Z4/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93/InstallAssistant.pkg', '-w', '%{http_code}', '--compressed', 'https://swcdn.apple.com/content/downloads/11/62/002-66265-A_HKQGKQG1Z4/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93/InstallAssistant.pkg']' returned non-zero exit status 56.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 1368, in <module>
    main()
  File "/Library/Management/erase-install/installinstallmacos.py", line 1295, in main
    download_pkg = replicate_url(
  File "/Library/Management/erase-install/installinstallmacos.py", line 455, in replicate_url
    raise ReplicationError(err)
__main__.ReplicationError: Command '['/usr/bin/curl', '-fL', '--create-dirs', '-o', '/Library/Management/erase-install/content/downloads/11/62/002-66265-A_HKQGKQG1Z4/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93/InstallAssistant.pkg', '-w', '%{http_code}', '--compressed', 'https://swcdn.apple.com/content/downloads/11/62/002-66265-A_HKQGKQG1Z4/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93/InstallAssistant.pkg']' returned non-zero exit status 56.
   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.

   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1042: 13073 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$**

**To Reproduce**
 - The script is being pushed out via Jamf.  I had users attempt to install via selfservice as well.  Error is consistent across a number of machines
 
**Expected behavior**
The expectation is that the machine pulls the correct os and installs.

**Code/log output**
Please supply the full command used, and if applicable, add full output from Terminal or from `/var/log/erase-install.log`. Either upload the log, or paste the output in a code block (triple backticks at the start and end of the code block please!).

**Environment (please complete the following information):**
 - OS version 12.1
 - erase-install version 26.0

**Comment by grahampugh** [comment]
Looks like a download error to me, not a bug.

**Comment by mrally7** [comment]
Not sure why with the updated package I only have the option fro two product id's

Result of command:
[erase-install] v26.1 script execution started: Fri Mar 25 15:10:11 EDT 2022
   [erase-install] Caffeinating this script (pid=3033)
   [check_free_space] OK - 228 GB free/purgeable disk space detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Opening DEPNotify download message (language=en)
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Checking that selected version 12.2.1 is available
   [run_installinstallmacos] This command is now being run:
   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --pkg --version 12.2.1 --validate
installinstallmacos.py - get macOS installers from the Apple software catalog
This Mac:
Model Identifier : MacBookPro14,1
Board ID         : Mac-B4831CEBD52A0C4C
OS Version       : 10.14.6
Build ID         : 18G103
 #  ProductID       Version    Build    Post Date   Title
 1  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur
 2  071-08758       12.3       21E230   2022-03-14  macOS Monterey
A valid installer for version 12.2.1 is not available for this computer. Run again without --version argument to select a valid build to download.
   [run_installinstallmacos] No disk image found. I guess nothing got downloaded.
   [erase-install] attempting to terminate the ‘caffeinate’ process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1055:  3049 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$

**Comment by grahampugh** [comment]
The --pkg option is only really relevant for macOS 10.15 and above. I suspect the catalog on 10.14 doesn't contain the full list of packages.
