### ISSUE TITLE
Script not running properly on M1 when launched via Rosetta-emulated admin tool

### ISSUE THREAD

**Issue by dechkovanen** [grahampugh/erase-install#225]
**Describe the bug**
When initiating the script from 3rd party tool (ManageEngine Desktop Central in this case) and the tool is not universal but runs via Rosetta, the script seems to fail. This is likely due to anything launched via the tool running under Rosetta as well and the script cannot handle this

**To Reproduce**
Script installed using the basic pkg. Launching the script via ManageEngine Desktop Central using command `/bin/bash /Library/Management/erase-install/erase-install.sh --reinstall --update --depnotify --current-user` causes 1) password prompt not appear and 2) DEPnotify window to open, saying "Upgrading macOS..." but the progress bar never advances and computer sits at the DEPnotify window forever.

When running the command as `arch -arm64 /bin/bash /Library/Management/erase-install/erase-install.sh --reinstall --update --depnotify --current-user` the password prompt appears and everything works.
 
**Expected behavior**
The script would check whether it's running natively on Intel, on Rosetta or natively on Apple Silicon and work in any case.

**Environment (please complete the following information):**
 - OS version 12.2.1
 - erase-install version 26

**Comment by joelfjimenez** [comment]
I had similar issues today on my test M1 machine, manually installing Rosetta seemed to help
/usr/sbin/softwareupdate --install-rosetta

**Comment by grahampugh** [comment]
Please try the latest 26.1 upload.

**Comment by reuven-cohen** [comment]
Im also running into issues when trying to upgrade to Monterey on an M1.
The system is sitting on the "Upgrading macOS" DEPNotify Screen stating "This process may take up to 30 minutes. Once completed your computer will reboot and begin the upgrade."

Rosetta is already installed to the machine.
I also tried running the `arch -arm64 /bin/bash ` as a prefix to the command below with no success.

MDM: JAMF Pro

Pkg: erase-install-depnotify-26.1.pkg

Command: `/Library/Management/erase-install/erase-install.sh --reinstall --os=12 --update --min-drive-space=40 --current-user --check-power --no-fs --depnotify --cleanup-after-use`

Log Excerpt:

Product downloaded and installed to /Library/Management/erase-install/Install_macOS_12.4-21F79.sparseimage
   [run_installinstallmacos] Mounting sparse disk image to identify installer app.
   [erase-install] Installer is at: /Volumes/Install_macOS_12.4-21F79/Applications/Install macOS Monterey.app
   [erase-install] Closing DEPNotify download message (language=en)
/Library/Management/erase-install/erase-install.sh: line 807: kill: (1821) - No such process
   [check_free_space] OK - 406 GB free/purgeable disk space detected

   [erase-install] WARNING! Running /Volumes/Install_macOS_12.4-21F79/Applications/Install macOS Monterey.app with reinstall option

   [erase-install] Opening DEPNotify message (language=en)
   [erase-install] Writing LaunchDaemon which will remove /Library/Management/erase-install at next boot
An error occurred preparing this update. Please try again.
By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.

   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1078:  1701 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$
