### ISSUE TITLE
Timer set to reboot the mac 

### ISSUE THREAD

**Issue by mani2care** [grahampugh/erase-install#232]
Hi THis is great work to do the install latest os or the migration 

but simply pushing to end user mostly all are working some unsaved documents atleast we need to give some time to reboot the mac like 1 hr or day 

can be possible to to do this ?

<img width="336" alt="image" src="https://user-images.githubusercontent.com/52978899/166443171-96412823-3ac3-4e08-8e49-37cd27aa89d5.png">

**Comment by grahampugh** [comment]
There are plenty of ways to do that already. 

The user can receive a forced description when they run it from Jamf Self Service. 

You can separate the download and install phases into 2 separate policies. 

There is a --confirm option that stops the process until the user confirms. 

And there is a --rebootdelay option that gives up to 5 minutes delay after the update is ready (which is the maximum allowed by Apple).
