### ISSUE TITLE
[check_newer_available] ERROR running installinstallmacos.py, cannot continue

### ISSUE THREAD

**Issue by Rorzzer** [grahampugh/erase-install#233]
Hi Graham,

We are seeing the below error recently, is this a python M1 issue? Or am I missing something else here?

Command: /Library/Management/erase-install/erase-install.sh --reinstall --os=12.3 --update --depnotify --cleanup-after-use --check-power --force-curl --power-wait-limit 180

Model: MacBookPro18,1

OS Version: 12.2.0

Script Version: 26

`[get_relocatable_python] Relocatable Python is installed in /Library/Management/erase-install

   [check_newer_available] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --list
Could not replicate https://swdist.apple.com/content/downloads/20/37/002-65695-A_JXBNO95L82/wwmyfh1vggj8qsk8dv069c9dmz1zmjm3fq/002-65695.English.dist: Command '['/usr/bin/curl', '-sfL', '--create-dirs', '-o', '/Library/Management/erase-install/content/downloads/20/37/002-65695-A_JXBNO95L82/wwmyfh1vggj8qsk8dv069c9dmz1zmjm3fq/002-65695.English.dist', '-w', '%{http_code}', '--compressed', '-z', '/Library/Management/erase-install/content/downloads/20/37/002-65695-A_JXBNO95L82/wwmyfh1vggj8qsk8dv069c9dmz1zmjm3fq/002-65695.English.dist', 'https://swdist.apple.com/content/downloads/20/37/002-65695-A_JXBNO95L82/wwmyfh1vggj8qsk8dv069c9dmz1zmjm3fq/002-65695.English.dist']' returned non-zero exit status 35.
Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 1368, in <module>
    main()
  File "/Library/Management/erase-install/installinstallmacos.py", line 1000, in main
    elif device_id and product_info[product_id]["DeviceIDs"]:
KeyError: 'DeviceIDs'
   [check_newer_available] ERROR running installinstallmacos.py, cannot continue`

**Comment by Rorzzer** [comment]
Have just seen this 
https://github.com/grahampugh/macadmin-scripts/issues/47

Will try again with 26.1 and report back.

**Comment by grahampugh** [comment]
`--os 12.3` is not a valid option and will return an undefined result. 

Please read the wiki about the `--os` and `--version` options.

**Comment by grahampugh** [comment]
26.0 is still perfectly functional. The issue 47 will not be a problem until 2023.
