### ISSUE TITLE
Add "Reboot & Upgrade Now" button if -rebootdelay is used

### ISSUE THREAD

**Issue by Benek107** [grahampugh/erase-install#235]
**Is your feature request related to a problem? Please describe.**
We would like to use reboot delay option, as it give a time for a user to close/save his work. But lets say if we set reboot delay to 30min it would be nice if user still have a button "Reboot & Upgrade Now" so he can force quicker reboot and upgrade instead of wait in idle for 30min. If somebody has slow network it might take ages to prepare upgrade so then i don't want to give user only 5min to save/close their work.

**Describe the solution you'd like**
Add "Reboot and Upgrade" button on reboot delay screen

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by grahampugh** [comment]
The maximum time is 5 minutes, so I don't think this is necessary.
