### ISSUE TITLE
cant upgrade from Catalina to the LATEST version of MacOS(11.6.6)

### ISSUE THREAD

**Issue by MehdiYawari** [grahampugh/erase-install#249]
Hi
We are using erase-install package to upgrade our device from MacOS catalina to Big Sur. It works perfectly by the way. The only Issue(or I am too dumb to find the right parameter) that I have is when upgrading from Catalina to Big Sur, the device will be upgraded to big sur 11.6.1 and as now Big Sur 11.6.6 has been released, i would like to upgrade our devices directly to the latest version of big sur compatible to the device. This is the command that I am using:
/Library/Management/erase-install/erase-install.sh --os=11 --pkg --move --reinstall --update --check-power --depnotify
I am using both "--update" and "--reinstall" parameter with no effect.
After the Upgrade, I can find the 11.6.6 version in system preferences
Appreciate it and BR
Mehdi

**Comment by grahampugh** [comment]
Have Apple published the 11.6.6 update in the software update catalog for Catalina? You can find out by running erase-install.sh --list on a Catalina machine. 

If not, you'll have to override the default catalog with the --catalog option, e.g. --catalog 11. But you will need to test whether the installer that's listed in the Big Sur catalog works on a Catalina device.

**Comment by grahampugh** [comment]
https://github.com/grahampugh/erase-install/wiki/FAQs#why-is-the-latest-macos-installer-not-available
