### ISSUE TITLE
installinstallmacos.py not downloading at office network

### ISSUE THREAD

**Issue by mani2care** [grahampugh/erase-install#251]
Hi Grahampugh,

When i am at office network installinstallmacos.py not getting downloading ?
same tested via personal network its happening , what is the difference & what is the issue with this.

Why i am not able to download this py file  what i need to unlock from my network to access this file to download is there any step.

kindly suggest 

Find the Script result: 
   [erase-install] v26.0 script execution started: Fri May 27 12:17:06 CEST 2022
   [erase-install] Caffeinating this script (pid=43242)
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [get_installinstallmacos] Downloading installinstallmacos.py...
shasum: /Library/Management/erase-install/installinstallmacos.py: No such file or directory
/Library/Management/erase-install/installinstallmacos.py: FAILED open or read
shasum: WARNING: 1 listed file could not be read
   [get_installinstallmacos] ERROR: downloaded installinstallmacos.py does not match checksum. Possible corrupted file. Deleting file.
rm: /Library/Management/erase-install/installinstallmacos.py: No such file or directory
Could not download installinstallmacos.py so cannot continue.

   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
   [erase-install] ERROR: 'caffeinate' could not be killed

**Comment by grahampugh** [comment]
Sorry but it's not up to me to diagnose what your office network is blocking. This is a one-person, free, open source project. It works on my office network.
