### ISSUE TITLE
Unable to download installinstallmacos.py

### ISSUE THREAD

**Issue by kingpocket** [grahampugh/erase-install#254]
I have JAMF Policies that curl the latest version of the script and it fails when attempting to install and verify installinstallmacos.py
[get_installinstallmacos] Downloading installinstallmacos.py...
/Library/Management/erase-install/installinstallmacos.py: FAILED
shasum: WARNING: 1 computed checksum did NOT match
   [get_installinstallmacos] ERROR: downloaded installinstallmacos.py does not match checksum. Possible corrupted file. Deleting file.
Could not download installinstallmacos.py so cannot continue.

**Comment by grahampugh** [comment]
Did you use `--force-curl`?

**Comment by kingpocket** [comment]
I'm always curling the latest version.  This one caches the Monterey Installer into the Applications folder.

/usr/bin/curl -s https://raw.githubusercontent.com/grahampugh/erase-install/main/erase-install.sh | sudo bash /dev/stdin --force-curl --update --move

This one is attempting to cache the Ventura Beta installer, but both scripts fail at validating installinstallmacos.py due to invalid checksum.

/usr/bin/curl -s https://raw.githubusercontent.com/grahampugh/erase-install/main/erase-install.sh | sudo bash /dev/stdin --seed DeveloperSeed --os=13 --force-curl --update --move

**Comment by kingpocket** [comment]
I receive the same checksum error even running:
/usr/bin/curl -s https://raw.githubusercontent.com/grahampugh/erase-install/main/erase-install.sh | sudo bash /dev/stdin --pkg --list

**Comment by grahampugh** [comment]
Sigh. I guess the checksum got messed up again. I wish I hadn't introduced that security feature :) I'll see if I can fix it.

**Comment by kingpocket** [comment]
That seems to have done the tick.  Thank you.  I also never tried the pkg version before and just modified my policies accordingly.
