### ISSUE TITLE
Check for available disk space before caching installer

### ISSUE THREAD

**Issue by sphen13** [grahampugh/erase-install#272]
In our use case we cache the installer in a separate step from installing it. we would like both handled by erase-install. in some of my testing I found that some machines will try to cache the installer (installinstallmacos.py) and the process ends up being incomplete as the disk runs out of space. This ends up causing other unwanted issues on the machine in general as well as when we try to run the script subsequently.

Trying to see if there is interest in checking for enough disk space prior to downloading an installer. This would involve another function or a revision of `check_free_space` which assumes reinstall or erase. I am not sure the best way to get the size metrics or if we should expose as variables. installinstallmacos.py for example requires double the size of the installer ~ 25 GB currently.

Right now we are preventing the installer cache on low disk space via other means (munki pkginfo etc), but i think it would be nice to have in the script.

thoughts?

**Comment by grahampugh** [comment]
There are already checks for enough disk space before and after downloading the installer. Can you explain what you think is not happening?

**Comment by grahampugh** [comment]
Close though inactivity.
