### ISSUE TITLE
Ensure sparsebundle is unmounted

### ISSUE THREAD

**Issue by sphen13** [grahampugh/erase-install#273]
I have encountered some situations where the script will exit in error for one reason or an other. In some of these cases the sparsebundle had been mounted to check the version/build, but due to the script exiting the image is still mounted and visible on the users desktop.

I wonder if we could potentially just set a variable that tells the script that we have mounted an image if we have and then create an exit function which checks if we have mounted an image, unmounts it and then exits with a code we provide.

thoughts?

**Comment by grahampugh** [comment]
Perhaps this will be addressed with the resolution of #271. Let me know.
