### ISSUE TITLE
Update Verbage and Icon on displayed winodws to make look less suspicious to unknowing users.

### ISSUE THREAD

**Issue by MacJediWizard** [grahampugh/erase-install#280]
**Is your feature request related to a problem? Please describe.**
We have had users cancel because they didnt know what was popping up on their Macs and didnt remember the email they were sent telling about it.

**Describe the solution you'd like**
I would like to be able to brand the windows and adjust the verbiage for company specific things for user trust

**Describe alternatives you've considered**
I could always modify the file but then that leads to a problem for updates. would be easier if we had a config file or plist that the scriot could read for this.

**Comment by grahampugh** [comment]
I recommend that you inform your users of the method for upgrading their computer in advance of deploying it. Send them an email with screenshots. People would not be suspicious of it if you had already communicated to them about this convenience tool.

**Comment by MacJediWizard** [comment]
﻿Untrue, People never read emails and even the ones that did recommended that we brand it better so they knew it was a company application. They get an email, a management notification and it also showes up in self service.

this is not my first time at the rodeo


thanks

will

**Comment by grahampugh** [comment]
Believe it or not, of the hundreds of organisations that use this script (including of course, my own), yours is the first to make this request. 

That said, a pull request which has no breaking changes in it would be given due respect.

**Comment by MacJediWizard** [comment]
﻿I believe it. The company i work for is medical so they scrutinize everything. i love your script an di am using it in very unique ways in my jamf setup. it is awesome. I am building a tool right now for how the company wants to roll out patch management that will build all the jamf policies through the api.  I am also doing a jnuc session on another script i wrote for how to clean up a jamf install after a previous admin. 

thanks so much for the info and lets see what we can come up with that will not break anything. It would be my pleasure to assist.

thanks

will

**Comment by MacJediWizard** [comment]
We ar setting up time so i can work on the dialogs as i spoke about above.  I also use your script for doing some custom patch management. I am working on a tool and having your script with a custom trigger to install will be a requirement. i will share with you once done. The tool that i am building just says that they have to come to your git and install the package in a policy with custom trigger. that is another thread. i will look into the branding and dialog shortly.

**Comment by grahampugh** [comment]
Closing through inactivity. I think forking the repo to do rebranding would be easier now that we are using swiftDialog.
