### ISSUE TITLE
Replace DEPNotify with SwiftDialog

### ISSUE THREAD

**Issue by grahampugh** [grahampugh/erase-install#296]
**Is your feature request related to a problem? Please describe.**
DEPNotify is great, but is somewhat inflexible in that there is only really one window size, and only one button can be added to the window. This means that various dialogs have to be done using osascript instead.

In contrast, SwiftDialog can work like DEPNotify, but also have different window sizes with multiple buttons and inputs. Therefore it can completely replace DEPNotify, jamfHelper and osascript, simplifying the erase-install code.

**Describe the solution you'd like**
Implement SwiftDialog windows for all dialogs

**Comment by asri-tm** [comment]
i wonder if SwiftDialog has the same issue with DEPNotify where extended displays will not show when running on full screen mode.

**Comment by grahampugh** [comment]
v28.0+ is swiftDialog.
