### ISSUE TITLE
Sparseimage not deleted when using the --move option

### ISSUE THREAD

**Issue by andyincali** [grahampugh/erase-install#297]
The downloaded sparseimage is not deleted when using the `--move` option. 

This seems to be because `find_existing_installer` is run before the download, and thus the `$existing_sparseimage` variable is empty when the `rm` is run as a part of `move_to_applications_folder()`.

It should be possible to populate `$existing_sparseimage` by adding this just below the `existing_installer` stuff on line 1097:

`existing_sparseimage=$( find "$workdir/"*.sparseimage -maxdepth 1 -type f -print -quit 2>/dev/null )`

**Comment by grahampugh** [comment]
Ah, I understand the problem. `existing_sparseimage` only applies when the script is run and a sparseimage is found already. If the sparseimage is freshly downloaded and `--move` is invoked, we only have `downloaded_sparseimage`. Yeah, should be able to fix that.

**Comment by grahampugh** [comment]
Should hopefully be fixed in the latest v27.0 upload.
