### ISSUE TITLE
Resumable Download

### ISSUE THREAD

**Issue by Guisch** [grahampugh/erase-install#301]
Hello 👋🏼

**Is your feature request related to a problem? Please describe.**
Updating/Upgrading/Wiping Macs with low bandwidth Internet is hard because of the ten-ish GB every update weight.

**Describe the solution you'd like**
Add the `-C -` to the curl command that download the update to resume where the last download started.

Probably adding a new command arg is better for usability to enable resumable download like `--resumable-download`.

Man Page of Curl:
> -C/--continue-at <offset>
Continue/Resume a previous file transfer at the given offset. The given offset is the exact number of bytes that will be skipped counted from the beginning of the source file before it is transferred to the destination. If used with uploads, the ftp server command SIZE will not be used by curl.
Use "-C -" to tell curl to automatically find out where/how to resume the transfer. It then uses the given output/input files to figure that out.
If this option is used several times, the last one will be used.

**Describe alternatives you've considered**
None

**Additional context**
Thanks

**Comment by grahampugh** [comment]
What happens if the cache is corrupted?

**Comment by grahampugh** [comment]
I believe mist-cli attempts resumed downloads already, though not indefinitely.

```
  --retries <retries>     Number of times to attempt resuming a download before failing. (default: 10)
  --retry-delay <retry-delay>
                          Number of seconds to wait before attempting to resume a download. (default: 30)
```

**Comment by Guisch** [comment]
> What happens if the cache is corrupted?

Adding resume capability does not increase corruption chance. You can get corrupted file with resumed download just like you can have corrupted file with a one time download.
That being said, if the file is corrupted, startosinstall prevent installation and print `Installation cannot proceed because the installer is damaged` at the `Preparing to run macOS Installer...` stage. (I confirmed it by starting an install with an intentionally corrupted file with `dd`).

> I believe mist-cli attempts resumed downloads already, though not indefinitely.

Indeed and that's great news because it means that it's already implemented. I just think we should be able to resume when re-launching the process. From what I understand, here mist-cli tries to resume if internet connection briefly but we are not capable to resume if a download if the process is killed.
Why ? Because when we cache an update that takes 5+h to download (in background), user might stop its device stopping the caching process. So next time the user use its device, would be great to have the download start where it stopped.

**Comment by Guisch** [comment]
Fixed with https://github.com/grahampugh/erase-install/releases/tag/v28.1
🚀
