### ISSUE TITLE
--version used a newer major os installer that was on the system than was called

### ISSUE THREAD

**Issue by dnikles** [grahampugh/erase-install#308]
**Describe the bug**
--version=12.6 used to call, ventura installer already present in /Applications was used

**To Reproduce**
 - this was called via a script in jamf using the following "/Library/Management/erase-install/erase-install.sh" --version=12.6 --update --check-power --power-wait-limit 300 --reinstall --pkg --move --min-drive-space 30 --current-user --rebootdelay 10
 - The 27.1 erase install pkg was used
 
**Expected behavior**
Download and use the installer specified by the --version 

**Code/log output**
```
Script result: [erase-install-launcher] Starting script "/Library/Management/erase-install/erase-install.sh" --version=12.6 --update --check-power --power-wait-limit 300 --reinstall --pkg --move --min-drive-space 30 --current-user --rebootdelay 10

   [erase-install] v27.1 script execution started: Fri Oct 28 13:54:04 EDT 2022
   [erase-install] Caffeinating this script (pid=4233)
   [check_free_space] OK - 52 GB free/purgeable disk space detected
   [check_power_status] OK - AC power detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] Installer found at /Applications/Install macOS Ventura.app.
   [check_installer_is_valid] Checking validity of /Applications/Install macOS Ventura.app.
Volume Shared Support on disk2s2 force-unmounted
   [check_installer_is_valid] Mounting /Applications/Install macOS Ventura.app/Contents/SharedSupport/SharedSupport.dmg
   [check_installer_is_valid] Using Build value from com_apple_MobileAsset_MacSoftwareUpdate.xml
Volume Shared Support on disk2s2 force-unmounted
   [compare_build_versions] Comparing (1) 18G9323 with (2) 22A380
   [check_installer_is_valid] Installer: 22A380 >= System: 18G9323 : valid build.
   [erase-install] Checking for newer installer
   [check_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [check_python] Relocatable Python is installed in /Library/Management/erase-install
   [check_newer_available] checking against package installers
   [check_newer_available] Checking against version 12.6 only

   [check_newer_available] No newer builds found
   [erase-install] Running on architecture i386
   [erase-install] Installer is at: /Applications/Install macOS Ventura.app
   [erase-install] Invoking --move option
   [move_to_applications_folder] Valid installer already in /Applications folder
   [erase-install] Closing jamfHelper download message (language=en)

   [check_free_space] OK - 52 GB free/purgeable disk space detected

   [erase-install] WARNING! Running /Applications/Install macOS Ventura.app with reinstall option

   [erase-install] Opening jamfHelper message (language=en)
   [launch_startosinstall] Launching startosinstall
```

**Environment (please complete the following information):**
 - OS version 10.14.6
 - erase-install version 27.1

**Additional context**

**Comment by deathatog** [comment]
Saw the same issue using version erase-install 26 and the setting --os=12 
Run the script as a script policy in jamf

`  [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] Installer found at /Applications/Install macOS Ventura.app.
   [check_installer_is_valid] Checking validity of /Applications/Install macOS Ventura.app.

   [compare_build_versions] Comparing (1) 20G817 with (2) 22A380
   [check_installer_is_valid] Installer: 22A380 >= System: 20G817 : valid build

  [compare_build_versions] 22A380 = 22A380
   [compare_build_versions] Comparing (1) 21G217 with (2) 22A380
   [compare_build_versions] Comparing (1) 20G918 with (2) 22A380
   [check_newer_available] No newer builds found
   [erase-install] Installer is at: /Applications/Install macOS 

`

**Comment by grahampugh** [comment]
@deathatog version 26 is old. Have you tried 27.1?

**Comment by deathatog** [comment]
Updating to version 27.1 fixed the issue for me
