### ISSUE TITLE
Receiving a Error 42 in jamf policy history logs on multiple users laptops.

### ISSUE THREAD

**Issue by dvasquezavant** [grahampugh/erase-install#309]
**Describe the bug**
The policy and upgrade process seems to be going ok then I see and error 42 mid way through the process while also seeing that the end-user declined to upgrade the laptop. 

**To Reproduce**
 - If applicable, please provide the full command used when running the script.
![Screenshot 2022-10-31 at 11 19 15 AM](https://user-images.githubusercontent.com/101146428/199057986-f9ed9b30-42ca-4207-9a70-71f5af0824c6.png)

 - Please describe how the script was run. 
 - I am running through Jamf pro policy with commands
 
**Expected behavior**
I want the end users laptop to be upgraded to 12.6 specifically

**Code/log output**
Please supply the full command used, and if applicable, add full output from Terminal or from `/var/log/erase-install.log`. Either upload the log, or paste the output in a code block (triple backticks at the start and end of the code block please!).

**Screenshots**
The screenshots outline the error code I see and also the commands switches I am using with the erase and install script. Also I am still seeing the policy as completed when it failed. is that expected behavior.  

**Environment (please complete the following information):**
 - OS version 12.5.1
 - erase-install version 27.0
 - Jamf pro 10.42
![Screenshot 2022-10-31 at 11 23 34 AM](https://user-images.githubusercontent.com/101146428/199058319-e0e49be8-1302-4317-9499-354b9019d5d2.png)
![Screenshot 2022-10-31 at 11 19 15 AM](https://user-images.githubusercontent.com/101146428/199058375-a0a8c7de-460d-4e0b-94bf-553da2c84dba.png)
![Screenshot 2022-10-31 at 11 19 15 AM](https://user-images.githubusercontent.com/101146428/199058402-5d9bc0bb-b37d-4a82-ba91-725360b7c7ac.png)

**Additional context**
**Now this is not all bad I have used this process to update 100's of laptops in our environment and this is really so great. Excited to continue to use your process. So do nto get me wrong. Like an admin I do not have so many resources to dedicate to fix these issues. But from your perspective I want to know if what I am seeing makes sense and if you have any answers.**

**Comment by grahampugh** [comment]
"The installer is damaged" -> that's your answer. You'll need to download it again.

PS. you have an error in your Jamf policy. You have put two different arguments (`--force-curl --update`) in to Parameter 4 which will not work. If you do this correctly, the `--update` parameter should ensure that any corrupt installer is replaced.

**Comment by dvasquezavant** [comment]
Thank you for the information and feedback!

My mistake on the commands (--force-curl --update) I thought we were able
to put 2 commands in each parameter. But I removed --force-curl and put in
--update.

Thank you Sir!
Dom

On Tue, Nov 1, 2022 at 7:40 AM Graham Pugh ***@***.***> wrote:

> Closed #309
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_grahampugh_erase-2Dinstall_issues_309&d=DwMCaQ&c=sg0gIgj-pqT9xZp1nZjt0Q&r=6RVHPGHUyvTPrwD1zOyZf1Sk9IGKRM9jU1kYnWO4h2Y&m=ruUT_MkWDUIPsHdybHd0OCy335PQqgeXi1Ia0IY70psrf2VjkYLuN0g7dYJItrHD&s=GqP0aJTDj9z6XfFqQl7zlalp9Dcsu2q_dEeGZ1zmyNY&e=>
> as completed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_grahampugh_erase-2Dinstall_issues_309-23event-2D7712933984&d=DwMCaQ&c=sg0gIgj-pqT9xZp1nZjt0Q&r=6RVHPGHUyvTPrwD1zOyZf1Sk9IGKRM9jU1kYnWO4h2Y&m=ruUT_MkWDUIPsHdybHd0OCy335PQqgeXi1Ia0IY70psrf2VjkYLuN0g7dYJItrHD&s=9m7xOXVKmlSO-DglI1hiN3FSZGRaqBUNVzaNDeG0pZk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYDV6PBW5R72HWDCNBYJSRLWGEFSFANCNFSM6AAAAAARTIDNCE&d=DwMCaQ&c=sg0gIgj-pqT9xZp1nZjt0Q&r=6RVHPGHUyvTPrwD1zOyZf1Sk9IGKRM9jU1kYnWO4h2Y&m=ruUT_MkWDUIPsHdybHd0OCy335PQqgeXi1Ia0IY70psrf2VjkYLuN0g7dYJItrHD&s=i1Jme5194uW9BPPvs-Gh6xZEN9LdLiWklRivEtCBnzA&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

*Dominic Vasquez*

IT Systems Engineer, Avant LLC
Avant.com <http://www.avant.com/> | Financially ForwardTM

-- 
This e-mail is only intended for the person(s) to whom it is addressed and 
may contain confidential information.  Any unauthorized review, use, 
disclosure, or distribution is prohibited. If you received this e-mail in 
error, please notify the sender by reply e-mail and then delete this 
message and any attachments from your system. Thank you for your 
cooperation.
