### ISSUE TITLE
Reached end of script. Exit with error 42. Monterey to Ventura

### ISSUE THREAD

**Issue by wbragass** [grahampugh/erase-install#314]
I am trying to upgrade a new intel based MacBook Pro from Monterey 12.6.1 to Ventura 13.0.1 using the --os=13 option.
I am utilizing version 27.1_depnotify.pkg within Jamf pro. 
I successfully upgraded a 2017 iMac from 12.6.1 to 13.0.1 using the same jamf policy. 
My MacBook Pro times out at the Preparing your Mac for upgrade screen. Within the log file it gets to 
`[Launch_startosinstall] Launching startosinstall `

after an hour the process times out and fills in the log with the rest.....
`[erase-install] Timeout reached for PID 61613!
/Library/Management/erase-install/erase-install.sh: line 2660: 61613 Terminated: 15     /bin/cat 0<&4
  [erase-install] Reached end of script. Exit with error 42.`

Here is my Jamf run command:
`/Library/Management/erase-install/erase-install.sh --os=13 --update --reinstall --move --depnotify`

Can you think of any reason it would work on one machine but not another? Both machines are listed on Apples list of Ventura capable Macs so I can't imagine that being a problem. Can the process be interrupted by Malwarebytes AV?

**Comment by grahampugh** [comment]
There's a 60 minute time limit set. Seems like your machine needs longer for some reason? I'd be interested to know if it's quicker without the AV software running.

**Comment by wbragass** [comment]
I tried on another MacBook Pro and it too timed out. The policy works for minor upgrades such as 13.0 to 13.0.1 and successfully upgraded my iMac from Monterey to Ventura. The only difference between them is that the iMac is on MacOS extended journaled and the MacBook Pros are on APFS. Do you know if there is any difference for the script there?

**Comment by grahampugh** [comment]
The startosinstall command is only designed for APFS.

**Comment by wbragass** [comment]
My iMac has a 3TB fusion drive with MacOS Extended Journaled and the erase-install worked to upgrade it from Catalina to Monterey and again from Monterey to Ventura beautifully. I have another MacBook Pro(on APFS) that was able to successfully upgrade from Monterey to Ventura but I have 2 other MBPs (on APFS) that stall out at the Launching startosinstall portion of the script. The install MacOS Ventura.app appears in the applications folder so that is successfully downloading but when it times out the Ventura installer disappears. Is there a way to prevent the 'Preparing to install' window from taking up the whole screen so I can investigate what's happening during that part? It's almost like it may be mounting in the wrong place when it launches the installer or something to that effect.

**Comment by grahampugh** [comment]
Use --no-fs to prevent a full screen window.

**Comment by wbragass** [comment]
When the script runs, it downloads the sparse image. The log says it gets mounted:


Making empty sparseimage...
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
Product downloaded and installed to /Library/Management/erase-install/Install_macOS_13.0.1-22A400.sparseimage
   [run_installinstallmacos] Mounting sparse disk image to identify installer app.
   [erase-install] Installer is at: /Volumes/Install_macOS_13.0.1-22A400/Applications/Install macOS Ventura.app
   [erase-install] Closing DEPNotify download message (language=en)
/Library/Management/erase-install/erase-install.sh: line 1266: kill: (14169) - No such process
   [check_free_space] OK - 1145 GB free/purgeable disk space detected

   [erase-install] WARNING! Running /Volumes/Install_macOS_13.0.1-22A400/Applications/Install macOS Ventura.app with reinstall option

   [erase-install] Opening DEPNotify message (language=en)
   [launch_startosinstall] Launching startosinstall

However, when I go to this location it is empty. I do an ls -la /Volumes/Install_macOS_13.0.1-22A400/Applications 
and there is no Install macOS Ventura.app file.

I repeat this on my other Mac and the file is there and successfully upgrades. Do you know why it would not be present on some Macs and not others?

**Comment by grahampugh** [comment]
I don't think it can have been empty, otherwise the script would have been unable to detect the app inside and would not have got to the point where it says it's launching startosinstall. 

I notice you said it's a 3TB Fusion Drive and there's only 1.1TB free. That might explain why it is timing out. 

I guess the answer is for the timeout to be longer. 1 hour was arbitrary based on the normal time it takes which is generally only 10-20 minutes.

**Comment by wbragass** [comment]
Im not having any issues with the Fusion drive Mac. That Mac succeeded beautifully. 

The Macs I am having issues with are 2019 16inch MacBook Pro with 2TB SSD and i9 with 64GB of Ram. These Macs have APFS and are on Monterey 12.6.1 FileVault enabled.(All of our Macs have FileVault enabled.)

We are able to successfully update from 12.6 to 12.6.1 but not to 13 on these two Macs. 

william@wbragassa-327-mbp ~ % ls /Volumes
Install_macOS_13.0.1-22A400	Macintosh HD
william@wbragassa-327-mbp ~ % ls /Volumes/Install_macOS_13.0.1-22A400/Applications
william@wbragassa-327-mbp ~ %

**Comment by wbragass** [comment]
I tested with a 2 hour timeout and no change.

**Comment by wbragass** [comment]
So, I implemented the 28.0 version and no change. Still fails, however, it downloads 13.0.1 and puts it in the /Applications folder. As soon as it tries to run the installer it crashes. I found the Install macOS Ventura.app in the /Applications folder and when I tried to double click it and run it manually it just disappears rather than opening?

**Comment by wbragass** [comment]
I figured out the issue. There was software restriction policy on Jamf Pro that was killing the Install macOS Ventura.app process. Removed the policy and it works now.
