### ISSUE TITLE
AppleLanguages Does not exists error at frist use

### ISSUE THREAD

**Issue by Draawa** [grahampugh/erase-install#315]
Hey,

I feel so goddamn stupid to fail at the very first step but this does drive me crazy.

I downloaded the lastest release with the recommended method as advised, so the package straight on my test computer.

So I tried using the the erase-install.sh script and I already bump into an issue. I pretty sure I've missed something but I've read and read the wiki for hours an couldn't find what's wrong. Any clue ?

**Command used and result :**

> admin@xxxxxxxxx erase-install % sh erase-install.sh --reinstall
> Print: Entry, "AppleLanguages:0", Does Not Exist
> 
>    [erase-install] v27.1 script execution started: Mer 16 nov 2022 15:30:29 CET
> erase-install.sh: line 2186: syntax error near unexpected token `>'
> erase-install.sh: line 2186: `exec > >(tee "${LOG_FILE}") 2>&1'
> 
> 
>    [finish] Script exit code: 258

**Comment by grahampugh** [comment]
Hi @Draawa 
I'm afraid you did not follow a recommended method. You have run the script using `sh`, but it is a `bash` script. So use `bash` or don't specify an interpreter: `./erase-install.sh --reinstall` is just fine.

**Comment by Draawa** [comment]
Thank you...
I told it was something stupid.
