### ISSUE TITLE
ERROR! The startosinstall binary requires a user to be logged in.

### ISSUE THREAD

**Issue by ajleach** [grahampugh/erase-install#33]
Not sure if this is an issue with this software or something new that Apple introduced, but when we run this via SSH we're now getting:

```
Product downloaded and installed to /Library/Management/erase-install/Install_macOS_10.15.1-19B88.sparseimage
   [run_installinstallmacos] Mounting sparse disk image to identify installer app.
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	EFI                            	
/dev/disk2s2        	Apple_HFS                      	/Volumes/Install_macOS_10.15.1-19B88

   [erase-install] WARNING! Running /Volumes/Install_macOS_10.15.1-19B88/Applications/Install macOS Catalina.app with eraseinstall option

    [erase-install] ERROR! The startosinstall binary requires a user to be logged in.
```

**Comment by grahampugh** [comment]
Did it work before from SSH? Even if there was no user logged in. I added this on somebody’s recommendation, but I admittedly had never tried to run it remotely on a Mac at the login window.

**Comment by ajleach** [comment]
It worked up until this change - we had to keep the SSH session open until the Mac would reboot, but typically no user was logged in when we'd run this. It's just faster to run this via SSH than having to login to a hidden administrator account and potentially having to click through license agreements and iCloud Sign-in, etc.

If there were an option during runtime to skip this check that would be great, otherwise we'll probably just hardcode an older version of your script into our process.

**Comment by grahampugh** [comment]
No worries, I've removed (commented out) the check in v0.10.1 since it doesn't sound like it's necessary after all.

**Comment by ajleach** [comment]
Thank you!
