### ISSUE TITLE
Python - Bad/illegal format or missing URL

### ISSUE THREAD

**Issue by kvellano** [grahampugh/erase-install#330]
Some reports of Python failing to download/install:

  [check_python] Downloading MacAdmins Python package...
Path not found.
curl: (3) URL using bad/illegal format or missing URL
installer: Error - the package path specified was invalid: '/Library/Management/erase-install/macadmins_python-v3.10.2.80694.pkg'.
   [check_python] Could not download MacAdmins Python.
   [run_installinstallmacos] Checking that selected OS 13 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --os 13 --validate
/Library/Application Support/JAMF/tmp/macOS In-Place Upgrade: line 1371: : command not found
   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.

**Comment by grahampugh** [comment]
Assuming you're just grabbing the script from GitHub and adding it to Jamf, can you try the one that's here: https://github.com/grahampugh/erase-install/tree/v27.2-rc 

Looks like the version of the MacAdmins Python I was calling was pulled last night. I've altered the URL to reflect the current latest release.

**Comment by kvellano** [comment]
> Assuming you're just grabbing the script from GitHub and adding it to Jamf, can you try the one that's here: https://github.com/grahampugh/erase-install/tree/v27.2-rc
> 
> Looks like the version of the MacAdmins Python I was calling was pulled last night. I've altered the URL to reflect the current latest release.

Yes, was using the script. The 27.2-RC variant solved the problem. Thanks!
