### ISSUE TITLE
showing invalid installer while running the erase install script.

### ISSUE THREAD

**Issue by vysakhjayadas** [grahampugh/erase-install#336]
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/119936720/213462748-42cd6160-be22-4e24-84e4-2ee4486c2ebd.png)

We are trying to update the macOS to Ventura 13.1. But the installation is getting failed and getting this error log from Jamf. The valid installer is present in Application folder, still it get failed. 
Is there any solution for this.

Thanks &Regards,
Vysakh

**Comment by grahampugh** [comment]
Looks like that machine's got in a state where you have a corrupt installer as well as a different installer in Applications. I think you'll need to clear up the working directory (delete /Library/Management/erase-install) and run again.
