### ISSUE TITLE
how can I downgrade from Catalina to Mojave please

### ISSUE THREAD

**Issue by aesthyrica** [grahampugh/erase-install#34]
how can I downgrade from Catalina to Mojave please I'm struggling

**Comment by grahampugh** [comment]
This script is not designed to do that. Macs are not really designed to do that either, and you cannot use `startosinstall` to do it. 

To downgrade a Mac, you need to create an external installation media for the version of the OS you require, and install from that, or in some circumstances you can use the alternate internet recovery method (shift+option+cmd+R) to install the original version of macOS that came with the device.
