### ISSUE TITLE
"Upgrading macOS" Progress Bar Immediately Goes to 100% Instead of Incrementing

### ISSUE THREAD

**Issue by rougegoat** [grahampugh/erase-install#344]
**Describe the bug**
When erase-install v28.1 gets to the "Upgrading macOS" screen, the progress bar fills up to 100% immediately while the text below it correctly displays the percentage complete.

**To Reproduce**
Run from terminal with the following flags: --os 13 --replace-invalid --reinstall --check-power --reboot-delay 10 --no-fs --cleanup-after-use
 
**Expected behavior**
The progress bar should increment up as the percentage complete.

**Environment (please complete the following information):**
 - OS version [e.g. 12.0.1]: macOS 11, 12, and 13
 - erase-install version [e.g. 24.0] - please upgrade to the latest version before submitting a bug report.

**Comment by grahampugh** [comment]
Fixed in latest commit to `main` and latest release package.
