### ISSUE TITLE
27.x [check_python] Error

### ISSUE THREAD

**Issue by killer23d** [grahampugh/erase-install#346]
The following error were discovered for the 27.x version when executed on Jamf

`   [check_installinstallmacos] force-curl selected so installinstallmacos.py will be overwritten
   [download_installinstallmacos] Downloading installinstallmacos.py...
   [check_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [check_python] Downloading MacAdmins Python package...
Path not found.
curl: (3) URL using bad/illegal format or missing URL
installer: Error - the package path specified was invalid: '/Library/Management/erase-install/macadmins_python-v3.10.2.80694.pkg'.
   [check_python] Could not download MacAdmins Python.
   [run_installinstallmacos] Checking that selected build 22D49 is available`

Looks like it errors out in here: 
`macadmins_python_url="https://api.github.com/repos/macadmins/python/releases/tags/$macadmins_python_version"`

**Comment by grahampugh** [comment]
You're running an old version. Please update to 27.3 or 28.1.
