### ISSUE TITLE
run_list_full_installers returning Deferred Updates

### ISSUE THREAD

**Issue by bsidecode** [grahampugh/erase-install#347]
**Describe the bug**
run_list_full_installers is not filtering out updates deferred by major or minorUpdateDelay keys deployed via MDM. When run_fetch_full_installer runs and attempts to download the first update in ffi-list-full-installers.txt matching the criteria in the function, if said update was deferred the download process will fail.

**To Reproduce**
1. Deploy Configuration Profile for domain: com.apple.applicationaccess with the following configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>enforcedSoftwareUpdateMajorOSDeferredInstallDelay</key>
    <integer>90</integer>
    <key>forceDelayedMajorSoftwareUpdates</key>
    <true/>
  </dict>
</plist>
```

2. Attempt to run erase-install with --fetch-full-installer --overwrite
 
**Expected behavior**
erase-install to select the first non-deferred entry in ffi-list-full-installers.txt

**Code/log output**
Line in question is 2051

Current:
`if /usr/sbin/softwareupdate --list-full-installers > "$workdir/ffi-list-full-installers.txt"; then`

List-Full-Installers Output:
```
* Title: macOS Ventura, Version: 13.2, Size: 12261428KiB, Build: 22D49, Deferred: YES
* Title: macOS Ventura, Version: 13.1, Size: 11931164KiB, Build: 22C65, Deferred: YES
* Title: macOS Ventura, Version: 13.0.1, Size: 11866460KiB, Build: 22A400, Deferred: NO
* Title: macOS Ventura, Version: 13.0, Size: 11866804KiB, Build: 22A380, Deferred: NO
* Title: macOS Monterey, Version: 12.6.3, Size: 12115350KiB, Build: 21G419, Deferred: YES
* Title: macOS Monterey, Version: 12.6.2, Size: 12104568KiB, Build: 21G320, Deferred: YES
* Title: macOS Monterey, Version: 12.6.1, Size: 12108491KiB, Build: 21G217, Deferred: NO
```

run_fetch_full_installer outputs the following:
```
   [swu_fetch_full_installer] Running /usr/sbin/softwareupdate --fetch-full-installer  --full-installer-version 13.2
Scanning for 13.2 installer
Install failed with error: Update not available 
```

Possible Remediation:
`if /usr/sbin/softwareupdate --list-full-installers | grep -vO "Deferred: YES" > "$workdir/ffi-list-full-installers.txt"; then`

List-Full-Installers output with updated command:
```
* Title: macOS Ventura, Version: 13.0.1, Size: 11866460KiB, Build: 22A400, Deferred: NO
* Title: macOS Ventura, Version: 13.0, Size: 11866804KiB, Build: 22A380, Deferred: NO
* Title: macOS Monterey, Version: 12.6.1, Size: 12108491KiB, Build: 21G217, Deferred: NO
```

**Environment (please complete the following information):**
 - erase-install version [e.g. 28.0] - please upgrade to the latest version before submitting a bug report.

**Comment by grahampugh** [comment]
Please test https://github.com/grahampugh/erase-install/releases/tag/v29.1 which should fix this.
