### ISSUE TITLE
Fullscreen on rebootdelay while --no-fs 

### ISSUE THREAD

**Issue by sundeep443** [grahampugh/erase-install#348]
**Describe the bug**
after providing the --no-fs in the process in jamf we were getting fullscreen on rebootdely countdown screen.

**To Reproduce**
In Jamf policy we use --no-fs in Files and Process to get all the windows as utility window. As it was working fine till 27.2 as checked but it's having issues in the reboot delay screen in 28.1 ver. other screens were in utility but just the rebootdelay screen was fullscreen.
 
**Expected behavior**
The Reboot Delay screen should be in non-full screen or utility window when --no-fs used.

**Code/log output**
[erase-install.log](https://github.com/grahampugh/erase-install/files/10683630/erase-install.log)

**Screenshots**
<img width="1440" alt="Screenshot 2023-02-08 at 2 07 52 PM" src="https://user-images.githubusercontent.com/91255001/217482157-9a90a63b-45d3-4409-af0d-02c4eedbcffd.png">

**Environment (please complete the following information):**
 - OS version 12.6.3 to 13.2 
 - erase-install version 28.1

<img width="1440" alt="Screenshot 2023-02-08 at 1 57 59 PM" src="https://user-images.githubusercontent.com/91255001/217483724-fb7bb8b9-3fc9-4b2b-827c-e7717c68f272.png">

**Comment by tkimpton** [comment]
i have the same issue :(

**Comment by sahibbhai** [comment]
Yes, same here.

**Comment by sahibbhai** [comment]
Confirming that v29.0 has fixed this bug for me 🎉
