### ISSUE TITLE
[FR] for the non full screen would it be possible for a timeout

### ISSUE THREAD

**Issue by tkimpton** [grahampugh/erase-install#350]
**PLEASE NOTE THAT FEATURE REQUESTS ARE ONLY CONSIDERED AGAINST v.28.0+**

**Is your feature request related to a problem? Please describe.**
Would it be possible to Add a timeout the dialog box below? We currently use the fullscreen but wish to change this. One thing though is without a timeout we would just have people sitting at the OK button and on purpose move the dialog to the side of the screen and ignore it.  

<img width="598" alt="Screenshot 2023-02-08 at 13 33 53" src="https://user-images.githubusercontent.com/2095960/217544962-ebad176d-63f8-4655-9e56-c0d9f63b0994.png">

**Describe the solution you'd like**
option for a timeout flag on the no-fs dialog

**Describe alternatives you've considered**
Alternate is the full screen but our users don't like it

**Additional context**
none.

**Comment by grahampugh** [comment]
What do you mean by a timeout?

**Comment by tkimpton** [comment]
So it will timeout, close the dialog box and start. We have difficult users that they already on purpose move dialog boxes to the side to get one over in us.

**Comment by tkimpton** [comment]
Thanks for the info, I have tried the reboot delay for 5 minutes prior but it is going to a full screen. Just to clarify if I was to leave the dialog and not click ok, would the machine eventually just upgrade? If so then apologies I have nothing to worry about.
