### ISSUE TITLE
Download Icon does not show

### ISSUE THREAD

**Issue by nramo013** [grahampugh/erase-install#351]
During the download process, Icon will not show correctly for the System Preferences Icon.

The current setting is set at:

dialog_confirmation_icon="/System/Applications/System Settings.app" but not the actual icon for the app

**Comment by nramo013** [comment]
<img width="603" alt="Screen Shot 2023-02-08 at 9 33 08 AM" src="https://user-images.githubusercontent.com/19276258/217559733-a5b5b5cc-a123-4d7e-b626-4ba87981d659.png">

**Comment by macbm** [comment]
icon still missing with version 29.0 in "Upgrading macOS" and "Downloading macOS" prompts.
Device running script has OS 12.6.3, trying to upgrade to 13.2.1.
![Screen Shot 2023-02-23 at 3 16 16 PM](https://user-images.githubusercontent.com/38539306/221054747-f06cad80-1176-4473-aa0d-26d2a0057e2a.png)

**Comment by BigMacAdmin** [comment]
This may be the same issue I reported here: https://github.com/bartreardon/swiftDialog/issues/235

May not be an eraseinstall issue, but a SwiftDialog issue

**Comment by grahampugh** [comment]
Looks like a known issue with swiftDialog, nothing I can fix here.

**Comment by grahampugh** [comment]
I believe I have fixed this in v31.0 by providing the icons directly.
