### ISSUE TITLE
User is not informed via dialog if space is not available on device; erase-install pkg v28.1

### ISSUE THREAD

**Issue by crgundersen** [grahampugh/erase-install#353]
**Describe the bug**
When testing upgrading via erase-install v28.1, I'm finding that the user does not receive feedback/dialog if the device does not have sufficient space available.

**To Reproduce**
I'm leveraging a Jamf policy w/ uploaded pkg and the following script parameters in Files and Processes payload : `/Library/Management/erase-install/erase-install.sh  --fetch-full-installer --version=13.2 --reinstall --fs --check-power --power-wait-limit 360 --min-drive-space 50 --cleanup-after-use --no-timeout`

I used Apple's Disk Utility to create a Disk Image on device to create capacity issue for testing purposes.
 
**Expected behavior**
From the wiki [https://github.com/grahampugh/erase-install/wiki/4.-Upgrading-macOS#available-drive-space](url) `If this space is not available, the user is informed via a dialog and the script ends.` In my testing, user does not receive dialog/alert that there was a problem relating to insufficient disk capacity. Jamf policy is set to ongoing. so just given Done!/Reinstall button as feedback to user.

**Environment (please complete the following information):**
Test device is freshly DFU'd Apple Silicon M1 MBA running macOS Monterey 12.2.1
erase-install pkg is version 28.1

**Additional context**
Please let me know if workflow/expectations are incorrect. Happy to test/provide further feedback as needed. Thanks much!

**Code/log output**
From `/var/log/erase-install.log`. 
```2023-02-10 11:09:11  [erase-install] Caffeinating this script (pid=2285)
2023-02-10 11:09:11  [check_free_space] ERROR - 24 GB free/purgeable disk space detected
2023-02-10 11:09:11  [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1172:  2313 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$
2023-02-10 11:09:11  [finish] quitting dialog
2023-02-10 11:09:11  [finish] Script exit code: 1```

**Comment by grahampugh** [comment]
Should be fixed in https://github.com/grahampugh/erase-install/releases/tag/v29.0

**Comment by crgundersen** [comment]
Confirmation that working as expected in my testing against macOS 12.6.3 and v29.0
