### ISSUE TITLE
add option to call jamf policy

### ISSUE THREAD

**Issue by n0brainer** [grahampugh/erase-install#36]
I've got some locations that are behind proxies and restricted firewalls and I tried to run the 0.11.1 script on a machine there, and basically it can't get out to pull the swscan URLs to pull the OS versions.  However, we have the OS in a DMG on our jamf distribution points and a policy on a custom trigger.  

If the script 1) can't find the installer locally 2) wasn't able to download directly from apple, then can it try a 3rd attempt to call a policy?

We'd need multiple policies I guess depending on the OS installer to cache, but still would be doable.

**Comment by grahampugh** [comment]
If you know that the firewall will prevent the search, why not run the policy that puts the installer in place first? This script looks for an existing installer before going out to the internet so it would just use what it has.

**Comment by LukeHagar** [comment]
Yeah running a policy to copy the install to the /Applications folder before running this script would be advisable

**Comment by mani2care** [comment]
Like and recommended samples the way to install the commands like from jamf or via command to call and install and reinstall or erase and install or erase reinstall ect....

**Comment by grahampugh** [comment]
@mani2care see https://github.com/grahampugh/erase-install#setting-up-in-jamf-pro

**Comment by grahampugh** [comment]
Closing this issue because erase-install is already designed to look in /Applications for a suitable installer if the `--overwrite` option is omitted, so there is no need to call a jamf policy within the script.
