### ISSUE TITLE
Dialog to tell user not enough free space to install [FR]

### ISSUE THREAD

**Issue by jeden-92** [grahampugh/erase-install#362]
**PLEASE NOTE THAT FEATURE REQUESTS ARE ONLY CONSIDERED AGAINST v.28.0+**

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When using if the script detects there is not enough free space it would be great to show a dialog to the user instead of the script just exiting

**Describe alternatives you've considered**
no alternatives considered

**Comment by grahampugh** [comment]
There is a dialog. Please check the wiki.

**Comment by jeden-92** [comment]
Apologies missed this in the documentation, thank you for the update
