### ISSUE TITLE
Erase-Install syntax error near unexpected token - line 2596 - Exit code 258

### ISSUE THREAD

**Issue by okschl** [grahampugh/erase-install#363]
I am using the erase-install version 29 pkg and trying to perform action of erase and install but getting the below error message. I have tried the standalone script as well and get the seem error message.The dialog box never pops up asking for confirmation.

I am on macOS Ventura 13.2.1 and on an Intel MacBook Pro.

> $ sudo sh /Library/Management/erase-install/erase-install.sh --erase --version=13.1 --min-drive-space=35 --current-user --check-power --no-fs --depnotify --confirm
> 
> 2023-02-21 08:23:43  [erase-install] v29.0 script execution started: Tue Feb 21 08:23:43 EST 2023
> 2023-02-21 08:23:43  [erase-install] System version: 13.2.1 (Build: 22D68)
> 2023-02-21 08:23:43  [check_for_dialog_app] dialog is installed (/Library/Application Support/Dialog/Dialog.app)
> /Library/Management/erase-install/erase-install.sh: line 2596: syntax error near unexpected token `>'
> /Library/Management/erase-install/erase-install.sh: line 2596: `exec > >(tee "${LOG_FILE}") 2>&1'
> 
> 2023-02-21 08:23:43  [finish] quitting dialog
> 2023-02-21 08:23:43  [finish] Script exit code: 258

**Comment by grahampugh** [comment]
Two problems. 

1. You are running the script with sh. It is a bash script, not an sh script. 

2. You cannot downgrade from 13.2.1 to 13.1 - you cannot downgrade at all.

**Comment by rougegoat** [comment]
I'm getting this same result running on macOS 12.6.3 to upgrade to macOS 13 using the example command given in the documentation for running it from Jamf.

/Library/Management/erase-install/erase-install.sh --os 13 --update --reinstall --confirm

**Comment by okschl** [comment]
> Two problems.
> 
> 1. You are running the script with sh. It is a bash script, not an sh script.
> 2. You cannot downgrade from 13.2.1 to 13.1 - you cannot downgrade at all.

Sorry I didn't realize that. But I was under the impression that with the "erase" option, this would wipe and install whatever os version of your choosing. Was I mistaken?

I was testing it locally as it was failing to run via Jamf MDM with error below. The dialog box never pops up.

> 2023-02-21 11:59:16  [erase-install] Caffeinating this script (pid=9778)
> 2023-02-21 11:59:17  [check_free_space] OK - 193 GB free/purgeable disk space detected
> 2023-02-21 11:59:17  [erase-install] Looking for existing installer app or pkg
> 2023-02-21 11:59:17  [find_existing_installer] Installer found at /Applications/Install macOS Ventura.app.
> 2023-02-21 11:59:17  [check_installer_is_valid] Checking validity of /Applications/Install macOS Ventura.app.
> 2023-02-21 11:59:17  [check_installer_is_valid] Mounting /Applications/Install macOS Ventura.app/Contents/SharedSupport/SharedSupport.dmg
> 2023-02-21 11:59:18  [check_installer_is_valid] Using Build value from com_apple_MobileAsset_MacSoftwareUpdate.xml
> Volume Shared Support on disk2s2 force-unmounted
> 2023-02-21 11:59:19  [compare_build_versions] Comparing (1) 22D68 with (2) 22D68
> 2023-02-21 11:59:19  [compare_build_versions] 22D68 = 22D68
> 2023-02-21 11:59:19  [check_installer_is_valid] Installer: 22D68 >= System: 22D68 : valid build.
> 2023-02-21 11:59:19  [erase-install] Running on architecture i386
> 2023-02-21 11:59:19  [erase-install] Installer is at: /Applications/Install macOS Ventura.app
> 2023-02-21 11:59:20  [check_free_space] OK - 193 GB free/purgeable disk space detected
> 
> 2023-02-21 11:59:20  [erase-install] WARNING! Running /Applications/Install macOS Ventura.app with reinstall option
> 
> 2023-02-21 11:59:20  [erase-install] Sending to dialog: quit:
> 2023-02-21 11:59:20  [get_default_dialog_args] Invoking utility dialog
> 2023-02-21 11:59:20  [erase-install] User FAILED to confirm erase-install or reinstall
> 
> 2023-02-21 11:59:20  [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
> 
> 2023-02-21 11:59:20  [finish] quitting dialog
> 2023-02-21 11:59:20  [finish] Script exit code: 1

I just re-ran it again using "bash" and not getting the below error.

> If you do not agree, press CTRL-C and cancel this process immediately.
> Preparing to run macOS Installer...
> Preparing: 100.0%            An error occurred preparing the update.
