### ISSUE TITLE
Vaild Ventura installer on the system is being deleted

### ISSUE THREAD

**Issue by tkimpton** [grahampugh/erase-install#367]
**Describe the bug**
we are currently installing silent 13.2.1 Venrua installer so that it is on the system. When it is there and erase and install runs i see in the log No valid installer found. and it gets deleted the the download dialog appears again

**To Reproduce**
1.download apples Ventura 13.2.1 see https://github.com/scriptingosx/DownloadFullInstaller
2. upload to jamf pro and deploy to your macs
3. run the erase and install as per launcher with argument --version=13.2.1
 
**Expected behavior**
expect the 13.2.1 installer to be recognised and carry on. Instead it gets deleted and redownloaded

**Code/log output**
[erase-install 2.log](https://github.com/grahampugh/erase-install/files/10814380/erase-install.2.log)

**Screenshots**

<img width="1215" alt="Screenshot 2023-02-22 at 16 34 03" src="https://user-images.githubusercontent.com/2095960/220932438-bdaef8c4-ee07-4955-b822-569750833124.png">

**Environment (please complete the following information):**
 - OS version [e.g. 12.6.3 ]
 - erase-install version 29.0

**Additional context**

**Comment by grahampugh** [comment]
Would need to see the log output.

**Comment by tkimpton** [comment]
[erase-install 2.log](https://github.com/grahampugh/erase-install/files/10815346/erase-install.2.log)

**Comment by grahampugh** [comment]
If you re-upload this as .txt I will be able to read it before next week. Can't read .log on iOS apparently.

**Comment by tkimpton** [comment]
will close, cant reproduce it again. pls can you look at #352
