### ISSUE TITLE
Question | Best Practice

### ISSUE THREAD

**Issue by Todai1** [grahampugh/erase-install#371]
What is the best practice when using erase-install to specifically update the macOS & also wipe the device (Erase All Data) at the same time? when looking at the Wiki I am not sure if I am putting too many parameters in or It should be simplified.

Example A (Might be overkill)

/Library/Management/erase-install/erase-install.sh --build 22D68 --update --move --erase --check-power --min-drive-space 45

Example B (Slimmed down a bit)

/Library/Management/erase-install/erase-install.sh --erase --check-power --min-drive-space 45

I just want to make sure I am using this product correctly and not overcomplicating something that might be simple and straight forward. Thank you for your time & assistance.

**Comment by grahampugh** [comment]
`erase-install.sh --erase` is all you need.
