### ISSUE TITLE
erase-install v29. - Hangs at "searching for a valid macOS Installer..."

### ISSUE THREAD

**Issue by Trikster-Online** [grahampugh/erase-install#374]
I let my test computer sit here for two hours and never progressed passed this screen.

Output in Terminal is as follows.

% sudo /Library/Management/erase-install/erase-install.sh --reinstall --user=(name of the current admin user) --build 21G419 --cleanup-after-use --postinstall-command "jamf recon"
Password:

2023-02-21 16:04:48 [erase-install] v29.0 script execution started: Tue Feb 21 16:04:48 PST 2023
2023-02-21 16:04:48 [erase-install] System version: 11.4 (Build: 20F71)
2023-02-21 16:04:48 [check_for_dialog_app] dialog is installed (/Library/Application Support/Dialog/Dialog.app)
2023-02-21 16:04:48 [erase-install] Caffeinating this script (pid=799)
2023-02-21 16:04:48 [check_free_space] OK - 956 GB free/purgeable disk space detected
2023-02-21 16:04:48 [erase-install] Looking for existing installer app or pkg
2023-02-21 16:04:48 [find_existing_installer] No valid installer found.
2023-02-21 16:04:48 [erase-install] Checking if the cached installer matches requested build...
2023-02-21 16:04:48 [compare_build_versions] Comparing (1) 21G419 with (2)
2023-02-21 16:04:48 [compare_build_versions] 21G419 >
2023-02-21 16:04:48 [erase-install] Existing installer does not match requested build, so replacing...
2023-02-21 16:04:48 [overwrite_existing_installer] Overwrite option selected. Deleting existing version.
2023-02-21 16:04:48 [erase-install] Running on architecture i386
2023-02-21 16:04:48 [get_default_dialog_args] Invoking utility dialog
2023-02-21 16:04:48 [check_for_mist] mist is installed (/usr/local/bin/mist)
┌──────────────────┐
│ INPUT VALIDATION │
└──────────────────┘
├─ Search only for latest (first) result will be 'false'...
├─ Include betas in search results will be 'false'...
├─ Only include compatible installers will be 'true'...
├─ Export path will be '/Library/Management/erase-install/mist-list.json'...
├─ Export path file extension is valid...
├─ Output type will be 'ascii'...
┌────────┐
│ SEARCH │
└────────┘
├─ Searching for macOS Installer versions...
├─ Exported list as JSON: '/Library/Management/erase-install/mist-list.json'
└─ Found 21 macOS Installer(s) available for download

Identifier │ Name │ Version │ Build │ Size │ Date │ Compatible
───────────┼────────────────┼─────────┼─────────┼──────────┼────────────┼───────────
032-48342 │ macOS Ventura │ 13.2.1 │ 22D68 │ 12.56 GB │ 2023-02-20 │ True
032-35706 │ macOS Ventura │ 13.2 │ 22D49 │ 12.56 GB │ 2023-01-23 │ True
012-60271 │ macOS Ventura │ 13.1 │ 22C65 │ 12.23 GB │ 2023-01-11 │ True
012-93766 │ macOS Ventura │ 13.0.1 │ 22A400 │ 12.16 GB │ 2022-11-09 │ True
032-33828 │ macOS Monterey │ 12.6.3 │ 21G419 │ 12.41 GB │ 2023-01-31 │ True
032-12843 │ macOS Monterey │ 12.6.2 │ 21G320 │ 12.40 GB │ 2023-01-11 │ True
012-90254 │ macOS Monterey │ 12.6.1 │ 21G217 │ 12.41 GB │ 2022-10-24 │ True
032-50519 │ macOS Big Sur │ 11.7.4 │ 20G1120 │ 12.42 GB │ 2023-02-15 │ True
032-33756 │ macOS Big Sur │ 11.7.3 │ 20G1116 │ 12.42 GB │ 2023-01-31 │ True
032-12833 │ macOS Big Sur │ 11.7.2 │ 20G1020 │ 12.42 GB │ 2023-01-11 │ True
012-90253 │ macOS Big Sur │ 11.7.1 │ 20G918 │ 12.42 GB │ 2022-10-24 │ True
012-08272 │ macOS Big Sur │ 11.6.6 │ 20G624 │ 12.42 GB │ 2022-05-24 │ True
002-77154 │ macOS Big Sur │ 11.6.5 │ 20G527 │ 12.42 GB │ 2022-04-11 │ True
002-65695 │ macOS Big Sur │ 11.6.4 │ 20G417 │ 12.45 GB │ 2022-02-17 │ True
002-57023 │ macOS Big Sur │ 11.6.3 │ 20G415 │ 12.44 GB │ 2022-01-26 │ True
002-42341 │ macOS Big Sur │ 11.6.2 │ 20G314 │ 12.44 GB │ 2022-01-14 │ True
002-23589 │ macOS Big Sur │ 11.6.1 │ 20G224 │ 12.43 GB │ 2021-12-01 │ True
071-78704 │ macOS Big Sur │ 11.5.2 │ 20G95 │ 12.45 GB │ 2021-08-18 │ True
001-68446 │ macOS Catalina │ 10.15.7 │ 19H15 │ 08.75 GB │ 2020-11-11 │ True
001-51042 │ macOS Catalina │ 10.15.7 │ 19H2 │ 08.75 GB │ 2020-09-24 │ True
001-36801 │ macOS Catalina │ 10.15.6 │ 19G2021 │ 08.75 GB │ 2020-08-12 │ True

Does nothing past listing the different builds. Seems to be in some sort of loop. Current OS on the computer is 11.4 and is an M1. I have no idea where to go beyond installing a previous version.

**Comment by grahampugh** [comment]
I hate to be that guy, but have you tried this after a restart, and have you tried it on another machine? I cannot troubleshoot each individual machine.

**Comment by Trikster-Online** [comment]
I tried this on multiple machines after a reboot. All of those machines I went back to v27 and moved them along. I will try the latest version and report back if the issue persists.

**Comment by grahampugh** [comment]
Close due to lack of response from original requester. Please try with 30.2.

**Comment by Trikster-Online** [comment]
I'm sorry, I was out on medical leave and only recently came back to work. The most recent version seems to work. Every now and then I still get a weird message on an erase and install that I have to update the OS on the Mac in question before I can do the erase and install... Those, unfortunately for me, I usually have to put in DFU mode to get the current OS on them.

**Comment by grahampugh** [comment]
Some people said that the message about having to update first is showing up on macOS 11.3 or older. I haven't tested it yet.

**Comment by Trikster-Online** [comment]
That is exactly where I am seeing it as well, but I have had it on a few macOS 11.4 as well.
