### ISSUE TITLE
erase-install (29.1) - Reboot Delay Message/Countdown Dialog

### ISSUE THREAD

**Issue by jlloydroberts** [grahampugh/erase-install#377]
**Describe the bug**
During the preparation phase in the --reinstall workflow a user dialog appears, letting the user know that the installer is being prepared. If the 'Ok' button is selected here then when the --rebootdelay initiates, a new dialog doesn't appear with the countdown in seconds to let the user know that a reboot is imminent.

**To Reproduce**

These are the parameters used when running the 'Update' script:
--move
--version=12.6.3
--current-user
--reinstall
--check-power
--power-wait-limit=180
--rebootdelay=280

We have a separate policy running prior to this using the same version of erase-install which caches the installer on the device.

This policy uses the below parameters:

--move
--version=12.6.3
--update

 - Please describe how the script was run. [e.g. Standalone via Terminal, in Jamf Policy from the uploaded pkg, in Jamf policy from uploaded script only, via another MDM provider]
 
The script is run in a JAMF policy from the uploaded script.

**Expected behavior**
I would expect that regardless of if a user selects 'Ok' in the preparation dialog, a new dialog would appear to show the rebootdelay in seconds, and to notify the user to save their work.

**Code/log output**
Log attached.

**Screenshots**
Screenshot attached. This is where I click the 'Ok' button.

**Environment:**
 - OS version [12.6.3]
 - erase-install version [29.1]

**Additional context**
[erase-install.log](https://github.com/grahampugh/erase-install/files/10918748/erase-install.log)
![Image (1)](https://user-images.githubusercontent.com/127291477/223679521-36244865-d0db-406b-8522-73046b6cabce.jpeg)

**Comment by grahampugh** [comment]
I cannot reproduce this. In my tests the reboot delay window does popup. Are you still seeing this?

**Comment by grahampugh** [comment]
Close due to lack of response from original requester.
