### ISSUE TITLE
[FR] To add progress bar during the Upgrading portion

### ISSUE THREAD

**Issue by gatroie** [grahampugh/erase-install#382]
When the installer is preparing before the reboot there percentage given in the log of how much its done.  Maybe use that value to create a progress bar to give the user an impression that something is still going on.

**Comment by grahampugh** [comment]
There _is_ a progress bar at this stage. Are you not seeing it? Make sure you are using the latest release.

**Comment by grahampugh** [comment]
Close due to lack of response from original requester.
