### ISSUE TITLE
--overwrite option not working

### ISSUE THREAD

**Issue by Rorzzer** [grahampugh/erase-install#384]
Hi Graham,

Seeing this issue again were the script will not obtain a valid installer and seems to ignore the --overwrite flag.
2019 Intel device currently on 12.6.1 running the 28.1 package and script via JAMF

<img width="839" alt="Screenshot 2023-03-22 at 11 32 29 am" src="https://user-images.githubusercontent.com/26126712/226772126-60143477-a072-47ad-9332-538c512ba50f.png">
<img width="456" alt="Screenshot 2023-03-22 at 11 32 59 am" src="https://user-images.githubusercontent.com/26126712/226772131-f92ddd34-ab2e-4e2d-a8a6-74d837a5c0c3.png">

**Comment by Rorzzer** [comment]
Just noticed the 29.1 update, let me try that and report back.

**Comment by grahampugh** [comment]
You might want to clear that legacy sparseimage if you're not getting any luck with 29.1.

**Comment by grahampugh** [comment]
Close due to lack of response from original requester.
