### ISSUE TITLE
[FR] - Set default input field to the Password field when --curent-user/--user is provided

### ISSUE THREAD

**Issue by carlashley** [grahampugh/erase-install#385]
Version: 29.1.

When using the `--current-user` or `--user jappleseed` flags, the UI for entering the password defaults to the username field, rather than defaulting to the password field; if at all possible, it would be preferable to default the text input field in these two circumstances to the password input field.

In the screenshot attached, the `--current-user` flag was passed, and the default input field selected is the Username field.
![Screenshot 2023-03-28 at 2 07 22 pm](https://user-images.githubusercontent.com/9841187/228125661-567f5211-f207-46b2-9b2c-db2323f97064.png)

If it's not possible to default to the password field, then well, that's that I guess :>

**Comment by grahampugh** [comment]
I've added an FR into swiftDialog as I don't see that this is currently an option.

**Comment by grahampugh** [comment]
I've had confirmation that this is not currently possible. Sorry!
