### ISSUE TITLE
Query for Big Sur Space requirements

### ISSUE THREAD

**Issue by mrmte** [grahampugh/erase-install#388]
I am looking at some old Big Sur machines and i was wondering the space requirement.

"macOS Big Sur requires around 45 GB spare drive space to perform an upgrade using startosinstall. If this space is not available, the user is informed via a dialog and the script ends."

Is that 45GB without the installer or with the installer? If it is without the installer i would need to bump up to something like 57GB in a script im working on.

Thanks

**Comment by grahampugh** [comment]
It's very difficult to obtain the exact requirement from Apple. In erase-install I check the available space before AND after downloading the installer. This approach is corroborated, perhaps, in this post from Charles Edge: https://krypted.com/mac-os-x/free-space-required-for-modern-macos-upgrades/ - he recommends around 56 GB.

**Comment by mrmte** [comment]
great thanks very much for that.
