### ISSUE TITLE
Seeing an issue on 27.2/27.3 with 13.3.1 upgrades

### ISSUE THREAD

**Issue by GabeShack** [grahampugh/erase-install#389]
We are running the following:
/Library/Management/erase-install/erase-install.sh --reinstall --version=13.3.1 --current-user --check-power --update
which i had just changed to 13.3.1 from 13.1
The log is showing that is sees 13.3.1 but the error says its not a valid update file?  I bolded/italicised the line below where it still shows 13.3.1 on apples servers.  We are using the older version of erase install due to some machines in our fleet still running before MacOS 11

   [erase-install] Caffeinating this script (pid=1512)
   [check_free_space] OK - 969 GB free/purgeable disk space detected
   [check_power_status] OK - AC power detected
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Running on architecture i386
   [erase-install] Opening jamfHelper download message (language=en)
   [check_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [check_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Checking that selected version 13.3.1 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --version 13.3.1 --validate

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : iMac17,1

Board ID         : Mac-65CE76090165799A
OS Version       : 12.6.3
Build ID         : 21G419

 #  ProductID       Version    Build    Post Date   Title                          
 1  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
 2  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 3  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 4  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
 5  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
 6  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 7  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 8  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 9  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
10  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
11  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
12  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
13  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
14  071-78704       11.5.2     20G95    2021-08-18  macOS Big Sur                  
15  002-23589       11.6.1     20G224   2021-12-01  macOS Big Sur                  
16  002-42341       11.6.2     20G314   2022-01-14  macOS Big Sur                  
17  002-57023       11.6.3     20G415   2022-01-26  macOS Big Sur                  
18  002-65695       11.6.4     20G417   2022-02-17  macOS Big Sur                  
19  002-77154       11.6.5     20G527   2022-04-11  macOS Big Sur                  
20  012-08272       11.6.6     20G624   2022-05-24  macOS Big Sur                  
21  012-60271       13.1       22C65    2023-01-11  macOS Ventura                  
22  032-12843       12.6.2     21G320   2023-01-11  macOS Monterey                 
23  032-12833       11.7.2     20G1020  2023-01-11  macOS Big Sur                  
24  032-35706       13.2       22D49    2023-01-23  macOS Ventura                  
25  032-33756       11.7.3     20G1116  2023-01-31  macOS Big Sur                  
26  032-33828       12.6.3     21G419   2023-01-31  macOS Monterey                 
27  032-50519       11.7.4     20G1120  2023-02-15  macOS Big Sur                  
28  032-48342       13.2.1     22D68    2023-02-20  macOS Ventura                  
29  002-75541       13.3       22E252   2023-03-27  macOS Ventura                  
30  032-63749       12.6.4     21G526   2023-03-27  macOS Monterey                 
31  032-63762       11.7.5     20G1225  2023-03-27  macOS Big Sur                  
**_32  032-66588       13.3.1     22E261   2023-04-07  macOS Ventura_**                  
33  032-71575       12.6.5     21G531   2023-04-10  macOS Monterey                 
34  032-71551       11.7.6     20G1231  2023-04-10  macOS Big Sur                  

A valid installer for version 13.3.1 is not available for this computer. Run again without --version argument to select a valid build to download.

   [run_installinstallmacos] No disk image found. I guess nothing got downloaded.

   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1047:  1527 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$

   [erase-install] attempting to terminate the 'jamfHelper' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1047:  1551 Terminated: 15          "$jamfHelper" -windowType hud -windowPosition ul -title "${!dialog_dl_title}" -alignHeading center -alignDescription left -description "${!dialog_dl_desc}" -lockHUD -icon "$dialog_dl_icon" -iconSize 100

   [finish] Script exit code: 1

**Comment by grahampugh** [comment]
Erase-install has determined that 13.3.1 is not a valid build for that computer. I suggest that you run erase-install.sh --list on that computer. It will show you which builds are valid. 

Or just remove the version parameter and it will automatically choose the latest valid build for the computer.

**Comment by GabeShack** [comment]
Ah....ty....2015 iMac wont take ventura.  Makes sense.
