### ISSUE TITLE
[FR] Restrict SwiftDialog version to 2.2 on macOS 11

### ISSUE THREAD

**Issue by grahampugh** [grahampugh/erase-install#392]
**Is your feature request related to a problem? Please describe.**
SwiftDialog 2.3+ will only work on macOS 12 and above. In order to provide N-3 support, which is essential for erase-install moving forward, we need to ensure that we use swiftDialog 2.2. Currently erase-install will download 2.1 (soon 2.2) if it is not present, but if a newer one was present it would not attempt to downgrade it. 

**Describe the solution you'd like**
We should continue to specify version 2.2 for downloads and in the package, and if macOS is version 11 we should also ensure that version 2.2 gets installed even if 2.3+ is there.

**Additional context**
Note that there should not be a big problem here since it only affects macOS 11 and there should be few circumstances where SwiftDialog 2.3 would have ended up on macOS 11.

**Comment by grahampugh** [comment]
This should be addressed with v30.0.

**Comment by grahampugh** [comment]
How did you install? The package does contain 2.3.2 but when you run the script on macOS 11 it should delete it and download the older version.

**Comment by Samstar777** [comment]
I am using Erase-Install-31.0.Pkg through Jamf Pro with command in files and process </Library/Management/erase-install/erase-install.sh --os Sonoma --reinstall --current-user --confirm>

**Comment by grahampugh** [comment]
And did it remove 2.3.2 and download 2.2.1? Can you ship me the logs if not?

**Comment by Samstar777** [comment]
It is not downgrading to v2.2.1, in fact i had installed v2.2.1 and the script upgraded the same to v2.3.2
[erase-install.log](https://github.com/grahampugh/erase-install/files/12796253/erase-install.log)

**Comment by grahampugh** [comment]
Thanks, I'll try and spin up a Big Sur VM when I get a chance.

**Comment by allanp81** [comment]
While I haven't figured out exactly why, it seems that it might be line 252 that's the problem, possibly because it can't read the version properly?

**Comment by grahampugh** [comment]
This should be fixed now, please try the latest v31.0 that I pushed just now.
