### ISSUE TITLE
macOS Ventura is not compatible with this Mac

### ISSUE THREAD

**Issue by JamieSmithJAX** [grahampugh/erase-install#396]
Suddenly seeing a strange issue where I run through my workflow, Ventura 13.4 downloads as normal and starts the install, however the process never finishes, essentially leaving machine in a state where it says Preparing Ventura for Install until I hard power it down.

After looking at the machine, I tried to launch the Ventura installer manually and was greeted with"macOS Ventura is not compatible with this Mac".  The issue is it is the hardware is absolutely compatible, but suddenly I am seeing this error on every system I try to upgrade (Intel, M1 and M2).  If I download an installassistant.pkg for Ventura 13.4 I see no issues, so it seems like downloaded OS by the erase-install process has some issues.  Any idea?
![Screenshot 2023-06-07 at 3 11 00 PM](https://github.com/grahampugh/erase-install/assets/67976563/92ee6f9a-93f1-4eeb-bce9-1ea60275275c)

my command line is /Library/Management/erase-install/erase-install.sh --os=13 --update --reinstall

I just noticed this issue start happening today, I have previously updated some of this same hardware using the exact command line to Ventura 13.4 last week

**Comment by grahampugh** [comment]
Please see v29.2 which I released today and addresses this very issue.
