### ISSUE TITLE
Having issue while running in jamf pro

### ISSUE THREAD

**Issue by praveenkumar2406** [grahampugh/erase-install#401]
**Describe the bug**
I am running the policy with erase install package 

while upgrading the to ventura the policy re-run and searching for installer 

i am using —reinstall — update and some other parameter to check the power

I doesn’t want to run the policy again once it gets restart

please suggest me 

Thank you

**Comment by grahampugh** [comment]
If you are running the script from a recurring policy, you have to scope the policy appropriately to exclude the relevant Operating System Version to avoid it running repeatedly. 

You also need to make sure that you run a recon on startup to make sure that the upgrade is recorded back to Jamf when it's complete.

**Comment by praveenkumar2406** [comment]
I have another issue like after successfull installtion it shows installer package with ?(question mark). 

I have removed it from launchpad. But I cannot do that manually for nearly 200 laptop? So is there way to remove from script? I think it is stored in database some where.

**Comment by grahampugh** [comment]
What do you mean by "it shows installer package with ?(question mark)"? 

What is showing this, and where?

**Comment by grahampugh** [comment]
I still advise to set a policy to Update Inventory on start up.
