### ISSUE TITLE
Problem downloading installers on 13.5

### ISSUE THREAD

**Issue by grahampugh** [grahampugh/erase-install#421]
Hi Graham, I have noticed since the upgrade to 13.5 I can no longer download compatible Ventura Installs using erase install (as per the previous bug) I have tried both 29.2 and 30 with the same result.  I have noticed that the installer in the Applications folder has a line through it and when trying to run standalone it is broken.

Weirdly I can still use 29.2 to upgrade from Ventura 13.4.1 to 13.5.  Any advice would be useful.

_Originally posted by @NikThanki in https://github.com/grahampugh/erase-install/issues/320#issuecomment-1651753677_

**Comment by NikThanki** [comment]
Mist CLI  has been updated but now noticing I am being offer 13.6 and I have not put the switch in to allow betas?  Any one else seeing this at all?

**Comment by grahampugh** [comment]
@NikThanki that's a different issue, please don't mix up different problems in the same issue. However, I have just also come across this, I'll create a new issue for it and I have a fix in progress.

**Comment by grahampugh** [comment]
Are you by any chance testing this on a VM? What's the output of `./erase-install.sh --list`?

**Comment by dornoam41** [comment]
I'm having the same issue as well.
Please review the attached screenshots.
![Screenshot 2023-08-28 at 11 01 53](https://github.com/grahampugh/erase-install/assets/107796353/642647fb-d491-4bee-b125-7df8c5e65277)
![Screenshot 2023-08-28 at 11 01 07](https://github.com/grahampugh/erase-install/assets/107796353/3d431777-6f3f-4f28-bcf2-761ee3fe29df)
![Screenshot 2023-08-28 at 11 00 58](https://github.com/grahampugh/erase-install/assets/107796353/2f73ac1f-66a5-4dbe-9150-df37e8944881)
![Screenshot 2023-08-27 at 14 48 29](https://github.com/grahampugh/erase-install/assets/107796353/7539d80a-5c32-4153-b8dc-21148077e04b)

**Comment by grahampugh** [comment]
I'm going to close this issue because people are posting different things that require their own issue. @dornoam41 if you want to create an issue that's related to running erase-install, please create a new one with full log output (partial screenshots are not useful). If it's to do with running mist-cli directly, then please open an issue on the mist-cli repo.
