### ISSUE TITLE
erase-install doesn't seem to install

### ISSUE THREAD

**Issue by smithjw** [grahampugh/erase-install#43]
Hey Graham, I'm playing around with `erase-install` and running into a weird issue where it doesn't seem to actually install the OS (trying to upgrade a VM running 10.15.7 to 11.0.1). The Script runs fine from Jamf initially when used to cache the installer onto the system but then when running a followup policy with the `--reinstall` flag no JamfHelper and no install proceeded :(.

This is the output that I get from running the script (identical whether I run via a Self Service Policy or via the script on the VM itself.

```
admin@AppTesting ~ % sudo bash /Library/Management/erase-install/erase-install.sh --reinstall
Password:

   [erase-install] Script execution started: Mon 30 Nov 2020 15:51:03 AEDT
   [erase-install] Caffeinating this script (pid=5037)
   [erase-install] Looking for existing installer
   [find_existing_installer] Installer found at /Applications/Install macOS Big Sur.app.
   [check_installer_is_valid] Checking validity of /Applications/Install macOS Big Sur.app.
   [check_installer_is_valid] 20B31 >= 19H2 so valid.

   [erase-install] WARNING! Running /Applications/Install macOS Big Sur.app with reinstall option

   [free_space_check] OK - 38898428 KB free disk space detected
   [erase-install] Opening jamfHelper full screen message (language=en)
WARNING: "--allowremoval" is ignored in macOS 11.0 and greater. Please remove it from your invocation.
/Library/Management/erase-install/erase-install.sh: line 731:  5067 Killed: 9               "$installmacOSApp/Contents/Resources/startosinstall" "${install_args[@]}" --agreetolicense --nointeraction "${install_package_list[@]}"
   [erase-install] 'jamfHelper' ended
```

**Comment by grahampugh** [comment]
@smithjw not sure what's going on there. Something is killing the script. 

I've pushed a new version (https://github.com/grahampugh/erase-install/releases/tag/v0.16.0b3) - could you test it with this in case any of the changes I've pushed make any difference?

**Comment by grahampugh** [comment]
Closing the issue as no response to my question. Feel free to reopen if you are seeing the same issue on the latest version.
