### ISSUE TITLE
[FR] Error out of script if download fails due to space

### ISSUE THREAD

**Issue by charliwest** [grahampugh/erase-install#430]
When run via jamf (and other providers) the script exits "cleanly", but this then means we can't see that as admins as it shows "Completed".
It would be great if there was an option for it to exit with a reason if the download fails. 
As I cache the installer before I run anything further on devices this would be really helpful.

**Comment by grahampugh** [comment]
the script already is set to `exit 1` if the check_free_space function fails. 

How are you running the script, out of interest? If you're running from a Run Command it will always exit 0 regardless of the outcome of the script. To get a real exit code you need to use a second script to run erase-install, such as erase-install-launcher.sh (included in this repo), or a simpler one such as we use: https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/main/Scripts_Tools/macOS-upgrade-ventura.zsh
