### ISSUE TITLE
[FR] Add "minimum power" option

### ISSUE THREAD

**Issue by PhillyPhoto** [grahampugh/erase-install#455]
**PLEASE NOTE THAT FEATURE REQUESTS ARE ONLY CONSIDERED AGAINST v.28.0+**

**Is your feature request related to a problem? Please describe.**
We should be able to include the "--check-power" flag but have it automatically continue if the battery percentage is above a minimum amount (kind of like the free space check).

**Describe the solution you'd like**
Have a sub-function of --check-power (maybe something like "--min-power=40") that checks if the battery is at least a certain percent and will automatically continue even if the machine isn't plugged in. Their should probably be a hard lower limit that it won't allow the upgrade to run at (i.e. 20% battery).

**Describe alternatives you've considered**
N/A

**Additional context**
Knowledgeable users can disconnect the power once prompted for their credentials on ARM Macs and it will let them essentially cancel the upgrade from being pushed to their Macs. This has dragged out our deployment from completing.

**Comment by grahampugh** [comment]
It's not a bad idea.m, though I fear your knowledgeable users will always find a way. Sometimes these things are HR issues more than technical ones. 

You could of course set the --power-wait-limit to a really long time.

**Comment by grahampugh** [comment]
This is addressed in v35.0. Thanks!
