### ISSUE TITLE
macOS Sonoma icon is missing during the Upgrading OS

### ISSUE THREAD

**Issue by sushanth486** [grahampugh/erase-install#466]
macOS Sonoma icon is missing during the Upgrading OS.  See screenshot below. 

Tested with MacBook Pro 13 inch M2  2022

Any suggestions please ? Not sure if this bug or some other issues ... 

<img width="1440" alt="Screenshot 2023-11-03 at 8 01 23 PM" src="https://github.com/grahampugh/erase-install/assets/128150536/2a0fb6ce-e9ab-4686-843f-ae50b0d1bb34">

**Comment by grahampugh** [comment]
Please resubmit this issue answering all the questions in the template.
