### ISSUE TITLE
OS Version selection no longer "automatic"

### ISSUE THREAD

**Issue by fridomac** [grahampugh/erase-install#47]
From 0.16b2 onwards, if I run the script through a Jamf policy (or by hand), it no longer selects the OS Version to download in installinstallosx.py automatically. The script is waiting on an input from the user on which Version to select, so it hangs indefinitely.
Tested on a stock macOS 11. 0.16b1 does work, though.

Bye, Fridolin.

**Comment by grahampugh** [comment]
Hi Frido
Thanks for the heads up. I think it's fixed now. I've deleted the previous betas so go checkout v0.16.0b4. 

Cheers
Graham

**Comment by grahampugh** [comment]
Now pushed to full release - 0.16.0
