### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mrmte** [grahampugh/erase-install#478]
**Describe the bug**
Hi, I’m working n a mechanism to detect with Jamf  reporting  which machine fail the process and have a question. I want to touch creating a file if it was interrupted or unsuccessful on an upgrade. Would I need to do this Line 2521  in the terminate function 143 or line 3514 where it exits with 42?

**To Reproduce**
 - If applicable, please provide the full command used when running the script.
 - Please describe how the script was run. [e.g. Standalone via Terminal, in Jamf Policy from the uploaded pkg, in Jamf policy from uploaded script only, via another MDM provider]
 
**Expected behavior**

**Code/log output**
Please supply the **full command used**, and if applicable, add **full output** from Terminal or from `/var/log/erase-install.log`. Don't post a partial log - I need the whole thing. Either upload the log as a file, or paste the output in a code block like this:

```
your log goes here between triple backticks! Make sure you remove any personal information!
```

**Screenshots**

**Environment (please complete the following information):**
 - OS version [e.g. 12.0.1]
 - erase-install version [e.g. 24.0] - please upgrade to the latest version before submitting a bug report.

**Additional context**

**Comment by grahampugh** [comment]
Hi, this doesn't look like a bug. If you're after some support please use the Discussions section or post in the Mac Admins Slack #eraseinstall channel.

**Comment by mrmte** [comment]
I worked it out. Sorry forgot to close it
