### ISSUE TITLE
[BUG] Downloading installer then script quits at approx 5% if Zoom call is in progress

### ISSUE THREAD

**Issue by neil-bh** [grahampugh/erase-install#486]
**Describe the bug**
It wasn't obvious at first, however while working remotely with a colleague in order to setup Erase-Install, we were using a Zoom session to work collaboratively using screen sharing.  Each time we tried to execute a typical Erase-Install command, we could see in the logs that it started downloading the installer, and then at around 5% it would just stop without warning or error.  It was only when my colleague independently tried (i.e. while we were no longer in a Zoom session), that the download was happy to go all the way through to 100% and proceed to the next step.

**To Reproduce**
 - If applicable, please provide the full command used when running the script.
`/Library/Management/erase-install/erase-install.sh --os 14 --erase --fs --confirm --check-power`
Launch a Zoom session and then execute the above command, the process will start and shortly after starting, the swift dialog will close.  On looking at the log, you can see the download progress gets as far as 4% or 5%, this may vary, but is consistent.  When no Zoom session is active, the download will progress to 100% and continue to the next step.

 - Please describe how the script was run. [e.g. Standalone via Terminal, in Jamf Policy from the uploaded pkg, in Jamf policy from uploaded script only, via another MDM provider]
Executed via Jamf Policy. 2 payloads... Package, and Files and Processes/Execute Command.  The command is as written above.
 
**Expected behavior**
Expected to work as is, i.e. download the latest compatible version of macOS Sonoma 14.x, wipe the disk and install, with a power and confirmation check.

**Code/log output**
I've not provide a log output at this stage, since I believe this is already understood given that v33.0 addresses this issue somewhat.  However logs can be provided if needed to follow up.

**Environment (please complete the following information):**
 - OS version
 14.1
 - erase-install version
 32.0

**Additional context**
I noticed that in version **33.0** it mentions that Zoom can be checked if running by using `--check-activity`.  So I have installed v33.0 and included the --check-activity, and the the behaviour is working as designed, i.e. the logs show that the application was detected and the script gracefully ends - although no visual alerts are shown to the user.

My question to ask is are you already aware that Zoom quits the script during the download because it would seem you've implemented a check-activity.  Or was this check-activity in place to simply prevent users that were in Zoom calls from getting kicked off in mid conversation (assuming an MDM is performing an automated erase-install action)? If it is the latter, then I hope I have made you aware that the Zoom app has this unexpected impact on the process.

I'd be happy to provide any further information if required.

**Comment by grahampugh** [comment]
Hi Neil

Perhaps unsurprisingly I have not tried to run the script while in a Zoom call, certainly not to try and erase 😀

You've stated that the download bombs out. I'm curious as to whether it's mist-cli or erase-install bombing out. If you could provide some logs that would be helpful. 

The new option to quit the script during a zoom session was a pull request from a collaborator who uses the script in a "forced" mode so doesn't want to interrupt meetings to enforce updates - as far as I know, they had no knowledge of Zoom causing the script (or mist) to fail.

**Comment by grahampugh** [comment]
Addressed in v33.0
