### ISSUE TITLE
Signature verification of the os installer

### ISSUE THREAD

**Issue by kenchan0130** [grahampugh/erase-install#50]
If we install using `installinstallmacos.py`, there is a possibility that an incorrect OS will be installed, for example, if the catalog has been modified.
This is why we believe that we should check the signature of the binary and application.

This is the same idea as Gatekeeper for macOS.

Is it possible to add this feature?

**Comment by grahampugh** [comment]
Adding code signature verification would significantly lengthen the script, but I guess would be possible in terms of the application, although I would be surprised if there aren't checks built into startosinstall for that. 

Which binary do you envisage checking the signature of?

And when you say the "incorrect" version, do you mean a manipulated installer or just a different version?

**Comment by grahampugh** [comment]
I'm not going to leave this issue open as I don't intend to figure it out it myself, but feel free to submit a PR if you wish to see this implemented.
