### ISSUE TITLE
[FR] Add password pop-up timeout

### ISSUE THREAD

**Issue by PhillyPhoto** [grahampugh/erase-install#501]
**PLEASE NOTE THAT FEATURE REQUESTS ARE ONLY CONSIDERED AGAINST v.28.0+**

**Is your feature request related to a problem? Please describe.**
Yes, people could ignore the password prompt window and the script will run forever, causing issues for MDMs like Jamf where other policies may be waiting to run.

**Describe the solution you'd like**
Update the ask_for_credentials() function to include the following in "dialog_args":
        "--timer"
        "300" 
(or some other time interval)

**Describe alternatives you've considered**
N/A

**Additional context**
If max_password_attempts is set to "infinite" the user will just keep getting prompted for their creds. However, they can just ignore the dialog. Having it time out would bring it back in their view again and if there are issues they would be more likely to raise the issue sooner. This would also ensure if someone does use a password that isn't accepted for whatever reason but stop before the max attempts is reached, this would ensure the max attempts does eventually get reached and allow the script to fail in a timely manner.

**Comment by grahampugh** [comment]
This is addressed in v35.0. Thanks!
