### ISSUE TITLE
[BUG?] Dont delete Logs after CleanUp

### ISSUE THREAD

**Issue by mazeo2112** [grahampugh/erase-install#502]
Hey,

not sure if BUG or FR, but I also tried to edit the script to avoid deleting the logs after successfully upgraded, but with the cleanup-after trigger.

I tried to replace Log directory to /LIbrary/Logs/erase-install, but also in this place the logs will be deleted after Upgrade.
I cant find the Line in wich this is provided that the $logdir will always be deleted.

Can you guys help me with that?

Thanks in advance and great jobs on this tool!
Maze

**Comment by grahampugh** [comment]
Hi there, that should not be happening unless you are using the --cleanup-after-use option?

**Comment by mazeo2112** [comment]
Hey, yes we do, because we want to clear /Library/Management after Upgrade, but still want to have the logs.

**Comment by grahampugh** [comment]
So that is not a bug, it's working as intended. 

But you could use a --postinstall-command flag to copy the log to another location, so long as the permissions are correct. /Users/Shared for example.

**Comment by mazeo2112** [comment]
Many Thanks!

great Idea!
