### ISSUE TITLE
# default Finy My wait timer to 60 seconds

### ISSUE THREAD

**Issue by AirBookMac** [grahampugh/erase-install#514]
https://github.com/grahampugh/erase-install/blob/d24309b60a214c3eea7b4f35846af49c232d0ac9/erase-install.sh#L141

# default **Find** My wait timer to 60 seconds 

instead of

# default **Finy** My wait timer to 60 seconds

**Comment by grahampugh** [comment]
Good spot :)

**Comment by grahampugh** [comment]
Fixed in 36.0
