### ISSUE TITLE
Incorrect exit code on line 635?

### ISSUE THREAD

**Issue by wegotoeleven** [grahampugh/erase-install#52]
Lines 633 to 635; as this condition of the if statement occurs when a disk image hasn't been downloaded by installinstallmacos, shouldn't it technically be considered an error and therefore error out with an exit code of > 0 on line 635? 

Basically, I'm seeing a few macOS upgrade policies that use `erase-install` finish with a "Complete" status, rather than "Failed" status, when the Mac doesn't upgrade due to a failed installer.app download.

**Comment by grahampugh** [comment]
Sounds sensible, I'll take a look :)

**Comment by wegotoeleven** [comment]
<3

**Comment by grahampugh** [comment]
I can't remember when I changed this, but I did :)
