### ISSUE TITLE
[BUG] Manual restart prevents upgrade from completing

### ISSUE THREAD

**Issue by lewis-edward-svvsd** [grahampugh/erase-install#528]
**Describe the bug**
It seems that if a restart is triggered manually during the "rebootdelay" prompt the upgrade does not process

**To Reproduce**
- Upgrading from 14.6.1 to 15.0.1
- Jamf Pro Policy from Self Service
- /Library/Management/erase-install/erase-install.sh --current-user --update --ffi --reinstall --cleanup-after-use --os=15 --rebootdelay=60 --confirm --check-power --power-wait-limit=300 --no-fs
- Restart the computer from the Apple menu while the reboot delay prompt is up
- Results in upgrade not running and having to kick the entire process off again 
 
**Expected behavior**
Should this be happening? It seems that a manual restart should not prevent the upgrade. Another option is the report delay prompt shows "restart now" instead of a greyed out "Okay"

**Code/log output**

**Screenshots**

**Environment (please complete the following information):**
 - 14.6.1 to 15.0.1
 - erase-install 36.0 

**Additional context**
I am not sure if a bug, or me just misunderstanding how the reboot delay works.

**Comment by grahampugh** [comment]
Hi, the rebootdelay option is baked into startosinstall (not part of the erase-install code), so there's nothing I can do to change its behaviour. You might want to open a feedback with Apple on that one.
