### ISSUE TITLE
Erase to the same OS results in build valid check error? (10.15)

### ISSUE THREAD

**Issue by martyjw** [grahampugh/erase-install#53]
Hey Graham,

I'm attempting to erase a workstation running 10.15.7 to the same OS (10.15.x) via the param --os=10.15. Running the command as below the following output is received where it stops at '[check_installer_is_valid]' because the build number no longer matches.

> sudo /Library/Management/erase-install/erase-install.sh --erase --os=10.15 --test-run

Following installinstallmacos.py which downloads build 19H15 (expected)....

```
   [erase-install] v0.17.2 script execution started: Tue Jan 12 11:13:51 GMT 2021
   [erase-install] Caffeinating this script (pid=10596)
   [erase-install] Looking for existing installer
   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_10.15.7-19H15.sparseimage.
/dev/disk3              GUID_partition_scheme          
/dev/disk3s1            EFI                            
/dev/disk3s2            Apple_HFS                       /Volumes/Install_macOS_10.15.7-19H15
   [check_installer_is_valid] Checking validity of /Volumes/Install_macOS_10.15.7-19H15/Applications/Install macOS Catalina.app.
Unmount failed for /Volumes/Shared Support
   [check_installer_is_valid] 19H11 < 19H15 so not valid.
   [erase-install] Installer is at: /Volumes/Install_macOS_10.15.7-19H15/Applications/Install macOS Catalina.app
   [erase-install] Mounted installer will be unmounted: /Volumes/Install_macOS_10.15.7-19H15/Applications/Install macOS Catalina.app
Volume Install_macOS_10.15.7-19H15 on disk3s2 force-unmounted
   [erase-install] Cleaning working directory '/Library/Management/erase-install/content'
   [erase-install] 'caffeinate' ended
```
I've also tried caching the .dmg to /Library/Management/erase-install which results in the same error. I'm unsure why 'Unmount failed for /Volumes/Shared Support' is received. I presume [check_install_is_valid] assumed the current OS build is ahead of what can be downloaded.

erase-install.sh 0.17.2

**Comment by grahampugh** [comment]
I have to check, but I think this is because macOS Catalina (and older) installers do not have a SharedSupport.dmg in them from which the script can extract the real Build Version. In those cases I have to fall back to the `DTSDKBuild` value in the  `Info.plist` file, which is sometimes a few numbers older than the actual build version. 

The script tries to prevent failed installs by validating the build, but when it's not possible to compare exact build numbers, this makes it difficult. (This is solved with Big Sur installers by the way).

I think I'll have to loosen the comparison and hope it doesn't cause more failures, i.e. only compare the first three characters of the build version (`19H`).

I'll try and test it and let you know if it works.

**Comment by grahampugh** [comment]
Can you test out v0.17.3 Pre-release please? I've loosened the version check to point release, so any 10.15.7 should go ahead and run on a 10.15.7 system, rather than just the exact Build Version (which reports incorrectly pre Big Sur).

**Comment by martyjw** [comment]
From a quick check with --test-run that's looking better! 👍  

`   [check_installer_is_valid] Checking validity of /Volumes/Install_macOS_10.15.7-19H15/Applications/Install macOS Catalina.app.
   [check_installer_is_valid] Using DTSDKBuild value from Info.plist
   [check_installer_is_valid] Warning: 19H11 < 19H15 - find newer installer if this one fails
   [check_installer_is_valid] Installer: 19H11 ; System: 19H15 : valid build.'

**Comment by grahampugh** [comment]
The question will be whether an actually older build of the same point release successfully installs or not. But hopefully this will be a rare case, and is solved in Big Sur anyway since there is a method to get the actual build version in the new SharedSupport.dmg.

**Comment by martyjw** [comment]
Agree that should be a rare case (not one I've tried previously). Thanks for your help!
