### ISSUE TITLE
Not working on M1 Mac mini

### ISSUE THREAD

**Issue by n0brainer** [grahampugh/erase-install#57]
Not sure if this is expected, and I realized I tried the dev branch 17.3, but I tried to run it to reload on a lab M1 Mac mini and it did fail with an error obtaining installer.

` Script result: 
   [erase-install] v0.17.3 script execution started: Tue Jan 19 08:45:44 PST 2021
   [erase-install] Caffeinating this script (pid=27150)
   [erase-install] Looking for existing installer
   [find_existing_installer] No valid installer found.
   [get_user_details] macadmin has Secure Token
   [check_password] Success: the password entered is the correct login password for macadmin.
   [erase-install] Starting download process
   [erase-install] Opening jamfHelper download message (language=en)
   [get_installinstallmacos] Making working directory at /Library/Management/erase-install
   [get_installinstallmacos] Downloading installinstallmacos.py...
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [run_installinstallmacos] Getting current production version

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir=/Library/Management/erase-install --ignore-cache --raw --auto 
Could not replicate http://swcdn.apple.com/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/InstallAssistantAuto.smd: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/InstallAssistantAuto.smd', u'--compressed', 'http://swcdn.apple.com/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/InstallAssistantAuto.smd']' returned non-zero exit status 55
Could not replicate https://swdist.apple.com/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/001-15219.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/001-15219.English.dist', u'--compressed', 'https://swdist.apple.com/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/001-15219.English.dist']' returned non-zero exit status 16
Could not replicate http://swcdn.apple.com/content/downloads/61/24/001-57224/0o1xetys5n505gocjsil5qo0p4kg939elb/InstallAssistantAuto.smd: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/61/24/001-57224/0o1xetys5n505gocjsil5qo0p4kg939elb/InstallAssistantAuto.smd', u'--compressed', 'http://swcdn.apple.com/content/downloads/61/24/001-57224/0o1xetys5n505gocjsil5qo0p4kg939elb/InstallAssistantAuto.smd']' returned non-zero exit status 55
Could not replicate http://swcdn.apple.com/content/downloads/01/28/061-86291-A_JPEIWIOZES/enpozvvbmj3mj2dhulhevlt8b429qd5kw0/InstallAssistantAuto.smd: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/01/28/061-86291-A_JPEIWIOZES/enpozvvbmj3mj2dhulhevlt8b429qd5kw0/InstallAssistantAuto.smd', u'--compressed', 'http://swcdn.apple.com/content/downloads/01/28/061-86291-A_JPEIWIOZES/enpozvvbmj3mj2dhulhevlt8b429qd5kw0/InstallAssistantAuto.smd']' returned non-zero exit status 55
Could not replicate http://swcdn.apple.com/content/downloads/10/06/001-36801-A_9MBEQ97Z9M/672a1q4u8978ize3s15ygivp2dqwmk10qb/InstallAssistantAuto.smd: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/10/06/001-36801-A_9MBEQ97Z9M/672a1q4u8978ize3s15ygivp2dqwmk10qb/InstallAssistantAuto.smd', u'--compressed', 'http://swcdn.apple.com/content/downloads/10/06/001-36801-A_9MBEQ97Z9M/672a1q4u8978ize3s15ygivp2dqwmk10qb/InstallAssistantAuto.smd']' returned non-zero exit status 55
Could not replicate https://swdist.apple.com/content/downloads/00/55/001-86606-A_9SF1TL01U7/5duug9lar1gypwunjfl96dza0upa854qgg/001-86606.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/00/55/001-86606-A_9SF1TL01U7/5duug9lar1gypwunjfl96dza0upa854qgg/001-86606.English.dist', u'--compressed', 'https://swdist.apple.com/content/downloads/00/55/001-86606-A_9SF1TL01U7/5duug9lar1gypwunjfl96dza0upa854qgg/001-86606.English.dist']' returned non-zero exit status 35

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : Macmini9,1

Device ID        : J274AP
OS Version       : 11.1
Build ID         : 20C69

 #  ProductID       Version    Build    Post Date   Title                          
Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 1299, in <module>
    main()
  File "/Library/Management/erase-install/installinstallmacos.py", line 931, in main
    elif device_id and product_info[product_id]["DeviceIDs"]:
KeyError: u'DeviceIDs'
   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.
   [erase-install] 'jamfHelper' ended `

**Comment by grahampugh** [comment]
Hi @n0brainer, that looks more like network issues to me. Try one of those curl commands manually.

**Comment by n0brainer** [comment]
yeah, you're right, bad AV app was blowing it up.  thank you!
