### ISSUE TITLE
Error: failed to authorize for installation. Provide a password with --stdinpass or --passprompt.

### ISSUE THREAD

**Issue by foolsdragon** [grahampugh/erase-install#63]
Environment: M1 MacBook Pro running macOS 11.1

Download of the OS completes, but it looks like maybe the "--erase" switch requires a password now, even if run as an administrator.

This is the error returned:
Error: failed to authorize for installation. Provide a password with --stdinpass or --passprompt.

Usage for startosinstall under 11.2:

Usage: startosinstall

Arguments
--license, prints the user license agreement only.
--agreetolicense, agree to the license you printed with --license.
--rebootdelay, how long to delay the reboot at the end of preparing. This delay is in seconds and has a maximum of 300 (5 minutes).
--pidtosignal, Specify a PID to which to send SIGUSR1 upon completion of the prepare phase. To bypass "rebootdelay" send SIGUSR1 back to startosinstall.
--installpackage, the path of a package (built with productbuild(1)) to install after the OS installation is complete; this option can be specified multiple times.
--eraseinstall, (Requires APFS) Erase all volumes and install to a new one. Optionally specify the name of the new volume with --newvolumename.
--newvolumename, the name of the volume to be created with --eraseinstall.
--preservecontainer, preserves other volumes in your APFS container when using --eraseinstall.
--forcequitapps, on restart applications are forcefully quit. This is the default if no users are logged in.
--usage, prints this message.
--user, an admin user to authorize installation.
--passprompt, collect a password for authorization with an interactive prompt.
--stdinpass, collect a password from stdin without interaction.
--reducedsecurity, configure target volume's security policy as Reduced Security (will prompt for authorization after reboot).
--cloneuser, Copy account settings for the owner provided with --user when installing to a new volume.

**Comment by grahampugh** [comment]
Please ensure you are using the latest version of erase-install.sh.

**Comment by foolsdragon** [comment]
Heh, I knew there would be something! Thanks Graham.

**Comment by laoyaoer** [comment]
@foolsdragon Hi, I ran into the same issue. Have you worked it out and how did you make it? Thanks.

**Comment by grahampugh** [comment]
@laoyaoer make sure you have the latest version of the script. And you have to run the script when a user is logged in, because you now get a dialog to enter the password (and username if you don't use the --currentuser option).
