### ISSUE TITLE
Failing to Detect Big Sur 11.2.1 (20D74)

### ISSUE THREAD

**Issue by Ferventmonkey** [grahampugh/erase-install#64]
This looks like it is potentially an issue with installinstallmacos.py. However, I noticed that erase-install.sh appears to have the --fetch-full-installer flag disabled. 

Error log for reference:

Script result: 
   [erase-install] v0.17.3 script execution started: Thu Feb 11 11:23:20 CST 2021
   [erase-install] Caffeinating this script (pid=3925)
   [erase-install] Looking for existing installer
   [find_existing_installer] No valid installer found.
   [erase-install] Starting download process
   [erase-install] Opening jamfHelper download message (language=en)
/Library/Application Support/JAMF/tmp/erase-install.sh: line 853: [: 11.2.1: integer expression expected
   [get_installinstallmacos] Making working directory at /Library/Management/erase-install
   [get_installinstallmacos] Downloading installinstallmacos.py...
   [get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [run_installinstallmacos] Getting current production version

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir=/Library/Management/erase-install --ignore-cache --raw --auto 

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacPro6,1

Board ID         : Mac-F60DEB81FF30ACF6
OS Version       : 11.2.1
Build ID         : 20D74

 #  ProductID       Version    Build    Post Date   Title                          
 1  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 2  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
 3  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 4  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
 5  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 6  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 7  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
 8  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 9  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
10  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
11  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
12  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
13  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
14  071-00838       11.2       20D64    2021-02-01  macOS Big Sur                  
No valid build found for this hardware
   [run_installinstallmacos] No disk image found. I guess nothing got downloaded.
   [erase-install] 'jamfHelper' ended

**Comment by grahampugh** [comment]
There is no full installer available for 11.2.1 other than the ipsw file for M1 Macs, which are not suitable for upgrade/erase Workflows so I have not included in this script. 

11.2 is still the latest full installer available.
