### ISSUE TITLE
Add power source check, move space check forward

### ISSUE THREAD

**Issue by mani2care** [grahampugh/erase-install#66]
Hi number of proactive requests 
 
issue 1: Battery percentage, adapter connected or not, and disk space check, and add the retrying an option 

kindly make it before getting download the OS.

last minute saying your mac not having sufficient space or system shutdown sue to poser failur.

because downloading the OS it pain around 8 to 12 GB of data 

<img width="1038" alt="Screenshot 2021-02-19 at 1 50 18 PM" src="https://user-images.githubusercontent.com/52978899/108478394-7194e900-72ba-11eb-98b4-5cb763397ff6.png">
: 

issue 2

pls add one more option for the OS validation even --overwrite to avoid the spending download and internet.

for example, downloaded the OS in as its path and rerunning the same command it should take the existing OS because it downloaded as success without any issue 

is that you have validated and kept the file and use it again instant of --0verrwide 

issue 3: once the specification checked it should retry because selected the --0verrwide again I need to spend time and the internet to get it to download.
getting failed due to space issue there is no option for the retry and validate the space again.

<img width="1405" alt="Screenshot 2021-02-19 at 1 59 02 PM" src="https://user-images.githubusercontent.com/52978899/108478714-dbad8e00-72ba-11eb-85f8-3da11966505e.png">

pls, advise if it wrong.

**Comment by grahampugh** [comment]
Regarding Issue 1:

I will consider moving the space and power checks to the beginning. 

I don't see the need for a retry option. That would require some sort of prompt, and this script is designed as far as possible to be run programmatically. If you need to retry, run the script again.

Regarding Issue 2:

The option you seem to be asking for already exists. If you don't use `--overwrite`, the any existing installer on the device is used. If there is no existing installer, one is downloaded. You can also use `--update` which checks the version of the installer matches your requested one, and uses it if it is still up to date, but replaces it if it is old.

Regarding Issue 3:

I don't see the need for a retry option. That would require some sort of prompt, and this script is designed as far as possible to be run programmatically. If you need to retry, run the script again (without `--overwrite`, or with `--update`, as appropriate).

**Comment by grahampugh** [comment]
I believe all the suggestions here have now been addressed.
