### ISSUE TITLE
OS security patch update issue 

### ISSUE THREAD

**Issue by mani2care** [grahampugh/erase-install#67]
Hi ,

I am looking forward to updating the current OS either Mojave, Catalina , big sur, as up to date..........

when I'm trying this upgrading the OS and with download full installed.

if not wrong is this only to get download the full installer OS.

is not having the option to do security patch update /install.

attaching file if its full installed its working fine. if its security patch update is not the right one.
can you pls suggest?

<img width="734" alt="Screenshot 2021-02-22 at 5 06 55 PM" src="https://user-images.githubusercontent.com/52978899/108703621-df4a4a80-7530-11eb-8fc5-910462cb40db.png">

<img width="834" alt="Screenshot 2021-02-22 at 5 06 38 PM" src="https://user-images.githubusercontent.com/52978899/108703601-d8233c80-7530-11eb-91d1-ebe4d271d342.png">

**Comment by grahampugh** [comment]
You cannot obtain the Catalina Security Patch as a full installer. You have to use Software Update for that. This is normal for all previous versions of macOS - Apple do not integrate security patches into the final build of the previous macOS.
