### ISSUE TITLE
Apple M1

### ISSUE THREAD

**Issue by rossoneris** [grahampugh/erase-install#69]
Hi,
Have a M1 (model identifier MacbookPro17,1) 
Should all the commands also work for these new models ? - seems no valid build exist for this hardware according to error message when trying to run a eraes-install.sh --samos

**Comment by rossoneris** [comment]
sorry - I was running Beta OS version on this model I tried with

**Comment by grahampugh** [comment]
You can use the `--Beta` option along with your seed program to obtain beta versions. For example, `--seedprogram` PublicSeed.
