### ISSUE TITLE
Error No such file or directory 

### ISSUE THREAD

**Issue by motionbug** [grahampugh/erase-install#7]
Awesome script, just an FYI when testing today.

Doesn't do an erase install, stops at

```
./erase-install.sh: line 294: /Contents/Resources/startosinstall: No such file or directory
```
Thinking there is an issue with path stated in the variable, but I am unsure... 

```
"$installmacOSApp/Contents/Resources/startosinstall" --applicationpath "$installmacOSApp" --eraseinstall --agreetolicense --nointeraction
```

**Comment by grahampugh** [comment]
Can you make sure you have the latest version? I changed things around a lot last night, including fixing a bug when using the `—overwrite` option.
