### ISSUE TITLE
applicationpath is depreciated

### ISSUE THREAD

**Issue by motionbug** [grahampugh/erase-install#8]
If macOS is 10.4 and above then there is no need for the switch "--applicationpath"

**Comment by grahampugh** [comment]
10.4, 10.13.4, or 10.14?

**Comment by motionbug** [comment]
oops... man duh 10.14

sorry mate

**Comment by grahampugh** [comment]
OK thanks. Does it break the command if you leave it in?

**Comment by grahampugh** [comment]
Confirmed that the command still works with `--applicationpath` option in 10.14. So it’s safe to leave it in place until it’s not required.
