### ISSUE TITLE
Basic user confirmation prompt for non-Jamf devices

### ISSUE THREAD

**Issue by securitygeneration** [grahampugh/erase-install#84]
It would be great to have a `--confirm` option that works for non-Jamf devices to do some basic user confirmation prior to proceeding with an erase/install.

**Comment by grahampugh** [comment]
Hi @securitygeneration I'd forgotten that I already implemented this in one of the last releases! Can you try it - I don't think I tested it.

https://github.com/grahampugh/erase-install/blob/main/erase-install.sh#L1142-L1167

**Comment by securitygeneration** [comment]
Thank goodness for `--test-run` 😅 

```   
[erase-install] WARNING! Running /Volumes/Install_macOS_11.3.1-20E241/Applications/Install macOS Big Sur.app with eraseinstall option

54:57: syntax error: Expected “,” but found identifier. (-2741)
   [erase-install] User CONFIRMED erase/install
   [erase-install] Run without '--test-run' to run this command:
/Volumes/Install_macOS_11.3.1-20E241/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall --eraseinstall --forcequitapps --pidtosignal --pidtosignal 66083 --agreetolicense --nointeraction
```

**Comment by grahampugh** [comment]
Hmm, OK, I guess I need to unenrolled a Mac from Jamf to test this :)

**Comment by grahampugh** [comment]
Please can you try with v0.20.0? I think I have fixed this now. I also added a `--depnotify` option in case you want to use DEPNotify for the progress and confirmation dialogs (at present you have to ensure DEPNotify is pre-installed using your own means).
