### ISSUE TITLE
--power-wait-limit does not work 

### ISSUE THREAD

**Issue by tajinderchana** [grahampugh/erase-install#88]
Have used this in jamfPro and have found that this does not work. From a very high level glance it does not seem to be called when the script us run.

**Comment by grahampugh** [comment]
@tajinderchana did you add the command `--power-wait-limit=XY`? (the `=` sign is necessary in Jamf Pro)

**Comment by tajinderchana** [comment]
Yea i added it as: `--power-wait-limit=300` and `--power-wait-limit 300`

I may be wrong but when looking at the script i couldnt find `power_wait_timer` being called in the script as you are using `check_power` in the `check_power_status` function. `--check-power` works fine 

Hope this helps

**Comment by grahampugh** [comment]
And did you also add `--check-power`? `--power-wait-limit` only works if `--check-power` is also selected.

**Comment by tajinderchana** [comment]
I didn't try it with both. I have just tested and it does work, sorry i must have missed that in the documentation.
