### ISSUE TITLE
Support for VMs? 

### ISSUE THREAD

**Issue by lennyvaknine43** [grahampugh/erase-install#9]
Is it possible to get this to work for VMware Fusion VM's? Here is my current output. It seems as though `Unsupported Board ID` is the issue. 

`Script result: 
   [erase-install] Script execution started: Tue Oct 16 11:38:44 EDT 2018
   [erase-install] Looking for existing installer
   [find_existing_installer] No valid installer found.
   [erase-install] Starting download process
   [run_installinstallmacos] Downloading installinstallmacos.py to /Library/Management/erase-install
/Library/Application Support/JAMF/tmp/eraseInstall.sh: line 120:  8575 Killed: 9               "$jamfHelper" -windowType hud -windowPosition ul -title "Downloading macOS" -alignHeading center -alignDescription left -description "We need to download the macOS installer to your computer; this will take several minutes." -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
   [run_installinstallmacos] Checking that selected version 10.14 is available

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBook10,1
Board ID         : latform
OS Version       : 10.14
Build ID         : 18A391

 #  ProductID       Version    Build    Post Date   Title                          Notes
 1  041-08708       10.14      18A391   2018-09-24  macOS Mojave                   Unsupported Board ID
 2  091-95774       10.13.6    17G2208  2018-07-30  macOS High Sierra              Unsupported Board ID
 3  091-94326       10.13.6    17G65    2018-07-11  macOS High Sierra              Unsupported Board ID
 4  041-03369       10.14      18A384a  2018-09-12  macOS Mojave Beta              Unsupported Board ID
Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 710, in <module>
    main()
  File "/Library/Management/erase-install/installinstallmacos.py", line 641, in main
    'to select a valid build to download.\n' % answer)
UnboundLocalError: local variable 'answer' referenced before assignment
hdiutil: attach: cannot convert "" to URL
hdiutil: attach failed - Invalid argument

   [main] WARNING! Running  with eraseinstall option

   [erase-install] Opening jamfHelper full screen message
/Library/Application Support/JAMF/tmp/eraseInstall.sh: line 243: /Contents/Resources/startosinstall: No such file or directory`

**Comment by grahampugh** [comment]
Hi @lennyvaknine43 

I have now updated the fork of `installinstallmacos.py` which is used by this script to include a check for VMs. If a VM is detected, it will not check for Build ID compatibility, so you'll get the full choice of builds.
Let me know if you have any problems.

Cheers,
Graham
