### ISSUE TITLE
macOS 11.3.1 - Add packages to be installed after the reinstallation

### ISSUE THREAD

**Issue by user1233445** [grahampugh/erase-install#90]
Hi guys,

I created a folder called "extras" in the working dir (/Library/Management/extras) and insert the signed package in it. But the package won't be installed. Is there a log file or something else to check where the issue is?

**Comment by grahampugh** [comment]
The working directory is `/Library/Management/erase-install`, not `/Library/Management`. So you need to create `/Library/Management/erase-install/extras` (or add the `--extras` key if you want to point somewhere else).

**Comment by user1233445** [comment]
Problem solved. Thank you!

 

From: Graham Pugh ***@***.***>
Reply to: grahampugh/erase-install ***@***.***>
Date: Tuesday, 18. May 2021 at 09:26
To: grahampugh/erase-install ***@***.***>
Cc: "Schäfer, Niklas" ***@***.***>, Author ***@***.***>
Subject: Re: [grahampugh/erase-install] macOS 11.3.1 - Add packages to be installed after the reinstallation (#90)

 

The working directory is /Library/Management/erase-install, not /Library/Management. So you need to create /Library/Management/erase-install/extras (or add the --extras key if you want to point somewhere else).
