### ISSUE TITLE
MacOS 11.3.1 failed to erase

### ISSUE THREAD

**Issue by RenderMeWell** [grahampugh/erase-install#91]
Thank you for all the work you've put on this script. I've tried to erase and reinstall using your script, and it keep failing on the icon. I'm not too sure what's going on. 

```
`testaccount@0561 ~ % sudo jamf policy -event erase-bigsur
Password:
Checking for policies triggered by "erase-bigsur" for user "testaccount"...
Executing Policy Erase Reinstall Big Sur
Running script Erase-Install...
Script exit code: 0
Script result: 
   [erase-install] v0.20.1 script execution started: Tue May 18 16:00:55 EDT 2021
   [erase-install] Caffeinating this script (pid=5576)
45000000
   [free_space_check] OK - 159669052 KB free disk space detected
   [erase-install] Looking for existing installer
   [find_existing_installer] Installer sparse image found at /Library/Management/erase-install/Install_macOS_11.3.1-20E241.sparseimage.
/dev/disk4          	GUID_partition_scheme          	
/dev/disk4s1        	EFI                            	
/dev/disk4s2        	Apple_HFS                      	/Volumes/Install_macOS_11.3.1-20E241
   [check_installer_is_valid] Checking validity of /Volumes/Install_macOS_11.3.1-20E241/Applications/Install macOS Big Sur.app.
   [check_installer_is_valid] Using Build value from com_apple_MobileAsset_MacSoftwareUpdate.xml
Volume Shared Support on disk5s2 force-unmounted
   [check_installer_is_valid] Installer: 20E241 ; System: 20E241 : valid build.
yes testaccount is a member of staff
yes testaccount is a member of admin
   [get_user_details] testaccount is a Volume Owner
   [check_password] Success: the password entered is the correct login password for testaccount.

   [erase-install] WARNING! Running /Volumes/Install_macOS_11.3.1-20E241/Applications/Install macOS Big Sur.app with eraseinstall option

   [erase-install] Opening jamfHelper full screen message (language=en)
   [get_user_details] updating preboot files (takes a few seconds)...
/Library/Application Support/JAMF/tmp/Erase-Install: line 1386:  5702 Killed: 9               "$install_macos_app/Contents/Resources/startosinstall" "${install_args[@]}" --pidtosignal $PID --agreetolicense --nointeraction --stdinpass --user "$account_shortname" "${install_package_list[@]}" <<< $account_password
   [erase-install] 'jamfHelper' ended
/Library/Application Support/JAMF/tmp/Erase-Install: line 213:  5690 Terminated: 15          "$jamfHelper" -windowType $window_type -title "${!dialog_erase_title}" -heading "${!dialog_erase_title}" -description "${!dialog_erase_desc}" -icon "$dialog_erase_icon"
   [erase-install] 'caffeinate' ended

Submitting log to https://jss.
```

**Comment by grahampugh** [comment]
It's not failing on the icon. That is just the jamfHelper being force-closed by the startosinstall command. But it's failing to force a reboot for some reason. What commands do you have in your policy?

**Comment by RenderMeWell** [comment]
I'm using. 
Parameter 4: --force-curl
Parameter 5: --erase

**Comment by ayotec2015** [comment]
![Image from iOS (2)](https://user-images.githubusercontent.com/6651900/121918258-cbb82f00-cd2d-11eb-8483-fcf23de1762c.jpg)

HI I am getting this error above. I have this running in the execute command 
/Library/Management/erase-install/erase-install.sh --os=11 —erase --reinstall --confirm

To wipe and re-install  Big Sur.

**Comment by grahampugh** [comment]
@ayotec2015 you shouldn't use `--erase` and `--reinstall` in the same command - they are mutually exclusive options. To wipe the Mac and install fresh, use only `--erase`.

However, that is not the cause of your problem. Your problem is with `startosinstall` itself failing. I cannot help you with that.

**Comment by grahampugh** [comment]
@RenderMeWell I forgot to answer you sooner. There is no crash shown in those logs. The script kills jamfHelper and caffeinate at the end of the run. I would have another look at your jamf policy. I do not see any sign of the `--force-curl` option being used in the output, so I suspect you've configured something wrong. Did you add the parameters to the script rather than the policy, for example?

**Comment by RenderMeWell** [comment]
Thank you. It was an issue with that machine only. I tested it in a new M1 and was able to get it fully working. 

Sorry I was on vacation.
