### ISSUE TITLE
French translation ?

### ISSUE THREAD

**Issue by Darkomen78** [grahampugh/erase-install#92]
Hi ! 
I really like this script, I use it to make a imitation of the erase&install action menu (with Hello-IT) like iOS can do in settings.

Do you need a french translation for the notify text ?

**Comment by grahampugh** [comment]
Yes, a French translation would be great! Could you do it as a Pull Request? Basically we need `_fr` versions of all the strings here: https://github.com/grahampugh/erase-install/blob/main/erase-install.sh#L50-L148

**Comment by Darkomen78** [comment]
Ok !
I've make a pull request.
